// This file has been generated by Specta. DO NOT EDIT.
import Foundation

/// Either side may send this to abort an in-flight request identified
/// by `id`.
public struct CancelFrame: Codable {
    public let id: UInt32
}

/// Failure response correlated with a [`RequestFrame`] by `id`.
public struct ErrorFrame: Codable {
    public let id: UInt32
    public let code: UInt32
    public let message: String
    public let details: String?
}

/// Unsolicited notification pushed by a client (e.g. browser tab
/// activation, Word selection change).
public struct EventFrame: Codable {
    public let action: String
    public let payload: String?
}

/// Top-level envelope sent in both directions on the bridge. Every
/// message is a `Frame`; the [`FrameKind`] discriminator identifies the
/// payload variant.
public struct Frame: Codable {
    public let kind: FrameKind
}

/// Frame payload. Serialized as an externally-tagged JSON object —
/// `{ "Request": { ... } }` — to match the shape the browser extension
/// already consumes.
public enum FrameKind {
    case request(RequestFrame)
    case response(ResponseFrame)
    case event(EventFrame)
    case error(ErrorFrame)
    case cancel(CancelFrame)
    case register(RegisterFrame)
}

/// Mandatory first frame on every connection. Identifies the host
/// process (the bridge) and the application process being represented.
/// 
/// `app_pid` is the OS PID for clients that have one (browsers via the
/// native-messaging host, the macOS launcher representing Safari).
/// Sandboxed clients without access to a real PID — Office.js add-ins
/// in particular — synthesize a stable per-session identifier and set
/// `app_kind` to a logical name (e.g. `"microsoft-word"`) so the
/// desktop can locate the client without relying on OS process lookup.
public struct RegisterFrame: Codable {
    public let hostPid: UInt32
    public let appPid: UInt32
    public let appKind: String?

    private enum CodingKeys: String, CodingKey {
        case hostPid = "host_pid"
        case appPid = "app_pid"
        case appKind = "app_kind"
    }
}

/// Desktop-initiated request to a connected client.
public struct RequestFrame: Codable {
    public let id: UInt32
    public let action: String
    public let payload: String?
}

/// Client reply to a [`RequestFrame`], correlated by `id`.
public struct ResponseFrame: Codable {
    public let id: UInt32
    public let action: String
    public let payload: String?
}

// MARK: - FrameKind Codable Implementation
extension FrameKind: Codable {
    private enum CodingKeys: String, CodingKey {
        case request = "Request"
        case response = "Response"
        case event = "Event"
        case error = "Error"
        case cancel = "Cancel"
        case register = "Register"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        guard container.allKeys.count == 1, let key = container.allKeys.first else {
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Expected exactly one key for externally-tagged enum"
                )
            )
        }
        switch key {
        case .request:
            self = .request(try container.decode(RequestFrame.self, forKey: .request))
        case .response:
            self = .response(try container.decode(ResponseFrame.self, forKey: .response))
        case .event:
            self = .event(try container.decode(EventFrame.self, forKey: .event))
        case .error:
            self = .error(try container.decode(ErrorFrame.self, forKey: .error))
        case .cancel:
            self = .cancel(try container.decode(CancelFrame.self, forKey: .cancel))
        case .register:
            self = .register(try container.decode(RegisterFrame.self, forKey: .register))
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .request(let value):
            try container.encode(value, forKey: .request)
        case .response(let value):
            try container.encode(value, forKey: .response)
        case .event(let value):
            try container.encode(value, forKey: .event)
        case .error(let value):
            try container.encode(value, forKey: .error)
        case .cancel(let value):
            try container.encode(value, forKey: .cancel)
        case .register(let value):
            try container.encode(value, forKey: .register)
        }
    }
}
