// This file has been generated by Specta. DO NOT EDIT.
import Foundation

/// Either side may send this to abort an in-flight request identified
/// by `id`.
public struct CancelFrame: Codable {
    public let id: UInt32
}

/// Failure response correlated with a [`RequestFrame`] by `id`.
public struct ErrorFrame: Codable {
    public let id: UInt32
    public let code: UInt32
    public let message: String
    public let details: Payload?
}

/// Unsolicited notification pushed by a client (e.g. browser tab
/// activation, Word selection change).
public struct EventFrame: Codable {
    public let action: String
    public let payload: Payload?
}

/// Top-level envelope sent in both directions on the bridge. Every
/// message is a `Frame`; the [`FrameKind`] discriminator identifies the
/// payload variant.
public struct Frame: Codable {
    public let kind: FrameKind
}

/// Frame payload. Serialized as an externally-tagged JSON object —
/// `{ "Request": { ... } }` — to match the shape the browser extension
/// already consumes.
public enum FrameKind {
    case request(RequestFrame)
    case response(ResponseFrame)
    case event(EventFrame)
    case error(ErrorFrame)
    case cancel(CancelFrame)
    case register(RegisterFrame)
    case shutdown(ShutdownFrame)
}
// MARK: - FrameKind Codable Implementation
extension FrameKind: Codable {
    private enum CodingKeys: String, CodingKey {
        case request = "Request"
        case response = "Response"
        case event = "Event"
        case error = "Error"
        case cancel = "Cancel"
        case register = "Register"
        case shutdown = "Shutdown"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        
        if container.allKeys.count != 1 {
            throw DecodingError.dataCorrupted(
                DecodingError.Context(codingPath: decoder.codingPath, debugDescription: "Invalid number of keys found, expected one.")
            )
        }

        let key = container.allKeys.first!
        switch key {
        case .request:
            let data = try container.decode(RequestFrame.self, forKey: .request)
            self = .request(data)
        case .response:
            let data = try container.decode(ResponseFrame.self, forKey: .response)
            self = .response(data)
        case .event:
            let data = try container.decode(EventFrame.self, forKey: .event)
            self = .event(data)
        case .error:
            let data = try container.decode(ErrorFrame.self, forKey: .error)
            self = .error(data)
        case .cancel:
            let data = try container.decode(CancelFrame.self, forKey: .cancel)
            self = .cancel(data)
        case .register:
            let data = try container.decode(RegisterFrame.self, forKey: .register)
            self = .register(data)
        case .shutdown:
            let data = try container.decode(ShutdownFrame.self, forKey: .shutdown)
            self = .shutdown(data)
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        
        switch self {
        case .request(let data):
            try container.encode(data, forKey: .request)
        case .response(let data):
            try container.encode(data, forKey: .response)
        case .event(let data):
            try container.encode(data, forKey: .event)
        case .error(let data):
            try container.encode(data, forKey: .error)
        case .cancel(let data):
            try container.encode(data, forKey: .cancel)
        case .register(let data):
            try container.encode(data, forKey: .register)
        case .shutdown(let data):
            try container.encode(data, forKey: .shutdown)
        }
    }
}


/// Inline JSON payload carried by Request/Response/Event frames.
///
/// Mirrors `euro_bridge_protocol::frame::Payload` on the wire: any JSON
/// value (`null`, `Bool`, `Double`, `String`, array, object) embedded
/// inline in the outer Frame envelope. The Rust producer hands the
/// payload to serde as a `RawValue`, so consumers see the original
/// shape rather than an escaped JSON string layer.
///
/// Numbers are decoded as `Double` only — Chrome's native-messaging
/// bridge cannot round-trip 64-bit integers safely, so the wire never
/// carries one. Use `.number(Double)` for any numeric value.
public enum Payload: Codable {
    case null
    case bool(Bool)
    case number(Double)
    case string(String)
    case array([Payload])
    case object([String: Payload])

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
            return
        }
        if let value = try? container.decode(Bool.self) {
            self = .bool(value)
            return
        }
        if let value = try? container.decode(Double.self) {
            self = .number(value)
            return
        }
        if let value = try? container.decode(String.self) {
            self = .string(value)
            return
        }
        if let value = try? container.decode([Payload].self) {
            self = .array(value)
            return
        }
        if let value = try? container.decode([String: Payload].self) {
            self = .object(value)
            return
        }
        throw DecodingError.dataCorruptedError(
            in: container,
            debugDescription: "Payload: value did not match any known JSON shape"
        )
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .null:
            try container.encodeNil()
        case .bool(let value):
            try container.encode(value)
        case .number(let value):
            try container.encode(value)
        case .string(let value):
            try container.encode(value)
        case .array(let value):
            try container.encode(value)
        case .object(let value):
            try container.encode(value)
        }
    }
}

/// Mandatory first frame on every connection. Identifies the host
/// process (the bridge) and the application process being represented.
/// 
/// `app_pid` is the OS PID for clients that have one (browsers via the
/// native-messaging host, the macOS launcher representing Safari).
/// Sandboxed clients without access to a real PID — Office.js add-ins
/// in particular — synthesize a stable per-session identifier and set
/// `app_kind` to a logical name (e.g. `"microsoft-word"`) so the
/// desktop can locate the client without relying on OS process lookup.
public struct RegisterFrame: Codable {
    public let hostPid: UInt32
    public let appPid: UInt32
    public let appKind: String?

    private enum CodingKeys: String, CodingKey {
        case hostPid = "host_pid"
        case appPid = "app_pid"
        case appKind = "app_kind"
    }
}

/// Desktop-initiated request to a connected client.
public struct RequestFrame: Codable {
    public let id: UInt32
    public let action: String
    public let payload: Payload?
}

/// Client reply to a [`RequestFrame`], correlated by `id`.
public struct ResponseFrame: Codable {
    public let id: UInt32
    public let action: String
    public let payload: Payload?
}

/// Desktop-initiated request that the receiving client (currently:
/// browser native-messaging hosts) terminate cleanly. Sent when the
/// desktop has just installed an updated messenger binary on disk and
/// wants stale connections to drop so the browser respawns from the new
/// binary. The `reason` is informational only (logged by the recipient).
public struct ShutdownFrame: Codable {
    public let reason: String?
}

