// This file has been generated by Specta. Do not edit this file manually.
/**  A persisted activity row as returned to the client. */
export type Activity = {
	id: string;
	name: string;
	process_name: string;
	window_title: string;
	icon_asset_id: string | null;
	started_at: string;
	ended_at: string | null;
	created_at: string;
	updated_at: string;
};

/**
 *  JSON error body returned by the activity service on non-2xx responses.
 *
 *  Mirrors the shape used by `be-update-service` so the desktop client can
 *  decode failures uniformly across HTTP services.
 */
export type ActivityErrorResponse = {
	error: string;
	message: string;
	details?: string | null;
};

/**
 *  Request body for `POST /activities`.
 *
 *  `icon_png_base64` carries an optional PNG icon as standard-base64. We
 *  take JSON-with-base64 instead of `multipart/form-data` so the wire shape
 *  stays specta-friendly; in practice icons are app-launcher size (a few
 *  hundred bytes to ~50 KB), well under the monolith's 2 MiB body limit.
 */
export type InsertActivityRequest = {
	id?: string | null;
	name: string;
	process_name: string;
	window_title: string;
	icon_png_base64?: string | null;
	started_at: string;
	ended_at?: string | null;
};

/**  Response body for `POST /activities`. */
export type InsertActivityResponse = {
	activity: Activity;
};

/**
 *  Query parameters for `GET /activities`.
 *
 *  Both fields are optional. When `limit` is omitted the server falls back to
 *  [`DEFAULT_LIST_LIMIT`]; values greater than [`MAX_LIST_LIMIT`] are rejected
 *  rather than silently clamped.
 */
export type ListActivitiesQuery = {
	limit?: number | null;
	offset?: number | null;
};

/**  Response body for `GET /activities`. */
export type ListActivitiesResponse = {
	activities: Activity[];
};
