// This file has been generated by Specta. Do not edit this file manually.
/**
 *  A persisted parent activity as returned to the client.
 * 
 *  One row per `(user_id, identity_key)` — `identity_key` is a lowercased
 *  process name (default strategy) or a base domain label (browser
 *  strategy, with the public suffix stripped). `last_used_at` advances on
 *  every new session insert and on each session's closing PATCH so the
 *  rail can sort by recency without scanning the children table.
 */
export type Activity = {
	id: string,
	user_id: string,
	identity_key: string,
	display_name: string,
	icon_asset_id: string | null,
	last_used_at: string,
	created_at: string,
	updated_at: string,
};

/**
 *  JSON error body returned by the activity service on non-2xx responses.
 * 
 *  Mirrors the shape used by `be-update-service` so the desktop client
 *  can decode failures uniformly across HTTP services.
 */
export type ActivityErrorResponse = {
	error: string,
	message: string,
	details?: string | null,
};

/**
 *  Identity-portion of a session insert.
 * 
 *  Travels alongside the session in [`InsertActivitySessionRequest`] so
 *  the server can upsert the parent by `(user_id, identity_key)` in the
 *  same transaction as the session insert. `display_name` is *set-once*
 *  on the server: subsequent inserts that arrive with a different value
 *  are ignored, so a future rename endpoint is the only thing that ever
 *  mutates it. `icon_png_base64` carries the icon as standard-base64
 *  (JSON-friendly, well under the monolith's body limit at app-launcher
 *  sizes).
 */
export type ActivityInsert = {
	identity_key: string,
	display_name: string,
	icon_png_base64?: string | null,
};

/**
 *  One persisted focus run.
 * 
 *  `started_at` is client-supplied (the desktop owns wall-clock for the
 *  focus event); `ended_at` is ratcheted forward by heartbeat PATCHes and
 *  finalised on `Stopping`. `url` and `window_title` are optional because
 *  not every strategy produces them (the default strategy has no URL; an
 *  extension-less browser tab has no title yet).
 */
export type ActivitySession = {
	id: string,
	activity_id: string,
	process_name: string,
	process_id: number | null,
	window_title: string | null,
	url: string | null,
	started_at: string,
	ended_at: string | null,
	created_at: string,
	updated_at: string,
};

/**
 *  One element of [`ListActivitiesResponse`].
 * 
 *  Embeds the most recent session inline so the rail can decide "is this
 *  activity live right now?" (`latest_session.ended_at IS NULL`) without
 *  a second fetch. `latest_session` is `None` only for parents that have
 *  no sessions yet — a transient state that should never appear in
 *  practice but is allowed to keep the wire shape monotonic under
 *  concurrent inserts.
 */
export type ActivityWithLatestSession = {
	latest_session: ActivitySession | null,
} & Activity;

/**
 *  Request body for `POST /activity-sessions`.
 * 
 *  `session_id` and `ended_at` are sent at insert time so a subsequent
 *  PATCH targets the same row (idempotent retries / heartbeat) and an
 *  unexpected crash before the first heartbeat still leaves a bounded
 *  `ended_at` instead of `NULL`.
 */
export type InsertActivitySessionRequest = {
	session_id?: string | null,
	activity: ActivityInsert,
	process_name: string,
	process_id?: number | null,
	window_title?: string | null,
	url?: string | null,
	started_at: string,
	ended_at?: string | null,
};

/**
 *  Response body for `POST /activity-sessions`.
 * 
 *  Always carries both rows: the parent (which may have been freshly
 *  upserted or merely bumped) and the newly-inserted session. The client
 *  hands both to the timeline rail as a single atomic update so the rail
 *  never has to render a parent without knowing whether it is "live".
 */
export type InsertActivitySessionResponse = {
	activity: Activity,
	session: ActivitySession,
};

/**  Query parameters for `GET /activities` and `GET /activities/{id}/sessions`. */
export type ListActivitiesQuery = {
	limit?: number | null,
	offset?: number | null,
};

/**  Response body for `GET /activities`. */
export type ListActivitiesResponse = {
	activities: ActivityWithLatestSession[],
};

/**  Response body for `GET /activities/{id}/sessions`. */
export type ListActivitySessionsResponse = {
	sessions: ActivitySession[],
};

/**
 *  Request body for `PATCH /activity-sessions/{id}`.
 * 
 *  All fields are optional; missing fields are left untouched on the row.
 *  Used by the desktop client to (a) ratchet `ended_at` forward on every
 *  heartbeat tick and at session transitions, and (b) update
 *  `window_title` / `url` when an intra-domain SPA navigation reports a
 *  title-only change.
 */
export type UpdateActivitySessionRequest = {
	window_title?: string | null,
	url?: string | null,
	ended_at?: string | null,
};

/**  Response body for `PATCH /activity-sessions/{id}`. */
export type UpdateActivitySessionResponse = {
	session: ActivitySession,
};
