// This file has been generated by Specta. Do not edit this file manually.
/**  Request body for `POST /auth/login-token/associate`. */
export type AssociateLoginTokenRequest = {
	code_challenge: string,
};

/**
 *  JSON error body returned by the auth service on non-2xx responses.
 * 
 *  Mirrors the shape used by `be-update-service` and `be-activity-service`
 *  so the desktop client can decode failures uniformly across HTTP services.
 *  The `error` field is the stable machine-readable kind (see
 *  [`crate::error_kinds`]); `message` is human-readable; `details` is an
 *  optional free-form string for additional context.
 */
export type AuthErrorResponse = {
	error: string,
	message: string,
	details?: string | null,
};

/**
 *  Wire-level union returned by every endpoint that mints a session.
 *  `untagged` so existing desktop clients keep deserialising into
 *  [`TokenResponse`] while the SPA sees the cookie-only [`UserResponse`].
 */
export type AuthSuccessResponse = TokenResponse | UserResponse;

/**  Request body for `POST /auth/email/check`. */
export type CheckEmailRequest = {
	email: string,
};

/**  Response body for `POST /auth/email/check`. */
export type CheckEmailResponse = {
	status: CheckEmailStatus,
	/**  Populated only when `status == Oauth`. */
	provider?: Provider | null,
};

/**  Outcome of an email lookup performed via `POST /auth/email/check`. */
export type CheckEmailStatus = 
/**  No account is registered with that email. */
"not_found" | 
/**  Account exists and authenticates with a password. */
"password" | 
/**  Account exists and authenticates via a third-party provider. */
"oauth";

export type Claims = {
	sub: string,
	email: string,
	display_name?: string | null,
	exp: bigint,
	iat: bigint,
	token_type: string,
	role: Role,
	aud?: string,
	email_verified?: boolean,
	/**
	 *  RFC 7519 JWT ID. Guarantees that two tokens minted for
	 *  the same subject within the same second never collide
	 *  after hashing (see refresh-token rotation).
	 */
	jti?: string,
};

/**
 *  Request body for `POST /auth/oauth/google/id-token`.
 * 
 *  Used by mobile after a native Google Sign-In flow: the client sends
 *  the ID token issued directly by Google's iOS / Android SDK and the
 *  backend verifies it against Google's JWKS without an authorization
 *  code round-trip. The optional `nonce` is checked against the JWT's
 *  nonce claim when supplied.
 */
export type GoogleIdTokenLoginRequest = {
	id_token: string,
	nonce?: string | null,
};

/**  Request body for `POST /auth/login-token/exchange`. */
export type LoginByLoginTokenRequest = {
	token: string,
};

/**
 *  Request body for `POST /auth/login`.
 * 
 *  Encoded as a discriminated union: the `kind` tag selects the
 *  credential variant, mirroring the gRPC `oneof` it replaces while
 *  staying friendly to JSON consumers and TypeScript codegen.
 * 
 *  The desktop-pairing `login_token` is **not** part of this body — it
 *  is captured at OAuth URL issue time on
 *  [`ThirdPartyAuthUrlRequest`] and read off the `oauth_state` row
 *  during code exchange. Apple Sign In's form-post flow doesn't surface
 *  `code`/`state` to the SPA, so an at-callback mechanism is structurally
 *  impossible for that provider — moving every provider to the
 *  at-issue-time path keeps the contract uniform.
 */
export type LoginRequest = { kind: "email_password"; login: string; password: string } | { kind: "third_party"; provider: Provider; code: string; state: string };

/**
 *  Request body for `POST /auth/oauth/mobile/url`.
 * 
 *  The mobile app generates a PKCE pair locally and submits the
 *  challenge here; the backend stamps that challenge as the OAuth
 *  `state` (so it round-trips through Google and identifies the device
 *  in the callback) and as the eventual `login_token` row that the
 *  device redeems via `/auth/login-token/exchange`.
 */
export type MobileThirdPartyAuthUrlRequest = {
	provider: Provider,
	code_challenge: string,
	code_challenge_method: string,
};

/**
 *  Third-party identity provider supported by the auth service.
 * 
 *  Wire format is lowercase JSON (`"google"`, `"github"`, `"apple"`)
 *  so it reads naturally in URLs and request bodies.
 */
export type Provider = "google" | "github" | "apple";

/**  Request body for `POST /auth/register`. */
export type RegisterRequest = {
	email: string,
	password: string,
	display_name?: string | null,
};

export type Role = "Free" | "Tier1";

/**
 *  Request body for `POST /auth/oauth/url`.
 * 
 *  The optional `login_token` is the desktop client's PKCE challenge —
 *  when present, the backend stamps it onto the `oauth_state` row so the
 *  eventual callback can pair the device without the SPA round-tripping
 *  the value through the login request body. Mirrors the convention the
 *  mobile flow already uses via `MobileThirdPartyAuthUrlRequest`.
 */
export type ThirdPartyAuthUrlRequest = {
	provider: Provider,
	login_token?: string | null,
};

/**  Response body for `POST /auth/oauth/url`. */
export type ThirdPartyAuthUrlResponse = {
	url: string,
};

/**
 *  Bearer-mode session response, used by non-browser clients (desktop /
 *  mobile) that send `Authorization: Bearer …` and need the tokens in
 *  the JSON body.
 */
export type TokenResponse = {
	access_token: string,
	refresh_token: string,
	/**  Lifetime of `access_token` in seconds. */
	expires_in: bigint,
};

/**
 *  Public-facing user profile. Mirrors the subset of [`crate::Claims`]
 *  the SPA renders; never carries the JWT itself.
 */
export type UserInfo = {
	id: string,
	email: string,
	display_name?: string | null,
	email_verified: boolean,
	role: Role,
};

/**
 *  Cookie-mode session response. Tokens are delivered via `Set-Cookie`
 *  (HttpOnly access + refresh); the JSON body carries only the user
 *  profile so a compromised renderer cannot read the access token off
 *  the response.
 */
export type UserResponse = {
	user: UserInfo,
};

/**  Request body for `POST /auth/email/verify`. */
export type VerifyEmailRequest = {
	token: string,
};
