// This file has been generated by Specta. Do not edit this file manually.
/**
 *  Top-level cloud-synced settings blob. Sections are addressed
 *  individually so clients only touch the fields that apply to their
 *  platform; unknown sections and unknown fields within sections are
 *  preserved verbatim through `extras` so a newer release of one
 *  client never drops fields written by another.
 * 
 *  The wire format the server stores is exactly this struct: an opaque
 *  JSON document. Protocol metadata — schema version, `updated_at`,
 *  optimistic-concurrency baseline — rides on the request / response
 *  envelopes, not inside the blob, so this struct deliberately carries
 *  neither a version nor a timestamp.
 * 
 *  Fresh-install defaults are whatever each section's [`Default`] impl
 *  produces. Per-field `#[serde(default)]` rather than struct-level so a
 *  missing wire field falls back to its *type's* `Default::default()`
 *  without going through `CloudSettings::default()` itself.
 */
export type CloudSettings = {
	shared?: SharedSettings,
	desktop?: DesktopSettings,
	mobile?: MobileSettings,
	web?: WebSettings,
};

/**
 *  Desktop-only cloud-synced settings. Mobile and web each have their
 *  own platform sections to keep concepts that don't translate (window
 *  chrome scaling, telemetry SDKs that don't run on the other
 *  platforms) cleanly partitioned.
 * 
 *  The derived `Default` is both the fresh-install value and the
 *  per-field fallback used by `#[serde(default)]` when an older client
 *  wrote a partial blob. Scales default to [`DEFAULT_SCALE`] (via
 *  [`InterfaceScale::DEFAULT`] / [`TextScale::DEFAULT`]) rather than
 *  `0.0`, because a zero-size UI is unrecoverable; an inert sensible
 *  value is the only safe fallback. Telemetry consent defaults to the
 *  "never asked" sentinel (`consent_version == 0`) so a fresh install
 *  is routed through the consent prompt rather than silently
 *  auto-consented — see [`crate::TelemetryConsent`].
 * 
 *  `interface_scale` and `text_scale` carry their invariants in the
 *  type, not in a separate validation pass: any value of type
 *  [`InterfaceScale`] or [`TextScale`] is by construction finite and
 *  within `[MIN, MAX]`. Deserialization, `From<f32>`, and the
 *  `bon`-generated builder all route through the clamping
 *  constructor, so a corrupt cloud blob, a misbehaving client, or a
 *  hand-rolled patch via `extras` all collapse to safe values before
 *  they ever land in the struct.
 */
export type DesktopSettings = {
	/**
	 *  Multiplier applied to the document's root font-size, scaling every
	 *  rem-anchored design token (text, spacing, controls) together.
	 */
	interfaceScale?: InterfaceScale,
	/**
	 *  Additional multiplier layered on top of `interface_scale` that
	 *  affects only typography utilities, leaving spacing and control
	 *  sizes alone.
	 */
	textScale?: TextScale,
	/**
	 *  Desktop-scoped telemetry consent. Covers what the desktop
	 *  client collects (Sentry, PostHog) and nothing else; mobile and
	 *  web each carry their own record because consent must be
	 *  specific to the data actually collected.
	 */
	telemetry?: TelemetryConsent,
} & { [key in string]: unknown };

/**
 *  `GET /settings` — 200 body.
 * 
 *  The server treats the settings document as an opaque JSON blob and only
 *  owns the `schema_version` and `updated_at` metadata columns. Clients
 *  deserialize `settings` into the [`CloudSettings`](crate::CloudSettings)
 *  shape they understand; a blob written by a newer release of another
 *  client round-trips verbatim through older readers.
 * 
 *  A 404 from the server is *not* an error; it signals "no row for this
 *  user yet" and triggers a first-run upload on the client. That branch
 *  carries no body and is therefore not represented here.
 */
export type GetSettingsResponse = {
	schemaVersion: number,
	updatedAt: string,
	settings: unknown,
};

/**
 *  Interface-scale multiplier applied to the document's root font-size,
 *  scaling every rem-anchored design token (text, spacing, controls)
 *  together. Always finite and within
 *  `[InterfaceScale::MIN, InterfaceScale::MAX]` by construction.
 * 
 *  Bounds are chosen against window chrome: below `MIN` the layout
 *  drops below useful tap-target sizes on Linux / Windows; above `MAX`
 *  the fixed-size titlebar and traffic-light buttons start overlapping
 *  content.
 */
export type InterfaceScale = number | null;

/**
 *  Mobile-only cloud-synced settings. Empty in v1 — the section exists
 *  so the mobile client can ship fields onto it without disturbing
 *  desktop's wire shape.
 */
export type MobileSettings = { [key in string]: unknown };

/**
 *  `PUT /settings` — 200 body. The client stamps these onto its local
 *  cache so the next `base_updated_at` it sends matches the server.
 */
export type PutSettingsAcceptedResponse = {
	schemaVersion: number,
	updatedAt: string,
};

/**
 *  `PUT /settings` — 409 body. The server returns its current row so
 *  the client can reconcile in one round trip rather than re-fetching.
 */
export type PutSettingsConflictResponse = {
	schemaVersion: number,
	updatedAt: string,
	current: unknown,
};

/**
 *  `PUT /settings` — request body.
 * 
 *  `schema_version` rides at the top level so the server can index it
 *  without parsing the blob. `settings` is opaque JSON: the server does
 *  not interpret the document, so well-formedness is the client's
 *  concern. Field-level invariants (e.g. UI scale bounds) are carried
 *  by the field types themselves — see [`crate::DesktopSettings`] —
 *  so a serialized [`crate::CloudSettings`] is always within range.
 * 
 *  `base_updated_at` is the `updated_at` the client last observed on the
 *  server. `None` means "this is a first write; only succeed if no row
 *  exists." The server uses this for optimistic concurrency: a mismatch
 *  yields [`PutSettingsConflictResponse`].
 */
export type PutSettingsRequest = {
	schemaVersion: number,
	settings: unknown,
	baseUpdatedAt: string | null,
};

/**
 *  Cross-platform cloud-synced settings. Anything in this section
 *  applies identically on desktop, mobile, and web; per-platform
 *  concepts live in the platform sections of [`crate::CloudSettings`].
 * 
 *  Telemetry consent is deliberately *not* here: each platform ships
 *  a different telemetry stack and so collects different categories
 *  of data, which means consent has to be platform-specific (see
 *  [`crate::TelemetryConsent`]).
 * 
 *  `dynamic_accent` defaults to `true` — the design pulls the OS / wallpaper
 *  accent by default and a user who has never touched the toggle should see
 *  the dynamic behaviour. This is the one field where the product default
 *  differs from `bool::default()`, which is why this struct has a hand-rolled
 *  `Default` instead of `#[derive]`.
 */
export type SharedSettings = {
	theme?: ThemePreference,
	dynamicAccent?: boolean,
} & { [key in string]: unknown };

/**
 *  Per-platform telemetry consent record. Lives under each platform
 *  section of [`crate::CloudSettings`] — never under
 *  [`crate::SharedSettings`] — because consent must be specific to the
 *  data actually collected, and each platform ships a different
 *  telemetry stack (Sentry + PostHog on desktop, platform-native SDKs
 *  on mobile, etc.). A user agreeing on desktop has not seen, and
 *  cannot legally cover, what mobile or web will collect.
 * 
 *  `distinct_id` is intentionally absent — it is an anonymous
 *  per-install identifier whose rotation must break cross-device
 *  linkage, and so stays in the platform's local file rather than
 *  crossing the wire.
 * 
 *  ## `consent_version` semantics
 * 
 *  `consent_version` records the schema version of the consent prompt
 *  the user agreed to *on this platform*.
 * 
 *  - `0` (the `Default`) means the user has **never** seen the prompt.
 *  - Any value `>= DESKTOP_CONSENT_VERSION` (or the analogue for other
 *    platforms) means the user has consented to the current schema.
 *  - A value between `1` and `current - 1` means the user consented to
 *    an older prompt; the client must re-prompt.
 * 
 *  The value is **monotonically non-decreasing** by contract. The only
 *  writer is the platform's consent procedure, which uses
 *  [`Self::record_for_desktop`] (analogous methods for other platforms
 *  will land when those clients ship). Regular settings-page saves
 *  must *not* touch this field; the IPC layer enforces this by
 *  clamping incoming values against the stored version.
 */
export type TelemetryConsent = {
	consentVersion?: number,
	anonymousMetrics?: boolean,
	anonymousErrors?: boolean,
	nonAnonymousMetrics?: boolean,
} & { [key in string]: unknown };

/**
 *  Additional multiplier layered on top of [`InterfaceScale`] that
 *  affects only typography utilities, leaving spacing and control
 *  sizes alone. Always finite and within
 *  `[TextScale::MIN, TextScale::MAX]` by construction.
 * 
 *  Bounds currently mirror [`InterfaceScale`] but the type is separate
 *  so they can diverge — text legibility may eventually want a wider
 *  range than the chrome-anchored interface bounds allow, and the type
 *  system already enforces that the two fields can't be swapped at
 *  call sites.
 */
export type TextScale = number | null;

/**
 *  User's preferred colour scheme. `System` defers to the OS-level
 *  setting; `Light` / `Dark` pin it explicitly across devices.
 */
export type ThemePreference = "system" | "light" | "dark";

/**
 *  Web-only cloud-synced settings. Empty in v1 — the section exists
 *  so the web client can ship fields onto it without disturbing
 *  desktop's wire shape.
 */
export type WebSettings = { [key in string]: unknown };
