// This file has been generated by Specta. Do not edit this file manually.
export type AIMessage = {
	content: ContentBlocks;
	id?: string | null;
	name?: string | null;
	tool_calls?: ToolCall[];
	invalid_tool_calls?: InvalidToolCall[];
	usage_metadata?: UsageMetadata | null;
	additional_kwargs?: { [key in string]: unknown };
	response_metadata?: { [key in string]: unknown };
};

export type AIMessageChunk = {
	content: ContentBlocks;
	id?: string | null;
	name?: string | null;
	tool_calls?: ToolCall[];
	invalid_tool_calls?: InvalidToolCall[];
	tool_call_chunks: ToolCallChunk[];
	usage_metadata?: UsageMetadata | null;
	additional_kwargs?: { [key in string]: unknown };
	response_metadata?: { [key in string]: unknown };
	chunk_position?: ChunkPosition | null;
};

export type Annotation =
	| {
			type: 'citation';
			id?: string | null;
			url?: string | null;
			title?: string | null;
			start_index?: bigint | null;
			end_index?: bigint | null;
			cited_text?: string | null;
			extras?: { [key in string]: unknown } | null;
	  }
	| { type: 'non_standard_annotation'; id?: string | null; value: { [key in string]: unknown } };

/**
 *  Tagged union of every message variant. Wire format is internally tagged on
 *  the `type` field — `{"type": "human", "content": ..., ...}` etc. The inner
 *  per-variant structs (`HumanMessage`, `AIMessage`, ...) deliberately do NOT
 *  carry their own `type` field; the discriminant is added at the union level
 *  and only there. This keeps the Rust types and the specta-generated TS types
 *  in lockstep with the actual JSON shape.
 */
export type AnyMessage =
	| ({
			type: 'human';
	  } & HumanMessage)
	| ({
			type: 'system';
	  } & SystemMessage)
	| ({
			type: 'ai';
	  } & AIMessage)
	| ({
			type: 'tool';
	  } & ToolMessage)
	| ({
			type: 'chat';
	  } & ChatMessage)
	| ({
			type: 'remove';
	  } & RemoveMessage);

export type AudioContentBlock = {
	id?: string | null;
	file_id?: string | null;
	mime_type?: string | null;
	index?: BlockIndex | null;
	url?: string | null;
	base64?: string | null;
	extras?: { [key in string]: unknown } | null;
};

export type BlockIndex = number | string;

/**
 *  Frame sent by the client over the chat WebSocket.
 *
 *  Bidirectional from day one; the current set is `Send` (start a turn from
 *  a new human message), `Regenerate` (re-roll an existing AI response under
 *  the same human parent so it becomes a sibling variant), and `Cancel`
 *  (interrupt the in-flight turn). New variants can be added without breaking
 *  older clients because serde rejects unknown tagged variants only on
 *  deserialize, never on encode.
 */
export type ChatClientMessage =
	| ({
			type: 'send';
	  } & ChatSendRequest)
	| ({
			type: 'regenerate';
	  } & RegenerateRequest)
	| { type: 'cancel' };

export type ChatMessage = {
	content: ContentBlocks;
	role: string;
	id?: string | null;
	name?: string | null;
	additional_kwargs?: { [key in string]: unknown };
	response_metadata?: { [key in string]: unknown };
};

/**
 *  Payload of a [`ChatClientMessage::Send`] frame.
 *
 *  When `parent_message_id` is present the turn is interpreted as an edit of
 *  an existing branch; the service rewinds `active_leaf` accordingly.
 */
export type ChatSendRequest = {
	content_blocks: ContentBlock[];
	parent_message_id?: string | null;
	asset_chips_json?: string | null;
};

/**
 *  Frame sent by the server over the chat WebSocket.
 *
 *  Clients should accumulate `Chunk` payloads (using agent-chain's chunk-merge
 *  semantics) and replace placeholder state with the `Final.messages` payload
 *  when the turn ends.
 */
export type ChatServerMessage =
	/**  The user's message has been persisted; clients should display it. */
	| { type: 'confirmed_human_message'; message: MessageNode }
	/**  One streaming chunk from the AI. */
	| { type: 'chunk'; chunk: AIMessageChunk }
	/**
	 *  The turn ended successfully; tree positions for everything that was
	 *  persisted during this turn (human + AI + any tool messages).
	 */
	| { type: 'final'; messages: MessageNode[] }
	/**  The turn aborted with an error. The connection is closed after this. */
	| { type: 'error'; kind: string; message: string };

export type ChunkPosition = 'last';

export type ContentBlock =
	| ({
			type: 'text';
	  } & TextContentBlock)
	| ({
			type: 'invalid_tool_call';
	  } & InvalidToolCallBlock)
	| ({
			type: 'reasoning';
	  } & ReasoningContentBlock)
	| ({
			type: 'non_standard';
	  } & NonStandardContentBlock)
	| ({
			type: 'image';
	  } & ImageContentBlock)
	| ({
			type: 'video';
	  } & VideoContentBlock)
	| ({
			type: 'audio';
	  } & AudioContentBlock)
	| ({
			type: 'text-plain';
	  } & PlainTextContentBlock)
	| ({
			type: 'file';
	  } & FileContentBlock)
	| ({
			type: 'tool_call';
	  } & ToolCallBlock)
	| ({
			type: 'tool_call_chunk';
	  } & ToolCallChunkBlock)
	| ({
			type: 'server_tool_call';
	  } & ServerToolCall)
	| ({
			type: 'server_tool_call_chunk';
	  } & ServerToolCallChunk)
	| ({
			type: 'server_tool_result';
	  } & ServerToolResult);

export type ContentBlocks = ContentBlock[];

/**  Request body for `POST /threads`. */
export type CreateThreadRequest = {
	title?: string | null;
};

/**  Response body for `POST /threads`. */
export type CreateThreadResponse = {
	thread: Thread;
};

/**  Response body for `DELETE /threads/{thread_id}`. */
export type DeleteThreadResponse = Record<string, never>;

export type FileContentBlock = {
	id?: string | null;
	file_id?: string | null;
	mime_type?: string | null;
	index?: BlockIndex | null;
	url?: string | null;
	base64?: string | null;
	extras?: { [key in string]: unknown } | null;
};

/**
 *  Request body for `POST /threads/{thread_id}/title`.
 *
 *  The endpoint reads recent thread history server-side, so no payload is
 *  needed. An empty body type keeps the request well-typed for code-gen and
 *  leaves room to add fields later.
 */
export type GenerateThreadTitleRequest = Record<string, never>;

/**  Response body for `POST /threads/{thread_id}/title`. */
export type GenerateThreadTitleResponse = {
	thread: Thread;
};

/**  Query parameters for `GET /threads/{thread_id}/messages`. */
export type GetMessagesQuery = {
	limit?: number | null;
	offset?: number | null;
};

/**  Response body for endpoints that return the message tree. */
export type GetMessagesResponse = {
	messages: MessageNode[];
};

/**  Response body for `GET /threads/{thread_id}`. */
export type GetThreadResponse = {
	thread: Thread;
};

export type HumanMessage = {
	content: ContentBlocks;
	id?: string | null;
	name?: string | null;
	additional_kwargs?: { [key in string]: unknown };
	response_metadata?: { [key in string]: unknown };
};

export type ImageContentBlock = {
	id?: string | null;
	file_id?: string | null;
	mime_type?: string | null;
	index?: BlockIndex | null;
	url?: string | null;
	base64?: string | null;
	extras?: { [key in string]: unknown } | null;
};

export type InputTokenDetails = {
	audio?: bigint | null;
	cache_creation?: bigint | null;
	cache_read?: bigint | null;
} & { [key in string]: bigint };

export type InvalidToolCall = {
	name?: string | null;
	args?: string | null;
	id?: string | null;
	error?: string | null;
	type?: string | null;
};

export type InvalidToolCallBlock = {
	id?: string | null;
	name?: string | null;
	args?: string | null;
	error?: string | null;
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

/**  Query parameters for `GET /threads`. */
export type ListThreadsQuery = {
	limit?: number | null;
	offset?: number | null;
};

/**  Response body for `GET /threads`. */
export type ListThreadsResponse = {
	threads: Thread[];
};

/**  One node in the message tree returned by message-list endpoints. */
export type MessageNode = {
	parent_id?: string | null;
	message: AnyMessage;
	children?: MessageNode[];
	sibling_index: number;
	depth: number;
};

export type NonStandardContentBlock = {
	id?: string | null;
	value?: { [key in string]: unknown };
	index?: BlockIndex | null;
};

export type OutputTokenDetails = {
	audio?: bigint | null;
	reasoning?: bigint | null;
} & { [key in string]: bigint };

export type PlainTextContentBlock = {
	id?: string | null;
	file_id?: string | null;
	mime_type: string;
	index?: BlockIndex | null;
	url?: string | null;
	base64?: string | null;
	text?: string | null;
	title?: string | null;
	context?: string | null;
	extras?: { [key in string]: unknown } | null;
};

export type ReasoningContentBlock = {
	id?: string | null;
	reasoning?: string | null;
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

/**
 *  Payload of a [`ChatClientMessage::Regenerate`] frame.
 *
 *  The server resolves the AI message's parent (a human message), rewinds
 *  `active_leaf` to that parent, and runs the agent loop on the existing
 *  context. The newly produced AI message lands as a sibling of the original.
 */
export type RegenerateRequest = {
	ai_message_id: string;
};

export type RemoveMessage = {
	id: string;
	name?: string | null;
	additional_kwargs?: { [key in string]: unknown };
	response_metadata?: { [key in string]: unknown };
};

/**  One message hit returned by full-text search. */
export type SearchMessageResult = {
	id: string;
	thread_id: string;
	message_type: string;
	rank: number | null;
	created_at: string;
	snippet: string;
};

/**  Query parameters for `GET /threads/messages/search`. */
export type SearchMessagesQuery = {
	q: string;
	limit?: number | null;
	offset?: number | null;
};

/**  Response body for `GET /threads/messages/search`. */
export type SearchMessagesResponse = {
	results: SearchMessageResult[];
};

/**  One thread hit returned by full-text search. */
export type SearchThreadResult = {
	id: string;
	title: string;
	rank: number | null;
	updated_at: string;
};

/**  Query parameters for `GET /threads/search`. */
export type SearchThreadsQuery = {
	q: string;
	limit?: number | null;
	offset?: number | null;
};

/**  Response body for `GET /threads/search`. */
export type SearchThreadsResponse = {
	results: SearchThreadResult[];
};

export type ServerToolCall = {
	id: string;
	name: string;
	args?: { [key in string]: unknown };
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

export type ServerToolCallChunk = {
	name?: string | null;
	args?: string | null;
	id?: string | null;
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

export type ServerToolResult = {
	id?: string | null;
	tool_call_id: string;
	status: ServerToolStatus;
	output?: unknown | null;
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

export type ServerToolStatus = 'success' | 'error';

/**
 *  Request body for `POST /threads/{thread_id}/messages/switch-branch`.
 *
 *  `direction` is `-1`, `0`, or `1` — left sibling, no sibling change, right
 *  sibling — matching the gRPC contract this replaces.
 */
export type SwitchBranchRequest = {
	message_id: string;
	direction: number;
};

export type SystemMessage = {
	content: ContentBlocks;
	id?: string | null;
	name?: string | null;
	additional_kwargs?: { [key in string]: unknown };
	response_metadata?: { [key in string]: unknown };
};

export type TextContentBlock = {
	id?: string | null;
	text: string;
	annotations?: Annotation[] | null;
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

/**  A persisted thread row as returned to the client. */
export type Thread = {
	id: string;
	user_id: string;
	title: string;
	created_at: string;
	updated_at: string;
	active_leaf_id?: string | null;
};

/**
 *  JSON error body returned by the thread service on non-2xx responses.
 *
 *  Mirrors the shape used by [`activity-core`](https://docs.rs/activity-core)
 *  so the desktop client can decode failures uniformly across HTTP services.
 */
export type ThreadErrorResponse = {
	error: string;
	message: string;
	details?: string | null;
};

export type ToolCall = {
	id?: string | null;
	name: string;
	/**
	 *  Always a JSON object on the wire. The struct-side type stays
	 *  `serde_json::Value` for ergonomic constructor input, but the specta-
	 *  generated TS type is `Record<string, unknown>` to reflect that.
	 */
	args: { [key in string]: unknown };
	type?: string | null;
};

export type ToolCallBlock = {
	id?: string | null;
	name: string;
	args?: { [key in string]: unknown };
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

export type ToolCallChunk = {
	name?: string | null;
	args?: string | null;
	id?: string | null;
	index?: number | null;
	type?: string | null;
};

export type ToolCallChunkBlock = {
	id?: string | null;
	name?: string | null;
	args?: string | null;
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

export type ToolMessage = {
	content: ContentBlocks;
	tool_call_id: string;
	id?: string | null;
	name?: string | null;
	status?: ToolStatus;
	artifact?: unknown | null;
	additional_kwargs?: { [key in string]: unknown };
	response_metadata?: { [key in string]: unknown };
};

export type ToolStatus = 'success' | 'error';

export type UsageMetadata = {
	input_tokens: bigint;
	output_tokens: bigint;
	total_tokens: bigint;
	input_token_details?: InputTokenDetails | null;
	output_token_details?: OutputTokenDetails | null;
};

export type VideoContentBlock = {
	id?: string | null;
	file_id?: string | null;
	mime_type?: string | null;
	index?: BlockIndex | null;
	url?: string | null;
	base64?: string | null;
	extras?: { [key in string]: unknown } | null;
};
