// This file has been generated by Specta. Do not edit this file manually.
export type AIMessage = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	tool_calls?: ToolCall[],
	invalid_tool_calls?: InvalidToolCall[],
	usage_metadata?: UsageMetadata | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

export type AIMessageChunk = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	tool_calls?: ToolCall[],
	invalid_tool_calls?: InvalidToolCall[],
	tool_call_chunks: ToolCallChunk[],
	usage_metadata?: UsageMetadata | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
	chunk_position?: ChunkPosition | null,
};

export type Annotation = { type: "citation"; id?: string | null; url?: string | null; title?: string | null; start_index?: bigint | null; end_index?: bigint | null; cited_text?: string | null; extras?: { [key in string]: unknown } | null } | { type: "non_standard_annotation"; id?: string | null; value: { [key in string]: unknown } };

/**
 *  Tagged union of every message variant. Wire format is internally tagged on
 *  the `type` field — `{"type": "human", "content": ..., ...}` etc. The inner
 *  per-variant structs (`HumanMessage`, `AIMessage`, ...) deliberately do NOT
 *  carry their own `type` field; the discriminant is added at the union level
 *  and only there. This keeps the Rust types and the specta-generated TS types
 *  in lockstep with the actual JSON shape.
 */
export type AnyMessage = {
	type: "human",
} & HumanMessage | {
	type: "system",
} & SystemMessage | {
	type: "ai",
} & AIMessage | {
	type: "tool",
} & ToolMessage | {
	type: "chat",
} & ChatMessage | {
	type: "remove",
} & RemoveMessage;

export type AudioContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

export type BlockIndex = number | string;

/**
 *  Frame sent by the client over the chat WebSocket.
 * 
 *  Bidirectional from day one; the current set is `Send` (start a turn from
 *  a new human message), `Regenerate` (re-roll an existing AI response under
 *  the same human parent so it becomes a sibling variant), `Cancel`
 *  (interrupt the in-flight turn), and the tool-routing pair
 *  `CapabilityUpdate` + `ToolResponse`. New variants can be added without
 *  breaking older clients because serde rejects unknown tagged variants only
 *  on deserialize, never on encode.
 */
export type ChatClientMessage = {
	type: "send",
} & ChatSendRequest | {
	type: "regenerate",
} & RegenerateRequest | ({ type: "cancel" }) & { call_id?: never; contexts?: never; result?: never; tools?: never } | 
/**
 *  Declaration of the client's available tools and active contexts for
 *  the upcoming turn. Sent before every `Send`/`Regenerate` so the
 *  catalog reflects the freshest state of the user's session.
 */
({ type: "capability_update"; tools: WireToolDescriptor[]; contexts: WireActiveContext[] }) & { call_id?: never; result?: never } | 
/**
 *  Resolution of a previously-issued `ToolRequest`. The result uses
 *  serde's default `Result` repr (`{"Ok": ...}` / `{"Err": ...}`); the
 *  shape is pinned by tests in this module. See [`WireToolResult`] for
 *  why the specta override is needed.
 */
({ type: "tool_response"; call_id: number; result: WireToolResult }) & { contexts?: never; tools?: never };

export type ChatMessage = {
	content: ContentBlocks,
	role: string,
	id?: string | null,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

/**
 *  Payload of a [`ChatClientMessage::Send`] frame.
 * 
 *  When `parent_message_id` is present the turn is interpreted as an edit of
 *  an existing branch; the service rewinds `active_leaf` accordingly.
 * 
 *  `activity_id` captures the desktop client's currently-tracked activity
 *  when the user sent the message, so the server can record the link in
 *  `activity_threads`. Optional because non-desktop clients (web, mobile)
 *  have no timeline; absent values skip the link step entirely.
 */
export type ChatSendRequest = {
	content_blocks: ContentBlock[],
	parent_message_id?: string | null,
	asset_chips_json?: string | null,
	activity_id?: string | null,
};

/**
 *  Frame sent by the server over the chat WebSocket.
 * 
 *  Clients should accumulate `Chunk` payloads (using agent-chain's chunk-merge
 *  semantics) and replace placeholder state with the `Final.messages` payload
 *  when the turn ends. The tool-routing pair `ToolRequest` + `ToolCancel`
 *  drives remote-tool RPC over the same socket.
 */
export type ChatServerMessage = 
/**  The user's message has been persisted; clients should display it. */
{ type: "confirmed_human_message"; message: MessageNode } | 
/**  One streaming chunk from the AI. */
{ type: "chunk"; chunk: AIMessageChunk } | 
/**
 *  The turn ended successfully; tree positions for everything that was
 *  persisted during this turn (human + AI + any tool messages).
 */
{ type: "final"; messages: MessageNode[] } | 
/**  The turn aborted with an error. The connection is closed after this. */
{ type: "error"; kind: string; message: string } | 
/**
 *  Request the client to execute a tool on its side and return the
 *  result via [`ChatClientMessage::ToolResponse`] correlated by
 *  `call_id`.
 */
{ type: "tool_request"; call_id: number; descriptor: WireToolDescriptor; arguments: unknown } | 
/**
 *  Abort an in-flight `ToolRequest`. Sent when the user cancels the
 *  turn or the server's tool budget is exhausted before the client's
 *  response arrives.
 */
{ type: "tool_cancel"; call_id: number };

export type ChunkPosition = "last";

export type ContentBlock = {
	type: "text",
} & TextContentBlock | {
	type: "invalid_tool_call",
} & InvalidToolCallBlock | {
	type: "reasoning",
} & ReasoningContentBlock | {
	type: "non_standard",
} & NonStandardContentBlock | {
	type: "image",
} & ImageContentBlock | {
	type: "video",
} & VideoContentBlock | {
	type: "audio",
} & AudioContentBlock | {
	type: "text-plain",
} & PlainTextContentBlock | {
	type: "file",
} & FileContentBlock | {
	type: "tool_call",
} & ToolCallBlock | {
	type: "tool_call_chunk",
} & ToolCallChunkBlock | {
	type: "server_tool_call",
} & ServerToolCall | {
	type: "server_tool_call_chunk",
} & ServerToolCallChunk | {
	type: "server_tool_result",
} & ServerToolResult;

export type ContentBlocks = ContentBlock[];

/**  Request body for `POST /threads`. */
export type CreateThreadRequest = {
	title?: string | null,
};

/**  Response body for `POST /threads`. */
export type CreateThreadResponse = {
	thread: Thread,
};

/**  Response body for `DELETE /threads/{thread_id}`. */
export type DeleteThreadResponse = Record<string, never>;

export type FileContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

/**
 *  Request body for `POST /threads/{thread_id}/title`.
 * 
 *  The endpoint reads recent thread history server-side, so no payload is
 *  needed. An empty body type keeps the request well-typed for code-gen and
 *  leaves room to add fields later.
 */
export type GenerateThreadTitleRequest = Record<string, never>;

/**  Response body for `POST /threads/{thread_id}/title`. */
export type GenerateThreadTitleResponse = {
	thread: Thread,
};

/**  Query parameters for `GET /threads/{thread_id}/messages`. */
export type GetMessagesQuery = {
	limit?: number | null,
	offset?: number | null,
};

/**  Response body for endpoints that return the message tree. */
export type GetMessagesResponse = {
	messages: MessageNode[],
};

/**  Response body for `GET /threads/{thread_id}`. */
export type GetThreadResponse = {
	thread: Thread,
};

export type HumanMessage = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

export type ImageContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

export type InputTokenDetails = {
	audio?: bigint | null,
	cache_creation?: bigint | null,
	cache_read?: bigint | null,
} & { [key in string]: bigint };

export type InvalidToolCall = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	error?: string | null,
	type?: string | null,
};

export type InvalidToolCallBlock = {
	id?: string | null,
	name?: string | null,
	args?: string | null,
	error?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

/**  Query parameters for `GET /threads`. */
export type ListThreadsQuery = {
	limit?: number | null,
	offset?: number | null,
};

/**  Response body for `GET /threads`. */
export type ListThreadsResponse = {
	threads: Thread[],
};

/**  One node in the message tree returned by message-list endpoints. */
export type MessageNode = {
	parent_id?: string | null,
	message: AnyMessage,
	children?: MessageNode[],
	sibling_index: number,
	depth: number,
};

export type NonStandardContentBlock = {
	id?: string | null,
	value?: { [key in string]: unknown },
	index?: BlockIndex | null,
};

export type OutputTokenDetails = {
	audio?: bigint | null,
	reasoning?: bigint | null,
} & { [key in string]: bigint };

export type PlainTextContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type: string,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	text?: string | null,
	title?: string | null,
	context?: string | null,
	extras?: { [key in string]: unknown } | null,
};

export type ReasoningContentBlock = {
	id?: string | null,
	reasoning?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

/**
 *  Payload of a [`ChatClientMessage::Regenerate`] frame.
 * 
 *  The server resolves the AI message's parent (a human message), rewinds
 *  `active_leaf` to that parent, and runs the agent loop on the existing
 *  context. The newly produced AI message lands as a sibling of the original.
 */
export type RegenerateRequest = {
	ai_message_id: string,
};

export type RemoveMessage = {
	id: string,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

/**  One message hit returned by full-text search. */
export type SearchMessageResult = {
	id: string,
	thread_id: string,
	message_type: string,
	rank: number | null,
	created_at: string,
	snippet: string,
};

/**  Query parameters for `GET /threads/messages/search`. */
export type SearchMessagesQuery = {
	q: string,
	limit?: number | null,
	offset?: number | null,
};

/**  Response body for `GET /threads/messages/search`. */
export type SearchMessagesResponse = {
	results: SearchMessageResult[],
};

/**  One thread hit returned by full-text search. */
export type SearchThreadResult = {
	id: string,
	title: string,
	rank: number | null,
	updated_at: string,
};

/**  Query parameters for `GET /threads/search`. */
export type SearchThreadsQuery = {
	q: string,
	limit?: number | null,
	offset?: number | null,
};

/**  Response body for `GET /threads/search`. */
export type SearchThreadsResponse = {
	results: SearchThreadResult[],
};

export type ServerToolCall = {
	id: string,
	name: string,
	args?: { [key in string]: unknown },
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ServerToolCallChunk = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ServerToolResult = {
	id?: string | null,
	tool_call_id: string,
	status: ServerToolStatus,
	output?: unknown | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ServerToolStatus = "success" | "error";

/**
 *  Request body for `POST /threads/{thread_id}/messages/switch-branch`.
 * 
 *  `direction` is `-1`, `0`, or `1` — left sibling, no sibling change, right
 *  sibling — matching the gRPC contract this replaces.
 */
export type SwitchBranchRequest = {
	message_id: string,
	direction: number,
};

export type SystemMessage = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

export type TextContentBlock = {
	id?: string | null,
	text: string,
	annotations?: Annotation[] | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

/**  A persisted thread row as returned to the client. */
export type Thread = {
	id: string,
	user_id: string,
	title: string,
	created_at: string,
	updated_at: string,
	active_leaf_id?: string | null,
};

/**
 *  JSON error body returned by the thread service on non-2xx responses.
 * 
 *  Mirrors the shape used by [`activity-core`](https://docs.rs/activity-core)
 *  so the desktop client can decode failures uniformly across HTTP services.
 */
export type ThreadErrorResponse = {
	error: string,
	message: string,
	details?: string | null,
};

export type ToolCall = {
	id?: string | null,
	name: string,
	/**
	 *  Always a JSON object on the wire. The struct-side type stays
	 *  `serde_json::Value` for ergonomic constructor input, but the specta-
	 *  generated TS type is `Record<string, unknown>` to reflect that.
	 */
	args: { [key in string]: unknown },
	type?: string | null,
};

export type ToolCallBlock = {
	id?: string | null,
	name: string,
	args?: { [key in string]: unknown },
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ToolCallChunk = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	index?: number | null,
	type?: string | null,
};

export type ToolCallChunkBlock = {
	id?: string | null,
	name?: string | null,
	args?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ToolDefinition = {
	name: string,
	description: string,
	parameters: unknown,
};

/**
 *  Wire-side counterpart to `eurora_tools::ToolError`.
 * 
 *  The framework's `ToolError` carries non-serializable payloads
 *  (`serde_json::Error`, boxed `dyn Error`); converting to `ToolErrorWire`
 *  is lossy on purpose (the `Adapter` variant collapses to a single
 *  `message: String`) so the wire shape stays serde-friendly.
 */
export type ToolErrorWire = { kind: "context_unavailable"; tool: string; reason: string } | { kind: "origin_mismatch"; tool: string; expected: string; got: string } | { kind: "timeout" } | { kind: "cancelled" } | { kind: "transport"; message: string } | { kind: "remote"; code: number; message: string; details?: unknown | null } | { kind: "decode"; message: string } | { kind: "encode"; message: string } | { kind: "adapter"; message: string };

export type ToolMessage = {
	content: ContentBlocks,
	tool_call_id: string,
	id?: string | null,
	name?: string | null,
	status?: ToolStatus,
	artifact?: unknown | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

/**
 *  Where a tool runs. The server uses this to dispatch each call:
 *  `ServerLocal` tools execute in-process on the backend; everything else
 *  is routed back to the client over the chat WebSocket as a `ToolRequest`,
 *  and from there the client picks the right destination (bridge, native
 *  app, ACP session).
 * 
 *  `#[non_exhaustive]` so adding new sources later is non-breaking for
 *  downstream consumers that `match` on the enum.
 */
export type ToolSource = 
/**
 *  Routed via `euro-bridge` to a registered app of `app_kind` (in v1,
 *  `"browser"`).
 */
{ kind: "bridge"; app_kind: string } | 
/**  Runs in-process on the client (native Tauri tools). */
{ kind: "client_local" } | 
/**  Runs in-process on the backend (Firecrawl, describe-image). */
{ kind: "server_local" } | 
/**  Piped through an ACP session. */
{ kind: "acp" };

export type ToolStatus = "success" | "error";

export type UsageMetadata = {
	input_tokens: bigint,
	output_tokens: bigint,
	total_tokens: bigint,
	input_token_details?: InputTokenDetails | null,
	output_token_details?: OutputTokenDetails | null,
};

export type VideoContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

/**
 *  Wire-side projection of an active context, sent in `CapabilityUpdate`.
 * 
 *  Carries only the parts the server needs: the key (used to template the
 *  system message), the activation timestamp, and the opaque per-key data
 *  blob (surfaced to the LLM). Routing information — which window, which
 *  tab, which session — is intentionally absent: that's `Origin`, and it
 *  stays client-side.
 */
export type WireActiveContext = {
	/**  Stable namespaced key, e.g. `"youtube::watch_page"`. */
	key: string,
	/**  When the client activated this context. */
	activated_at: string,
	/**
	 *  Opaque per-key payload. Shape is determined by `key`; the server's
	 *  per-key formatter renders it into the system message.
	 */
	data: unknown,
};

/**
 *  Wire-side descriptor for a tool. One per call, one per entry in the
 *  per-turn `CapabilityUpdate.tools` list.
 * 
 *  `WireToolDescriptor` is a [`ToolDefinition`] (name, description,
 *  parameters schema) plus dispatch metadata (timeout, source, required
 *  contexts, approval flag) and the tool's output schema. The framework
 *  form (`eurora_tools::ToolDescriptor`) is the in-process
 *  `&'static`-everywhere shape; this is its serializable counterpart, owned
 *  and ready for transport. The server only ever sees this form.
 * 
 *  The `definition` field is flattened on the wire so the JSON shape stays
 *  flat (`{"name": ..., "description": ..., "parameters": ..., ...}`),
 *  while in Rust the typed relationship `WireToolDescriptor IS-A
 *  ToolDefinition + dispatch metadata` is explicit.
 */
export type WireToolDescriptor = {
	/**  JSON Schema for the tool's success payload. */
	output_schema: unknown,
	/**
	 *  Per-call timeout in milliseconds. Used by the server's bus to bound
	 *  in-flight remote calls; the framework's `ToolDescriptor.timeout`
	 *  converts to/from this field. `u32` ms (~49 days) is bounded well
	 *  above any sensible per-tool budget and keeps the wire shape inside
	 *  JS's safe integer range.
	 */
	timeout_ms: number,
	/**  Where the tool runs. The server uses this to pick a dispatch path. */
	source: ToolSource,
	/**
	 *  Context keys whose presence is required for this tool to be
	 *  surfaced to the LLM in a given turn (e.g.
	 *  `["youtube::watch_page"]`).
	 */
	required_contexts?: string[],
	/**
	 *  If true, the server must obtain explicit user approval before
	 *  dispatching the call. Not enforced in v1 (all v1 tools are
	 *  read-only) but declared so the protocol is stable.
	 */
	requires_user_approval?: boolean,
} & ToolDefinition;

/**
 *  Specta-only proxy for the `ToolResponse.result` field's TypeScript shape.
 * 
 *  Rust uses `Result<serde_json::Value, ToolErrorWire>` which serde encodes
 *  as `{"Ok": ...}` / `{"Err": ...}` (the externally-tagged default). The
 *  auto-generated `Result<T, E>` that `specta-typescript` emits for
 *  `std::result::Result` is `{ ok: T, err: E }` — both fields present, no
 *  discriminator — which doesn't match the wire. We override the field
 *  with this proxy so the TS binding renders as `{ Ok: unknown } |
 *  { Err: ToolErrorWire }`, matching what serde actually produces.
 * 
 *  Only the type information matters — specta never serializes or
 *  deserializes this; the original field handles all I/O.
 */
export type WireToolResult = ({ Ok: unknown }) & { Err?: never } | ({ Err: ToolErrorWire }) & { Ok?: never };
