[package]
name = "eur-vision"
version = "0.1.0"
edition = "2024"
authors = ["Eurora <eurora@company.com>"]
description = "Vision util for capturing screen, window and ocr'ing"

[dependencies]
tokio = { workspace = true }
image = { workspace = true }
rusty-tesseract = "1.1.10"
anyhow = { workspace = true }
xcap = { version = "0.6.2" }
wgpu = "25.0.2"
bytemuck = "1.23.1"
pollster = "0.4.0"
futures-intrusive = "0.5.0"
base64.workspace = true
eur-ocr = { path = "../../common/eur-ocr" }
tracing = { workspace = true }
