//! Eurora's browser native-messaging integration.
//!
//! Two responsibilities live here:
//!
//! - The `euro-native-messaging` binary (`src/main.rs`) speaks Chrome's
//!   native-messaging protocol on stdin/stdout (length-prefixed JSON)
//!   and bridges to the desktop app over a WebSocket. Browsers launch
//!   one copy of it per browser instance.
//! - The library surface re-exports the [`euro_bridge_protocol`] frame
//!   types alongside the browser-specific payload types
//!   ([`NativeMessage`] and friends) and exposes a [`type_collection`]
//!   used by the codegen binary to emit the TypeScript bindings the
//!   browser extension consumes.
//!
//! TypeScript bindings for the browser extension are generated by the
//! bundled codegen binary:
//!
//! ```text
//! cargo run -p euro-browser --features codegen \
//!     --bin euro-browser-codegen -- --generate_specta
//! ```

pub mod parent_pid;
pub mod types;
pub mod utils;

pub use euro_bridge_protocol::{
    BRIDGE_HOST, BRIDGE_PATH, BRIDGE_PORT, CancelFrame, ErrorFrame, EventFrame, Frame, FrameKind,
    RegisterFrame, RequestFrame, ResponseFrame, bridge_url,
};
pub use types::*;

/// Cap on the size of any single JSON frame exchanged with Chrome over
/// stdin/stdout. Chrome's native messaging max is 1 MiB; we allow more
/// here for SNAPSHOT/ASSETS payloads that include base64-encoded
/// images.
pub const MAX_FRAME_SIZE: usize = 16 * 1024 * 1024;

/// Build the [`specta::Types`] collection containing every type the
/// browser extension exchanges with the desktop bridge — both the
/// envelope types from [`euro_bridge_protocol`] (`Frame`, `FrameKind`,
/// `RegisterFrame`, …) and the native-messaging payload types defined
/// in this crate. Emitted as a single TypeScript `bindings.ts` consumed
/// by `apps/browser`.
pub fn type_collection() -> specta::Types {
    let mut types = euro_bridge_protocol::type_collection();
    types
        .register_mut::<NativeMessage>()
        .register_mut::<NativeImage>()
        .register_mut::<NativeArticleAsset>()
        .register_mut::<NativeArticleSnapshot>()
        .register_mut::<NativeMetadata>()
        .register_mut::<NativeYoutubeAsset>()
        .register_mut::<eurora_tools_youtube::TranscriptEntry>()
        .register_mut::<NativeYoutubeSnapshot>()
        .register_mut::<NativeTwitterAsset>()
        .register_mut::<NativeTwitterTweet>()
        .register_mut::<TweetPageData>()
        .register_mut::<ProfilePageData>()
        .register_mut::<TimelineData>()
        .register_mut::<SearchData>()
        .register_mut::<NotificationsData>()
        .register_mut::<UnsupportedPageData>()
        .register_mut::<ParseResult>();
    types
}

#[cfg(test)]
mod tests {
    use super::*;

    fn type_names(types: specta::Types) -> Vec<String> {
        types
            .into_unsorted_iter()
            .map(|ndt| ndt.name.to_string())
            .collect()
    }

    /// Both the bridge-protocol envelope and the browser-specific
    /// payloads must appear in the generated bindings so the extension
    /// can build frames and decode payloads from a single file.
    #[test]
    fn type_collection_includes_bridge_and_native_messaging_types() {
        let names = type_names(type_collection());

        for required in [
            // bridge-protocol envelope
            "Frame",
            "FrameKind",
            "RegisterFrame",
            "RequestFrame",
            "ResponseFrame",
            "EventFrame",
            "ErrorFrame",
            "CancelFrame",
            "ShutdownFrame",
            // native-messaging payloads
            "NativeMessage",
            "NativeImage",
            "NativeMetadata",
            "NativeArticleAsset",
            "NativeArticleSnapshot",
            "NativeYoutubeAsset",
            "TranscriptEntry",
            "NativeYoutubeSnapshot",
            "NativeTwitterAsset",
            "NativeTwitterTweet",
            "ParseResult",
        ] {
            assert!(
                names.iter().any(|n| n == required),
                "expected {required} in collection, got {names:?}",
            );
        }
    }
}
