// This file has been generated by Specta. Do not edit this file manually.
export type NativeArticleAsset = {
	title: string;
	url: string;
	content: string;
	text_content: string;
	site_name: string;
	selected_text: string | null;
	language: string;
	excerpt: string;
	length: number;
};

export type NativeArticleSnapshot = {
	highlighted_text: string | null;
};

export type NativeImage = {
	base64: string;
	mime_type: string;
};

export type NativeMetadata = {
	url: string | null;
	icon_base64: string | null;
	title: string | null;
};

export type NativeTwitterAsset = {
	url: string;
	title: string;
	result: ParseResult;
	timestamp: string;
};

export type NativeTwitterTweet = {
	text: string;
	timestamp: string | null;
	author: string | null;
	images?: NativeImage[];
};

export type NativeYoutubeAsset = {
	url: string;
	title: string;
	transcript: string;
	current_time: number;
};

export type NativeYoutubeSnapshot = {
	current_time: number;
	video_frame_base64: string;
	video_frame_width: number;
	video_frame_height: number;
};

export type NotificationsData = {
	tweets: NativeTwitterTweet[];
};

export type ParseResult =
	| { page: 'tweet'; data: TweetPageData }
	| { page: 'profile'; data: ProfilePageData }
	| { page: 'home'; data: TimelineData }
	| { page: 'search'; data: SearchData }
	| { page: 'notifications'; data: NotificationsData }
	| { page: 'unsupported'; data: UnsupportedPageData };

export type ProfilePageData = {
	username: string;
	tweets: NativeTwitterTweet[];
};

export type SearchData = {
	query: string;
	tweets: NativeTwitterTweet[];
};

export type TimelineData = {
	tweets: NativeTwitterTweet[];
};

export type TweetPageData = {
	tweet: NativeTwitterTweet | null;
	replies: NativeTwitterTweet[];
};

export type UnsupportedPageData = {
	url: string;
};
