// This file has been generated by Specta. Do not edit this file manually.
/**  Approximate accessibility tree returned by `get_accessibility_tree`. */
export type AccessibilityTree = {
	/**
	 *  Root of the emitted subtree (the element resolved from
	 *  `root_selector`, or `<body>` when none was given).
	 */
	root: AxNode,
	/**  Total number of nodes in the emitted tree, including `root`. */
	node_count: number,
	/**
	 *  `true` when traversal hit `max_depth` or `max_nodes` and one or
	 *  more subtrees were elided. The model can refine via `root_selector`
	 *  or raise `max_nodes` (within the 2 000 hard cap) to see more.
	 */
	truncated: boolean,
};

/**
 *  One node in the approximate accessibility tree. The structure mirrors
 *  the platform-computed AX tree CDP exposes, but the role and name are
 *  resolved client-side from ARIA attributes and implicit element roles.
 */
export type AxNode = {
	/**
	 *  Resolved ARIA role (`"button"`, `"link"`, `"textbox"`, …).
	 *  Falls back to `"generic"` when no implicit or explicit role applies.
	 */
	role: string,
	/**
	 *  Accessible name computed per the
	 *  [accname](https://w3c.github.io/accname/) spec — `aria-labelledby`,
	 *  then `aria-label`, then associated `<label>`, then `placeholder`,
	 *  then text content.
	 */
	name: string | null,
	/**
	 *  Current value for form controls (`<input>`, `<textarea>`,
	 *  `[role=textbox]`, `[role=slider]`, etc.).
	 */
	value: string | null,
	/**  Accessible description from `aria-describedby` or the `title` attr. */
	description: string | null,
	/**
	 *  CSS selector that re-targets this node for DOM-tool follow-ups
	 *  (`query_selector`, `insert_text`). Stable for the lifetime of the
	 *  observation; may break after page mutations.
	 */
	selector_path: string | null,
	/**  Children in document order. Empty for leaf nodes. */
	children: AxNode[],
};

/**  Bounding rectangle in CSS pixels — mirrors `DOMRect` semantics. */
export type BoundingBox = {
	/**  X coordinate of the left edge, relative to the viewport. */
	x: number | null,
	/**  Y coordinate of the top edge, relative to the viewport. */
	y: number | null,
	/**  Width in CSS pixels. */
	width: number | null,
	/**  Height in CSS pixels. */
	height: number | null,
};

/**
 *  Either side may send this to abort an in-flight request identified
 *  by `id`.
 */
export type CancelFrame = {
	id: number,
};

/**  A single captured frame from the active YouTube video. */
export type CapturedFrame = {
	/**  The YouTube video ID the frame was captured from. */
	video_id: string,
	/**  Playback position at which the frame was captured, in seconds. */
	current_time: number | null,
	/**  Decoded frame width in pixels. */
	width: number,
	/**  Decoded frame height in pixels. */
	height: number,
	/**  PNG bytes, base64-encoded (standard alphabet, padded). */
	image_base64: string,
};

/**  Current playback state of the active YouTube video. */
export type CurrentTimestamp = {
	/**  The YouTube video ID — the `v=` parameter from the watch URL. */
	video_id: string,
	/**  Playback position in seconds, possibly fractional. */
	current_time: number | null,
	/**  Total video length in seconds, possibly fractional. */
	duration: number | null,
	/**  `true` when the video is playing, `false` when paused. */
	playing: boolean,
};

/**
 *  One DOM match returned from `query_selector`. Fields beyond
 *  `selector_path` are populated only when the corresponding
 *  [`QuerySelectorInclude`] was passed.
 */
export type DomNode = {
	/**  CSS selector that re-targets this node for DOM-tool follow-ups. */
	selector_path: string,
	/**
	 *  `Element.textContent`, truncated to 8 KB. Present iff the caller
	 *  passed [`QuerySelectorInclude::Text`].
	 */
	text: string | null,
	/**
	 *  `Element.outerHTML`, truncated to 32 KB. Present iff the caller
	 *  passed [`QuerySelectorInclude::Html`].
	 */
	html: string | null,
	/**
	 *  Attribute map (`name` → `value`) of the element. Present iff the
	 *  caller passed [`QuerySelectorInclude::Attributes`].
	 */
	attributes: { [key in string]: string } | null,
	/**
	 *  Bounding client rect in CSS pixels. Present iff the caller passed
	 *  [`QuerySelectorInclude::Bounds`] and the element is laid out.
	 */
	bounds: BoundingBox | null,
};

/**  Failure response correlated with a [`RequestFrame`] by `id`. */
export type ErrorFrame = {
	id: number,
	code: number,
	message: string,
	details?: Payload | null,
};

/**
 *  Unsolicited notification pushed by a client (e.g. browser tab
 *  activation, Word selection change).
 */
export type EventFrame = {
	action: string,
	payload?: Payload | null,
};

/**
 *  One editable field discovered by `list_form_inputs`. Restricted by
 *  [`FormInputKind`] to the allowlist of safely-writable input types.
 */
export type FormInput = {
	/**
	 *  Selector-shaped identifier the model must pass back to
	 *  `insert_text`. Stable for the lifetime of the observation.
	 */
	field_id: string,
	/**
	 *  Accessible label resolved via `<label for>`, `aria-labelledby`,
	 *  `aria-label`, or `placeholder` (in that order).
	 */
	label: string | null,
	/**
	 *  One of the allowlisted editable kinds. The content-script never
	 *  emits a [`FormInput`] outside this set.
	 */
	kind: FormInputKind,
	/**  Current value at observation time. Empty string for empty fields. */
	value: string,
	/**  Placeholder text, when set on the underlying element. */
	placeholder: string | null,
	/**
	 *  `true` when the field is marked `required` (HTML constraint or
	 *  `aria-required="true"`).
	 */
	required: boolean,
};

/**
 *  Allowlist of editable input kinds the `insert_text` writer accepts.
 *  The content-script never returns any other kind, and `insert_text`
 *  rejects writes whose target falls outside this set.
 */
export type FormInputKind = 
/**  `<input type="text">`. */
"text" | 
/**  `<input type="search">`. */
"search" | 
/**  `<input type="email">`. */
"email" | 
/**  `<input type="url">`. */
"url" | 
/**  `<input type="tel">`. */
"tel" | 
/**  `<input type="number">`. */
"number" | 
/**  `<textarea>`. */
"textarea" | 
/**  `[contenteditable="true"]` on any element. */
"content_editable";

/**  Result of a `list_form_inputs` invocation. */
export type FormInputsList = {
	/**  Emitted text-typed editable fields (capped by `limit`). */
	inputs: FormInput[],
	/**
	 *  Total number of allowlisted, enabled, in-scope fields before
	 *  `limit` was applied. Password, file, hidden, submit, disabled,
	 *  and readonly fields are never counted.
	 */
	total: number,
};

/**
 *  Top-level envelope sent in both directions on the bridge. Every
 *  message is a `Frame`; the [`FrameKind`] discriminator identifies the
 *  payload variant.
 */
export type Frame = {
	kind: FrameKind,
};

/**
 *  Frame payload. Serialized as an externally-tagged JSON object —
 *  `{ "Request": { ... } }` — to match the shape the browser extension
 *  already consumes.
 */
export type FrameKind = ({ Request: RequestFrame }) & { Cancel?: never; Error?: never; Event?: never; Register?: never; Response?: never; Shutdown?: never } | ({ Response: ResponseFrame }) & { Cancel?: never; Error?: never; Event?: never; Register?: never; Request?: never; Shutdown?: never } | ({ Event: EventFrame }) & { Cancel?: never; Error?: never; Register?: never; Request?: never; Response?: never; Shutdown?: never } | ({ Error: ErrorFrame }) & { Cancel?: never; Event?: never; Register?: never; Request?: never; Response?: never; Shutdown?: never } | ({ Cancel: CancelFrame }) & { Error?: never; Event?: never; Register?: never; Request?: never; Response?: never; Shutdown?: never } | ({ Register: RegisterFrame }) & { Cancel?: never; Error?: never; Event?: never; Request?: never; Response?: never; Shutdown?: never } | ({ Shutdown: ShutdownFrame }) & { Cancel?: never; Error?: never; Event?: never; Register?: never; Request?: never; Response?: never };

/**
 *  Arguments to `get_accessibility_tree`. All fields are optional; the
 *  content-script applies the documented defaults when omitted.
 */
export type GetAccessibilityTreeArgs = {
	/**  CSS selector for the subtree root. Defaults to `<body>` when omitted. */
	root_selector: string | null,
	/**
	 *  Maximum traversal depth. Defaults to 12; deeper nodes are pruned and
	 *  [`AccessibilityTree::truncated`] is set.
	 */
	max_depth: number | null,
	/**
	 *  Soft cap on emitted nodes. Defaults to 500; hard cap is 2 000.
	 *  Reaching the cap sets [`AccessibilityTree::truncated`].
	 */
	max_nodes: number | null,
};

/**  Arguments to `insert_text`, the single mutating web tool. */
export type InsertTextArgs = {
	/**
	 *  Selector-shaped identifier previously returned by `list_form_inputs`.
	 *  `insert_text` rejects any `field_id` that doesn't resolve to exactly
	 *  one allowlisted, enabled, writable element.
	 */
	field_id: string,
	/**
	 *  Text to insert. Inserted as-is — no Unicode normalisation, no key
	 *  dispatch, no `Enter`-on-newline.
	 */
	text: string,
	/**
	 *  When `true`, overwrite the entire field value. When `false`
	 *  (default), append `text` to the existing value. Caret position
	 *  is not preserved either way.
	 */
	replace?: boolean,
};

/**  Result of a successful `insert_text` call. */
export type InsertTextResult = {
	/**  Echo of the [`InsertTextArgs::field_id`] that was written. */
	field_id: string,
	/**  Value of the field immediately before the write. */
	previous_value: string,
	/**  Value of the field immediately after the write. */
	new_value: string,
};

/**  One link, suitable for the model to suggest as a navigation target. */
export type Link = {
	/**  Resolved absolute URL of the link target. */
	url: string,
	/**  Accessible label of the link, when one can be resolved. */
	label: string | null,
	/**
	 *  ARIA role (`"link"` for `<a href>`, possibly `"button"` for
	 *  link-styled `<button>`s the content-script chose to include).
	 */
	role: string,
	/**  CSS selector that re-targets this element for DOM-tool follow-ups. */
	selector_path: string,
};

/**  Result of a `list_links` invocation. */
export type LinksList = {
	/**  Emitted links (capped by `limit`). */
	links: Link[],
	/**  Total number of in-scope links, before `limit` was applied. */
	total: number,
};

/**  Arguments to `list_form_inputs`. */
export type ListFormInputsArgs = {
	/**  CSS selector scoping the search. Defaults to the whole document. */
	root_selector: string | null,
	/**  Maximum inputs to return. Defaults to 100. */
	limit?: number,
};

/**  Arguments to `list_links`. */
export type ListLinksArgs = {
	/**  CSS selector scoping the search. Defaults to the whole document. */
	root_selector: string | null,
	/**  Maximum links to return. Defaults to 100. */
	limit?: number,
};

/**
 *  Envelope for every payload the browser native-messaging host
 *  exchanges with the desktop bridge. Externally tagged on `kind` with
 *  the inner payload under `data` so the JSON shape stays stable as
 *  new wire-payload variants are added.
 * 
 *  At present only [`NativeMetadata`] crosses the bridge — page content
 *  is delivered through granular adapter tools (`browser_web_*`,
 *  `browser_youtube_*`, …) rather than through pre-bundled assets or
 *  snapshots.
 */
export type NativeMessage = { kind: "NativeMetadata"; data: NativeMetadata };

export type NativeMetadata = {
	url: string | null,
	icon_base64: string | null,
	title: string | null,
};

/**  Page-level metadata exposed to the LLM for the active tab. */
export type PageMetadata = {
	/**  Fully-qualified URL of the active document, including query and fragment. */
	url: string,
	/**  `document.title` at observation time. */
	title: string,
	/**  Host component of `url` (no scheme, no port). */
	host: string,
	/**
	 *  BCP-47 language tag derived from `<html lang>` then
	 *  `<meta http-equiv="content-language">`. `None` when neither is set.
	 */
	language: string | null,
	/**  Document character set as reported by the browser, when known. */
	charset: string | null,
	/**  `<meta name="description">` content, when present. */
	description: string | null,
	/**
	 *  OpenGraph tags scraped from `<meta property="og:*">`, keyed by the
	 *  suffix after `og:` (e.g. `"title"`, `"image"`, `"site_name"`).
	 */
	og: { [key in string]: string },
	/**  Scroll and viewport metrics at observation time. */
	viewport: ViewportMetrics,
};

/**
 *  Inline JSON payload carried by Request/Response/Event frames.
 * 
 *  Stored as a [`Box<RawValue>`] so the payload's JSON serializes
 *  **inline** into the frame envelope rather than as a JSON-encoded
 *  string. Compared to the historical `Option<String>` shape, this:
 * 
 *  - halves the wire size for large payloads (e.g. base64-encoded
 *    PNGs) because the outer envelope no longer double-escapes the
 *    inner JSON;
 *  - drops one parse + one escape per direction (Rust producers hand
 *    raw JSON straight to serde; consumers read it without first
 *    decoding a string layer);
 *  - typed in Rust as JSON rather than "string of unknown structure",
 *    which means the encode/decode helpers can be centralised here
 *    and call sites stop manually `serde_json::to_string`-ing.
 * 
 *  Construct via [`Payload::from_value`] for typed Rust data, or
 *  [`Payload::from_raw_json`] when handing through a literal JSON
 *  fragment.
 */
export type Payload = unknown;

/**  Arguments to `query_selector`. */
export type QuerySelectorArgs = {
	/**  CSS selector evaluated against `document`. */
	selector: string,
	/**  Maximum matches to return. Defaults to 50. */
	limit?: number,
	/**
	 *  Per-match facets to populate. Empty `include` returns nodes that
	 *  carry only [`DomNode::selector_path`].
	 */
	include?: QuerySelectorInclude[],
};

/**
 *  Per-match facet the caller wants populated. Stringly-encoded as a
 *  `snake_case` discriminator on the wire so the LLM's input schema is
 *  a closed enum, not free-form text.
 */
export type QuerySelectorInclude = 
/**  Populate [`DomNode::text`] with `Element.textContent`. */
"text" | 
/**  Populate [`DomNode::html`] with `Element.outerHTML`. */
"html" | 
/**  Populate [`DomNode::attributes`] with the element's attribute map. */
"attributes" | 
/**  Populate [`DomNode::bounds`] with the element's bounding client rect. */
"bounds";

/**  Result of a `query_selector` invocation. */
export type QuerySelectorResult = {
	/**  Emitted matches (post-filter, capped by `limit`). */
	matches: DomNode[],
	/**
	 *  Total number of pre-filter matches, before the safety denylist
	 *  and `limit` were applied. When this exceeds `matches.len()`, some
	 *  elements were elided (hidden / password / file / submit / CSRF-
	 *  shaped metas) or truncated.
	 */
	total_match_count: number,
	/**
	 *  `true` when `total_match_count > matches.len()` for any reason
	 *  other than the safety denylist (i.e. the model can ask for more
	 *  with a higher `limit`).
	 */
	truncated: boolean,
};

/**  Mozilla Readability extraction of the page's primary article. */
export type ReadabilityArticle = {
	/**  Article title as Readability resolves it. */
	title: string | null,
	/**  Author byline, when Readability can identify one. */
	byline: string | null,
	/**  Publishing site name, typically from `<meta property="og:site_name">`. */
	site_name: string | null,
	/**  BCP-47 language tag for the article body, when known. */
	language: string | null,
	/**  Short excerpt suitable for surface previews. */
	excerpt: string | null,
	/**  Sanitised HTML body. Subject to a per-call 32 KB truncation cap. */
	content_html: string,
	/**  Plain-text body. Subject to a per-call 32 KB truncation cap. */
	text_content: string,
	/**  Character length of `text_content` before truncation. */
	length: number,
};

/**
 *  Mandatory first frame on every connection. Identifies the host
 *  process (the bridge) and the application process being represented.
 * 
 *  `app_pid` is the OS PID for clients that have one (browsers via the
 *  native-messaging host, the macOS launcher representing Safari).
 *  Sandboxed clients without access to a real PID — Office.js add-ins
 *  in particular — synthesize a stable per-session identifier and set
 *  `app_kind` to a logical name (e.g. `"microsoft-word"`) so the
 *  desktop can locate the client without relying on OS process lookup.
 */
export type RegisterFrame = {
	host_pid: number,
	app_pid: number,
	/**
	 *  Logical client identifier for non-PID-based integrations.
	 *  `None` for clients whose `app_pid` corresponds to a real OS
	 *  process discoverable via process-name lookup.
	 */
	app_kind?: string | null,
};

/**  Desktop-initiated request to a connected client. */
export type RequestFrame = {
	id: number,
	action: string,
	payload?: Payload | null,
};

/**  Client reply to a [`RequestFrame`], correlated by `id`. */
export type ResponseFrame = {
	id: number,
	action: string,
	payload?: Payload | null,
};

/**  Whatever the user has highlighted in the active document right now. */
export type SelectedText = {
	/**
	 *  Highlighted text as `window.getSelection().toString()` returns it.
	 *  Empty string when no selection is active.
	 */
	text: string,
	/**  XPath to the selection anchor node, when one is present. */
	anchor_xpath: string | null,
	/**  XPath to the selection focus node, when one is present. */
	focus_xpath: string | null,
};

/**
 *  Desktop-initiated request that the receiving client (currently:
 *  browser native-messaging hosts) terminate cleanly. Sent when the
 *  desktop has just installed an updated messenger binary on disk and
 *  wants stale connections to drop so the browser respawns from the new
 *  binary. The `reason` is informational only (logged by the recipient).
 */
export type ShutdownFrame = {
	reason?: string | null,
};

/**  Full transcript of a YouTube video. */
export type Transcript = {
	/**  The YouTube video ID the transcript belongs to. */
	video_id: string,
	/**  Caption language as a BCP-47 tag (`"en"`, `"en-US"`, `"de"`, …). */
	language: string,
	/**  Ordered cues; empty for videos with auto-captions disabled. */
	entries: TranscriptEntry[],
};

/**  One cue from a YouTube transcript. */
export type TranscriptEntry = {
	/**  Start time of the cue in seconds, relative to the video start. */
	start: number | null,
	/**  How long the cue is on screen, in seconds. */
	duration: number | null,
	/**  Cue text as YouTube serves it (HTML-escaped, single-language). */
	text: string,
};

/**  Scroll and viewport metrics for the active document. */
export type ViewportMetrics = {
	/**  `window.scrollX` in CSS pixels. */
	scroll_x: number | null,
	/**  `window.scrollY` in CSS pixels. */
	scroll_y: number | null,
	/**  `window.innerWidth` in CSS pixels. */
	inner_width: number | null,
	/**  `window.innerHeight` in CSS pixels. */
	inner_height: number | null,
	/**  `document.documentElement.scrollHeight` in CSS pixels. */
	document_height: number | null,
};
