// This file has been generated by Specta. Do not edit this file manually.
/**
 *  Either side may send this to abort an in-flight request identified
 *  by `id`.
 */
export type CancelFrame = {
	id: number,
};

/**  Failure response correlated with a [`RequestFrame`] by `id`. */
export type ErrorFrame = {
	id: number,
	code: number,
	message: string,
	details?: Payload | null,
};

/**
 *  Unsolicited notification pushed by a client (e.g. browser tab
 *  activation, Word selection change).
 */
export type EventFrame = {
	action: string,
	payload?: Payload | null,
};

/**
 *  Top-level envelope sent in both directions on the bridge. Every
 *  message is a `Frame`; the [`FrameKind`] discriminator identifies the
 *  payload variant.
 */
export type Frame = {
	kind: FrameKind,
};

/**
 *  Frame payload. Serialized as an externally-tagged JSON object —
 *  `{ "Request": { ... } }` — to match the shape the browser extension
 *  already consumes.
 */
export type FrameKind = ({ Request: RequestFrame }) & { Cancel?: never; Error?: never; Event?: never; Register?: never; Response?: never; Shutdown?: never } | ({ Response: ResponseFrame }) & { Cancel?: never; Error?: never; Event?: never; Register?: never; Request?: never; Shutdown?: never } | ({ Event: EventFrame }) & { Cancel?: never; Error?: never; Register?: never; Request?: never; Response?: never; Shutdown?: never } | ({ Error: ErrorFrame }) & { Cancel?: never; Event?: never; Register?: never; Request?: never; Response?: never; Shutdown?: never } | ({ Cancel: CancelFrame }) & { Error?: never; Event?: never; Register?: never; Request?: never; Response?: never; Shutdown?: never } | ({ Register: RegisterFrame }) & { Cancel?: never; Error?: never; Event?: never; Request?: never; Response?: never; Shutdown?: never } | ({ Shutdown: ShutdownFrame }) & { Cancel?: never; Error?: never; Event?: never; Register?: never; Request?: never; Response?: never };

/**
 *  Envelope for every payload the browser native-messaging host
 *  exchanges with the desktop bridge. Externally tagged on `kind` with
 *  the inner payload under `data` so the JSON shape stays stable as
 *  new wire-payload variants are added.
 * 
 *  At present only [`NativeMetadata`] crosses the bridge — page content
 *  is delivered through granular adapter tools (`browser_web_*`,
 *  `browser_youtube_*`, …) rather than through pre-bundled assets or
 *  snapshots.
 */
export type NativeMessage = { kind: "NativeMetadata"; data: NativeMetadata };

export type NativeMetadata = {
	/**
	 *  Browser-side tab id of the focused tab. `i32` rather than `i64`
	 *  because specta's TypeScript binding emits `number` (an `f64`) for
	 *  any integer and the safe-integer range is `±2^53 - 1` — `i64`
	 *  values can silently lose precision when round-tripping. Chrome
	 *  tab ids are well within `i32` range in practice.
	 * 
	 *  Required: the extension only sends metadata when it can identify
	 *  a concrete tab, so the desktop can rely on this for `LIST_TOOLS`
	 *  / `INVOKE_TOOL` / `CANCEL_TOOL` routing without a fallback path.
	 *  URL, title, and icon all come from the same tab record, so there
	 *  is no scenario where the desktop receives metadata without a tab
	 *  id.
	 */
	tab_id: number,
	url: string | null,
	icon_base64: string | null,
	title: string | null,
};

/**
 *  Inline JSON payload carried by Request/Response/Event frames.
 * 
 *  Stored as a [`Box<RawValue>`] so the payload's JSON serializes
 *  **inline** into the frame envelope rather than as a JSON-encoded
 *  string. Compared to the historical `Option<String>` shape, this:
 * 
 *  - halves the wire size for large payloads (e.g. base64-encoded
 *    PNGs) because the outer envelope no longer double-escapes the
 *    inner JSON;
 *  - drops one parse + one escape per direction (Rust producers hand
 *    raw JSON straight to serde; consumers read it without first
 *    decoding a string layer);
 *  - typed in Rust as JSON rather than "string of unknown structure",
 *    which means the encode/decode helpers can be centralised here
 *    and call sites stop manually `serde_json::to_string`-ing.
 * 
 *  Construct via [`Payload::from_value`] for typed Rust data, or
 *  [`Payload::from_raw_json`] when handing through a literal JSON
 *  fragment.
 */
export type Payload = unknown;

/**
 *  Mandatory first frame on every connection. Identifies the host
 *  process (the bridge) and the application process being represented.
 * 
 *  `app_pid` is the OS PID for clients that have one (browsers via the
 *  native-messaging host, the macOS launcher representing Safari).
 *  Sandboxed clients without access to a real PID — Office.js add-ins
 *  in particular — synthesize a stable per-session identifier and set
 *  `app_kind` to a logical name (e.g. `"microsoft-word"`) so the
 *  desktop can locate the client without relying on OS process lookup.
 */
export type RegisterFrame = {
	host_pid: number,
	app_pid: number,
	/**
	 *  Logical client identifier for non-PID-based integrations.
	 *  `None` for clients whose `app_pid` corresponds to a real OS
	 *  process discoverable via process-name lookup.
	 */
	app_kind?: string | null,
};

/**  Desktop-initiated request to a connected client. */
export type RequestFrame = {
	id: number,
	action: string,
	payload?: Payload | null,
};

/**  Client reply to a [`RequestFrame`], correlated by `id`. */
export type ResponseFrame = {
	id: number,
	action: string,
	payload?: Payload | null,
};

/**
 *  Desktop-initiated request that the receiving client (currently:
 *  browser native-messaging hosts) terminate cleanly. Sent when the
 *  desktop has just installed an updated messenger binary on disk and
 *  wants stale connections to drop so the browser respawns from the new
 *  binary. The `reason` is informational only (logged by the recipient).
 */
export type ShutdownFrame = {
	reason?: string | null,
};
