// This file has been generated by Specta. Do not edit this file manually.
/**
 *  Either side may send this to abort an in-flight request identified
 *  by `id`.
 */
export type CancelFrame = {
	id: number;
};

// Failure response correlated with a [`RequestFrame`] by `id`.
export type ErrorFrame = {
	id: number;
	code: number;
	message: string;
	details?: string | null;
};

/**
 *  Unsolicited notification pushed by a client (e.g. browser tab
 *  activation, Word selection change).
 */
export type EventFrame = {
	action: string;
	payload?: string | null;
};

/**
 *  Top-level envelope sent in both directions on the bridge. Every
 *  message is a `Frame`; the [`FrameKind`] discriminator identifies the
 *  payload variant.
 */
export type Frame = {
	kind: FrameKind;
};

/**
 *  Frame payload. Serialized as an externally-tagged JSON object —
 *  `{ "Request": { ... } }` — to match the shape the browser extension
 *  already consumes.
 */
export type FrameKind =
	| { Request: RequestFrame }
	| { Response: ResponseFrame }
	| { Event: EventFrame }
	| { Error: ErrorFrame }
	| { Cancel: CancelFrame }
	| { Register: RegisterFrame };

/**
 *  Mandatory first frame on every connection. Identifies the host
 *  process (the bridge) and the application process being represented
 *  (e.g. the Chrome PID).
 */
export type RegisterFrame = {
	host_pid: number;
	app_pid: number;
};

// Desktop-initiated request to a connected client.
export type RequestFrame = {
	id: number;
	action: string;
	payload?: string | null;
};

// Client reply to a [`RequestFrame`], correlated by `id`.
export type ResponseFrame = {
	id: number;
	action: string;
	payload?: string | null;
};
