// This file has been generated by Specta. Do not edit this file manually.
/**
 *  Either side may send this to abort an in-flight request identified
 *  by `id`.
 */
export type CancelFrame = {
	id: number;
};

// Failure response correlated with a [`RequestFrame`] by `id`.
export type ErrorFrame = {
	id: number;
	code: number;
	message: string;
	details?: string | null;
};

/**
 *  Unsolicited notification pushed by a client (e.g. browser tab
 *  activation, Word selection change).
 */
export type EventFrame = {
	action: string;
	payload?: string | null;
};

/**
 *  Top-level envelope sent in both directions on the bridge. Every
 *  message is a `Frame`; the [`FrameKind`] discriminator identifies the
 *  payload variant.
 */
export type Frame = {
	kind: FrameKind;
};

/**
 *  Frame payload. Serialized as an externally-tagged JSON object —
 *  `{ "Request": { ... } }` — to match the shape the browser extension
 *  already consumes.
 */
export type FrameKind =
	| { Request: RequestFrame }
	| { Response: ResponseFrame }
	| { Event: EventFrame }
	| { Error: ErrorFrame }
	| { Cancel: CancelFrame }
	| { Register: RegisterFrame };

/**
 *  Mandatory first frame on every connection. Identifies the host
 *  process (the bridge) and the application process being represented.
 *
 *  `app_pid` is the OS PID for clients that have one (browsers via the
 *  native-messaging host, the macOS launcher representing Safari).
 *  Sandboxed clients without access to a real PID — Office.js add-ins
 *  in particular — synthesize a stable per-session identifier and set
 *  `app_kind` to a logical name (e.g. `"microsoft-word"`) so the
 *  desktop can locate the client without relying on OS process lookup.
 */
export type RegisterFrame = {
	host_pid: number;
	app_pid: number;
	/**
	 *  Logical client identifier for non-PID-based integrations.
	 *  `None` for clients whose `app_pid` corresponds to a real OS
	 *  process discoverable via process-name lookup.
	 */
	app_kind?: string | null;
};

// Desktop-initiated request to a connected client.
export type RequestFrame = {
	id: number;
	action: string;
	payload?: string | null;
};

// Client reply to a [`RequestFrame`], correlated by `id`.
export type ResponseFrame = {
	id: number;
	action: string;
	payload?: string | null;
};
