
[workspace]
members = [
    "crates/app/eur-*",
    "crates/proto/eur-*",
    "crates/backend/eur-*",
    "crates/common/eur-*",
]
resolver = "2"

[workspace.dependencies]
syn          = "2.0"     # collapse 2.0.101, 1.0.109, 1.0.109(build)  
toml_edit    = "0.22"    # collapse 0.22, 0.20, 0.19  
regex-syntax = "0.8"     # collapse 0.8, 0.6  
rustix       = "0.38"    # collapse 0.38, 1.0, 0.38(build)  
indexmap     = "2.9"     # collapse 2.9, 1.9  
bstr = "1.11.1"
# Add the `tracing` or `tracing-detail` features to see more of gitoxide in the logs. Useful to see which programs it invokes.
insta = "1.41.1"
uuid = { version = "1.16.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"],  default-features = false}
thiserror = "2.0.9"
tokio = { version = "1.44.2", default-features = false  }
keyring = { version = "3.6.2", features = [
    "apple-native",
    "windows-native",
    "linux-native",
    "crypto-rust",
], default-features = false}
anyhow = "1.0.97"
parking_lot = "0.12.3"
futures = { version = "0.3.31" }
toml = "0.8.13"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tempfile = "3.19"
rand = "0.9.0"
chrono = { version = "0.4.40", features = ["serde"] }
tonic = "0.13.0"
prost = "0.13.5"
prost-types = "0.13.5"
http-body = "1.0.1"
http-body-util = "0.1.3"
tonic-build = "0.13.0"
dirs = "6.0"
log = "0.4"
once_cell = "1.21"
tokio-stream = "0.1"
serde_json = "1.0"
image = {version = "0.25.6", features = ["jpeg", "png"], default-features = false }
base64 = "0.22.1"
sentry = { version = "0.37.0"}

eur-secret = {path = "crates/app/eur-secret"}
eur-user = {path = "crates/common/eur-user"}

# eur-tauri = { path = "crates/eur-tauri" }

# gitbutler-id = { path = "crates/gitbutler-id" }
# gitbutler-git = { path = "crates/gitbutler-git" }
# gitbutler-watcher = { path = "crates/gitbutler-watcher" }
# gitbutler-testsupport = { path = "crates/gitbutler-testsupport" }
# gitbutler-cli = { path = "crates/gitbutler-cli" }
# gitbutler-branch-actions = { path = "crates/gitbutler-branch-actions" }
# gitbutler-sync = { path = "crates/gitbutler-sync" }
# gitbutler-oplog = { path = "crates/gitbutler-oplog" }
# gitbutler-repo = { path = "crates/gitbutler-repo" }
# gitbutler-repo-actions = { path = "crates/gitbutler-repo-actions" }
# gitbutler-command-context = { path = "crates/gitbutler-command-context" }
# gitbutler-feedback = { path = "crates/gitbutler-feedback" }
# gitbutler-config = { path = "crates/gitbutler-config" }
# gitbutler-project = { path = "crates/gitbutler-project" }
# gitbutler-user = { path = "crates/gitbutler-user" }
# gitbutler-branch = { path = "crates/gitbutler-branch" }
# gitbutler-reference = { path = "crates/gitbutler-reference" }
# gitbutler-error = { path = "crates/gitbutler-error" }
# gitbutler-serde = { path = "crates/gitbutler-serde" }
# gitbutler-secret = { path = "crates/gitbutler-secret" }
# gitbutler-storage = { path = "crates/gitbutler-storage" }
# gitbutler-fs = { path = "crates/gitbutler-fs" }
# gitbutler-time = { path = "crates/gitbutler-time" }
# gitbutler-commit = { path = "crates/gitbutler-commit" }
# gitbutler-tagged-string = { path = "crates/gitbutler-tagged-string" }
# gitbutler-url = { path = "crates/gitbutler-url" }
# gitbutler-diff = { path = "crates/gitbutler-diff" }
# gitbutler-operating-modes = { path = "crates/gitbutler-operating-modes" }
# gitbutler-edit-mode = { path = "crates/gitbutler-edit-mode" }
# gitbutler-cherry-pick = { path = "crates/gitbutler-cherry-pick" }
# gitbutler-oxidize = { path = "crates/gitbutler-oxidize" }
# gitbutler-stack = { path = "crates/gitbutler-stack" }
# gitbutler-forge = { path = "crates/gitbutler-forge" }
# gitbutler-hunk-dependency = { path = "crates/gitbutler-hunk-dependency" }
# but-settings = { path = "crates/but-settings" }
# gitbutler-workspace = { path = "crates/gitbutler-workspace" }
# but-testsupport = { path = "crates/but-testsupport" }
# but-rebase = { path = "crates/but-rebase" }
# but-core = { path = "crates/but-core" }
# but-workspace = { path = "crates/but-workspace" }
# but-hunk-dependency = { path = "crates/but-hunk-dependency" }

[profile.release]
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true        # Enables link to optimizations
opt-level = "s"   # Optimize for binary size
debug = true      # Enable debug symbols, for profiling

[profile.bench]
codegen-units = 256
lto = false
opt-level = 3

[profile.dev]
incremental        = true
codegen-units      = 256
overflow-checks    = false

