packages:
    - 'apps/*'
    - 'apps/extension/*'
    - 'apps/extension/content-scripts/*'
    - 'apps/extension/chromium/*'
    - 'apps/extension/firefox/*'
    - 'packages/*'
    - 'packages/website-modules/youtube/*'
    - 'packages/custom-components/*'
    - 'packages/prosemirror/*'
    - 'crates/*'
    - 'backend/*'

catalog:
    'vite': '6.3.5'
    'vitest': '3.2.4'
    '@vitest/ui': '3.2.4'
    'tailwindcss': '^4.1.11'
    '@tailwindcss/postcss': '^4.1.11'
    'postcss': '^8.5.6'
catalogs:
    svelte:
        'svelte': '5.36.0'
        '@sveltejs/kit': '2.23.0'
        'svelte-check': '4.2.2'
        '@sveltejs/vite-plugin-svelte': '5.1.1'
        '@sveltejs/adapter-static': '3.0.8'
        '@sentry/sveltekit': '8.55.0'
    redux:
        '@reduxjs/toolkit': '^2.5.0'
