packages:
    - apps/*
    - packages/*
    - packages/prosemirror/*
    - crates/*
    - backend/*
    - e2e

catalog:
    '@tailwindcss/postcss': ^4.1.18
    '@vitest/ui': 3.2.4
    '@lucide/svelte': ^0.563.1
    postcss: ^8.5.6
    tailwindcss: ^4.1.18
    vite: 6.4.1
    vitest: 3.2.4

catalogs:
    redux:
        '@reduxjs/toolkit': ^2.5.0
    svelte:
        '@sentry/sveltekit': 8.55.0
        '@sveltejs/adapter-static': 3.0.10
        '@sveltejs/kit': 2.50.2
        '@sveltejs/vite-plugin-svelte': 5.1.1
        svelte: 5.51.5
        svelte-check: 4.3.6
