packages:
    - 'apps/*'
    - 'apps/extension/*'
    - 'apps/extension/content-scripts/*'
    - 'packages/*'
    - 'packages/website-modules/youtube/*'
    - 'packages/custom-components/*'
    - 'packages/prosemirror/*'
    - 'crates/*'
    - 'backend/*'

catalog:
    'vite': '6.3.4'
    'vitest': '3.0.5'
    '@vitest/ui': '3.0.9'
catalogs:
    svelte:
        'svelte': '5.28.2'
        '@sveltejs/kit': '2.20.8'
        'svelte-check': '4.1.6'
        '@sveltejs/vite-plugin-svelte': '5.0.3'
        '@sveltejs/adapter-static': '3.0.8'
        '@sentry/sveltekit': '8.55.0'
    redux:
        '@reduxjs/toolkit': '^2.5.0'
