

[package]
name = "eur-remote-db"
version = "0.0.0"
edition = "2024"
authors = ["Eurora <eurora@company.com>"]
description = "Eurora Remote DB"

[dependencies]
anyhow = { workspace = true }
sqlx = { version = "0.8.6", features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
    "ipnet",
] }
futures = { workspace = true, features = ["std"] }
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4", "serde"] }
tracing = { workspace = true }
zerocopy = { version = "0.8.26" }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
tokio = { workspace = true, features = ["full", "tracing"] }
ipnet = { version = "2", features = ["serde"] }
