//! Server-side bus abstraction for remote tool calls.
//!
//! [`RemoteToolBus`] is the surface the agent loop uses to invoke a tool
//! whose `ToolSource` doesn't run in-process. The chat-WebSocket-backed
//! implementation lives in `be-thread-service::remote_tool_bus`; tests use
//! in-process stubs.
//!
//! [`IncomingCall`] is the client-side counterpart — what the dispatcher
//! receives once a `ToolRequest` has been correlated with a frozen
//! [`crate::Origin`] from the turn snapshot.

use serde_json::Value;
use thread_core::WireToolDescriptor;
use tokio_util::sync::CancellationToken;

use crate::error::ToolError;
use crate::origin::Origin;

/// Server-side bus that ferries a tool call from the agent loop to the
/// remote executor and waits for the result.
///
/// Two trait shapes are exposed, both with the same method signature:
/// - [`RemoteToolBus`] is the production trait, generated by
///   `trait_variant::make`. Its `call` future carries a `Send` bound, so
///   it can be awaited on tokio's multi-threaded runtime. Implementers
///   should write `impl RemoteToolBus for …`.
/// - [`RemoteToolBusLocal`] is the source trait — the same method without
///   the `Send` future bound, for `!Send` impls in single-threaded test
///   harnesses. A blanket impl provides it automatically for every
///   `RemoteToolBus` implementer, so the Send-bound variant satisfies
///   either bound.
///
/// Implementations must be `Sync` (the agent loop shares them behind
/// `Arc`). `RemoteToolBus` additionally requires the impl to be `Send`.
#[trait_variant::make(RemoteToolBus: Send)]
pub trait RemoteToolBusLocal: Sync {
    /// Invoke a remote tool and await the structured result.
    ///
    /// The implementation is responsible for:
    /// - Allocating a `call_id`.
    /// - Sending a `ChatServerMessage::ToolRequest` (or equivalent).
    /// - Awaiting the matching `ChatClientMessage::ToolResponse`.
    /// - Enforcing the descriptor's `timeout_ms` budget and the chat-level
    ///   cancellation token, surfacing `ToolError::Timeout` /
    ///   `ToolError::Cancelled` respectively.
    async fn call(
        &self,
        descriptor: &WireToolDescriptor,
        arguments: Value,
    ) -> Result<Value, ToolError>;
}

/// Per-call context handed to a [`crate::Dispatcher`] on the client side.
///
/// The dispatcher matches `descriptor_name` to one of its declared tools,
/// validates that `origin` is the variant the method expects, decodes
/// `arguments`, then invokes the user-written adapter implementation. The
/// `cancel` token is a child of the chat-level turn cancellation so the
/// dispatcher can race the adapter against turn termination.
#[derive(Debug)]
pub struct IncomingCall {
    /// The wire-side correlation id, plumbed through so adapters can
    /// reference it in logs.
    pub call_id: u32,
    /// Static descriptor name — the dispatcher's `match` arms are
    /// string-literal patterns, so the static lifetime lets the compiler
    /// elide a runtime equality check on each arm.
    pub descriptor_name: &'static str,
    /// Decoded JSON arguments. The dispatcher decodes this into the
    /// method's declared input type before calling the adapter.
    pub arguments: Value,
    /// The frozen routing target captured at turn start. Dispatchers must
    /// verify the variant matches the adapter method's declared target
    /// type and return [`ToolError::OriginMismatch`] otherwise.
    pub origin: Origin,
    /// Child cancellation token rooted at the turn's cancel token.
    pub cancel: CancellationToken,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::origin::BrowserOrigin;
    use serde_json::json;

    struct EchoBus;

    // Impl the Send variant; trait_variant's blanket impl gives us the
    // non-Send `LocalRemoteToolBus` for free.
    impl RemoteToolBus for EchoBus {
        async fn call(
            &self,
            descriptor: &WireToolDescriptor,
            arguments: Value,
        ) -> Result<Value, ToolError> {
            // Trivial echo for the test: the result mirrors the call so we
            // can verify both arguments survive the trait dispatch.
            Ok(json!({
                "echoed_for": descriptor.name,
                "arguments": arguments,
            }))
        }
    }

    fn sample_descriptor() -> WireToolDescriptor {
        WireToolDescriptor {
            name: "browser::test::echo".into(),
            description: "x".into(),
            input_schema: json!({}),
            output_schema: json!({}),
            timeout_ms: 1_000,
            source: thread_core::ToolSource::Bridge {
                app_kind: "browser".into(),
            },
            required_contexts: vec![],
            requires_user_approval: false,
        }
    }

    /// The blanket impl from `trait_variant::make` exposes
    /// `RemoteToolBusLocal` automatically — this test exercises the
    /// non-Send-bound path that's convenient in single-threaded testing.
    #[tokio::test(flavor = "current_thread")]
    async fn local_variant_reachable_via_blanket_impl() {
        let bus = EchoBus;
        let descriptor = sample_descriptor();
        let result = RemoteToolBusLocal::call(&bus, &descriptor, json!({"hello": "world"}))
            .await
            .expect("echo bus never errors");
        assert_eq!(result["echoed_for"], "browser::test::echo");
        assert_eq!(result["arguments"], json!({"hello": "world"}));
    }

    /// The Send variant is what production code uses; impl-of-Send-variant
    /// is what callers should write, so verify the direct call works.
    #[tokio::test]
    async fn send_variant_round_trips() {
        async fn run<B: RemoteToolBus>(bus: B) -> Value {
            let descriptor = sample_descriptor();
            bus.call(&descriptor, json!(null)).await.unwrap()
        }
        let result = run(EchoBus).await;
        assert_eq!(result["echoed_for"], "browser::test::echo");
    }

    #[test]
    fn incoming_call_fields_are_accessible() {
        let call = IncomingCall {
            call_id: 42,
            descriptor_name: "browser::test::echo",
            arguments: json!({"x": 1}),
            origin: Origin::Browser(BrowserOrigin {
                process_id: 1,
                tab_id: 2,
                window_id: None,
                page_url: "https://example.test".into(),
            }),
            cancel: CancellationToken::new(),
        };
        assert_eq!(call.call_id, 42);
        assert_eq!(call.descriptor_name, "browser::test::echo");
        assert_eq!(call.arguments, json!({"x": 1}));
        assert_eq!(call.origin.variant_name(), "Browser");
        assert!(!call.cancel.is_cancelled());
    }
}
