//! [`Dispatcher`] trait and the [`Catalog`] of registered dispatchers.
//!
//! The catalog is the client-side index from a wire-side descriptor name
//! to the dispatcher that knows how to execute it. Each [`Dispatcher`]
//! covers one or more tools (usually one adapter trait's worth) and owns
//! the dispatch logic — `match descriptor_name`, decode arguments, check
//! [`crate::Origin`] variant, call the user-written adapter
//! implementation, encode the result.

use std::sync::Arc;

use dashmap::DashMap;
use futures::future::BoxFuture;
use serde_json::Value;

use crate::bus::IncomingCall;
use crate::descriptor::ToolDescriptor;
use crate::error::ToolError;

/// One dispatcher per adapter implementation. Typically generated by the
/// `#[adapter]` macro in `eurora-tools-macros` (Phase 3).
///
/// Returning `BoxFuture` (instead of using native `async fn`) is the
/// deliberate cost we pay for `dyn Dispatcher` storage in [`Catalog`]:
/// async fn in trait isn't reliably object-safe yet, and the per-call
/// `Box` allocation is negligible compared to the JSON encode/decode +
/// the bridge round-trip the call performs.
pub trait Dispatcher: Send + Sync {
    /// All tools this dispatcher serves. The slice is `&'static` because
    /// the macro emits a `static`/`const` table; per-dispatcher state
    /// (the inner adapter impl) is held elsewhere on `self`.
    fn descriptors(&self) -> &'static [ToolDescriptor];

    /// Translate a wire-side descriptor name (`&str` borrowed from a
    /// `WireToolDescriptor.name`) to the `&'static str` the dispatcher's
    /// internal match arms use.
    ///
    /// The default impl is a linear scan over `descriptors()`. Adapters
    /// with many tools can override with a faster lookup; the default is
    /// fine for v1's small catalog.
    fn descriptor_name_for(&self, name: &str) -> Option<&'static str> {
        self.descriptors()
            .iter()
            .find(|d| d.name == name)
            .map(|d| d.name)
    }

    /// Execute one tool call.
    ///
    /// The dispatcher is responsible for:
    /// 1. Matching `call.descriptor_name` against its declared tools.
    /// 2. Verifying `call.origin` is the variant the matched method
    ///    expects ([`ToolError::OriginMismatch`] otherwise).
    /// 3. Decoding `call.arguments` into the method's input type
    ///    ([`ToolError::Decode`] on failure).
    /// 4. Awaiting the adapter method, racing it against `call.cancel`.
    /// 5. Encoding the return value back to [`serde_json::Value`]
    ///    ([`ToolError::Encode`] on failure).
    fn dispatch(&self, call: IncomingCall) -> BoxFuture<'_, Result<Value, ToolError>>;
}

/// Client-side registry mapping descriptor name → dispatcher.
///
/// One [`Catalog`] is built at app startup and shared via
/// `app.manage(Arc::new(catalog))`. Each dispatcher is registered once
/// and shows up under all of its declared descriptor names.
///
/// `Catalog::register` panics on duplicate descriptor names — duplicates
/// are programmer errors, not runtime conditions, and crashing at startup
/// is preferable to silently routing calls to the wrong dispatcher. Not
/// safe under concurrent `register` calls; build the catalog fully before
/// sharing the `Arc<Catalog>`.
#[derive(Default)]
pub struct Catalog {
    by_name: DashMap<&'static str, Entry>,
}

/// Joint storage of a dispatcher and the descriptor it serves under one
/// name. Keeping the descriptor pre-resolved makes `all_descriptors`
/// O(N) instead of scanning the dispatcher's slice on every iteration.
struct Entry {
    dispatcher: Arc<dyn Dispatcher>,
    descriptor: ToolDescriptor,
}

impl Catalog {
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a dispatcher. Panics if any of its declared descriptor
    /// names is already in the catalog.
    ///
    /// The check is performed in a separate pass before insertion so a
    /// duplicate leaves the catalog completely unchanged — there's no
    /// partial-registration state to clean up.
    pub fn register(&self, dispatcher: Arc<dyn Dispatcher>) {
        let descriptors = dispatcher.descriptors();
        for desc in descriptors {
            if self.by_name.contains_key(desc.name) {
                panic!(
                    "eurora-tools Catalog::register: duplicate descriptor name `{}`",
                    desc.name
                );
            }
        }
        for desc in descriptors {
            self.by_name.insert(
                desc.name,
                Entry {
                    dispatcher: dispatcher.clone(),
                    descriptor: desc.clone(),
                },
            );
        }
    }

    /// Look up the dispatcher that serves `name` (the wire-side
    /// descriptor name). Returns `None` if no dispatcher is registered.
    pub fn dispatcher_for(&self, name: &str) -> Option<Arc<dyn Dispatcher>> {
        self.by_name.get(name).map(|e| e.value().dispatcher.clone())
    }

    /// All descriptors known to the catalog, in unspecified order.
    ///
    /// Used by the per-turn `descriptors_for` filter that builds the
    /// LLM-visible capability list. The order doesn't matter (the LLM
    /// binding stage doesn't care), so we don't pay to maintain one.
    pub fn all_descriptors(&self) -> Vec<ToolDescriptor> {
        self.by_name
            .iter()
            .map(|e| e.value().descriptor.clone())
            .collect()
    }

    /// Number of distinct descriptor names registered.
    pub fn len(&self) -> usize {
        self.by_name.len()
    }

    /// `true` iff no descriptors are registered.
    pub fn is_empty(&self) -> bool {
        self.by_name.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::origin::{BrowserOrigin, Origin};
    use crate::schema::schema_of;
    use schemars::JsonSchema;
    use serde::{Deserialize, Serialize};
    use serde_json::json;
    use std::time::Duration;
    use thread_core::ToolSource;
    use tokio_util::sync::CancellationToken;

    #[derive(Serialize, Deserialize, JsonSchema)]
    struct Empty {}

    /// Dispatcher with two declared tools. Returns the descriptor name in
    /// the result so we can verify the right method was reached.
    struct StubDispatcher;

    impl StubDispatcher {
        const DESCRIPTORS: &'static [ToolDescriptor] = &[
            ToolDescriptor {
                name: "stub::tool::a",
                description: "A.",
                input_schema: schema_of::<Empty>,
                output_schema: schema_of::<Empty>,
                timeout: Duration::from_millis(100),
                source: ToolSource::ClientLocal,
                required_contexts: &[],
                requires_user_approval: false,
            },
            ToolDescriptor {
                name: "stub::tool::b",
                description: "B.",
                input_schema: schema_of::<Empty>,
                output_schema: schema_of::<Empty>,
                timeout: Duration::from_millis(100),
                source: ToolSource::ClientLocal,
                required_contexts: &[],
                requires_user_approval: false,
            },
        ];
    }

    impl Dispatcher for StubDispatcher {
        fn descriptors(&self) -> &'static [ToolDescriptor] {
            Self::DESCRIPTORS
        }

        fn dispatch(&self, call: IncomingCall) -> BoxFuture<'_, Result<Value, ToolError>> {
            Box::pin(async move { Ok(json!({ "tool": call.descriptor_name })) })
        }
    }

    struct OtherDispatcher;

    impl OtherDispatcher {
        const DESCRIPTORS: &'static [ToolDescriptor] = &[ToolDescriptor {
            name: "stub::other::x",
            description: "X.",
            input_schema: schema_of::<Empty>,
            output_schema: schema_of::<Empty>,
            timeout: Duration::from_millis(100),
            source: ToolSource::ClientLocal,
            required_contexts: &[],
            requires_user_approval: false,
        }];
    }

    impl Dispatcher for OtherDispatcher {
        fn descriptors(&self) -> &'static [ToolDescriptor] {
            Self::DESCRIPTORS
        }

        fn dispatch(&self, _call: IncomingCall) -> BoxFuture<'_, Result<Value, ToolError>> {
            Box::pin(async { Ok(Value::Null) })
        }
    }

    /// Dispatcher whose declared name overlaps with [`StubDispatcher`] —
    /// used to verify duplicate detection.
    struct CollidingDispatcher;

    impl CollidingDispatcher {
        const DESCRIPTORS: &'static [ToolDescriptor] = &[ToolDescriptor {
            name: "stub::tool::a", // collides with StubDispatcher.
            description: "collision.",
            input_schema: schema_of::<Empty>,
            output_schema: schema_of::<Empty>,
            timeout: Duration::from_millis(100),
            source: ToolSource::ClientLocal,
            required_contexts: &[],
            requires_user_approval: false,
        }];
    }

    impl Dispatcher for CollidingDispatcher {
        fn descriptors(&self) -> &'static [ToolDescriptor] {
            Self::DESCRIPTORS
        }

        fn dispatch(&self, _call: IncomingCall) -> BoxFuture<'_, Result<Value, ToolError>> {
            Box::pin(async { Ok(Value::Null) })
        }
    }

    fn sample_call(descriptor_name: &'static str) -> IncomingCall {
        IncomingCall {
            call_id: 1,
            descriptor_name,
            arguments: json!({}),
            origin: Origin::Browser(BrowserOrigin {
                process_id: 1,
                tab_id: 1,
                window_id: None,
                page_url: "https://example.test".into(),
            }),
            cancel: CancellationToken::new(),
        }
    }

    #[test]
    fn register_indexes_every_descriptor_name() {
        let catalog = Catalog::new();
        catalog.register(Arc::new(StubDispatcher));
        assert!(catalog.dispatcher_for("stub::tool::a").is_some());
        assert!(catalog.dispatcher_for("stub::tool::b").is_some());
        assert!(catalog.dispatcher_for("stub::other::x").is_none());
        assert_eq!(catalog.len(), 2);
    }

    #[test]
    fn register_supports_multiple_dispatchers() {
        let catalog = Catalog::new();
        catalog.register(Arc::new(StubDispatcher));
        catalog.register(Arc::new(OtherDispatcher));
        assert_eq!(catalog.len(), 3);
        assert!(catalog.dispatcher_for("stub::other::x").is_some());
    }

    #[test]
    #[should_panic(expected = "duplicate descriptor name")]
    fn register_panics_on_duplicate_name() {
        let catalog = Catalog::new();
        catalog.register(Arc::new(StubDispatcher));
        catalog.register(Arc::new(CollidingDispatcher));
    }

    #[test]
    fn register_does_not_partially_apply_on_panic() {
        let catalog = Catalog::new();
        catalog.register(Arc::new(StubDispatcher));
        // Catch the panic so we can inspect the catalog state afterwards.
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            catalog.register(Arc::new(CollidingDispatcher));
        }));
        assert!(result.is_err(), "register should panic on duplicate");
        // The non-colliding descriptors from the first dispatcher are
        // still there, and the colliding dispatcher's other descriptors
        // (none in this case) didn't sneak in.
        assert_eq!(catalog.len(), 2);
        assert!(Arc::ptr_eq(
            &catalog.dispatcher_for("stub::tool::a").unwrap(),
            &catalog.dispatcher_for("stub::tool::b").unwrap(),
        ));
    }

    #[test]
    fn descriptor_name_for_default_impl_finds_static_name() {
        let d = StubDispatcher;
        assert_eq!(
            d.descriptor_name_for("stub::tool::a"),
            Some("stub::tool::a")
        );
        assert_eq!(
            d.descriptor_name_for("stub::tool::b"),
            Some("stub::tool::b")
        );
        assert_eq!(d.descriptor_name_for("unknown"), None);
    }

    #[test]
    fn all_descriptors_returns_full_set() {
        let catalog = Catalog::new();
        catalog.register(Arc::new(StubDispatcher));
        catalog.register(Arc::new(OtherDispatcher));
        let mut names: Vec<&str> = catalog.all_descriptors().iter().map(|d| d.name).collect();
        names.sort_unstable();
        assert_eq!(
            names,
            vec!["stub::other::x", "stub::tool::a", "stub::tool::b"]
        );
    }

    /// `all_descriptors` must yield each registered descriptor exactly
    /// once — no duplicates from dispatchers that serve multiple tools.
    #[test]
    fn all_descriptors_yields_each_descriptor_exactly_once() {
        let catalog = Catalog::new();
        catalog.register(Arc::new(StubDispatcher));
        catalog.register(Arc::new(OtherDispatcher));
        let names: Vec<&str> = catalog.all_descriptors().iter().map(|d| d.name).collect();
        assert_eq!(names.len(), 3, "expected 3 unique descriptors, got {names:?}");
    }

    #[test]
    fn new_catalog_is_empty() {
        let catalog = Catalog::new();
        assert!(catalog.is_empty());
        assert_eq!(catalog.len(), 0);
        assert!(catalog.all_descriptors().is_empty());
    }

    #[tokio::test(flavor = "current_thread")]
    async fn dispatch_through_catalog_lookup_works_end_to_end() {
        let catalog = Catalog::new();
        catalog.register(Arc::new(StubDispatcher));

        let dispatcher = catalog.dispatcher_for("stub::tool::a").expect("registered");
        let static_name = dispatcher
            .descriptor_name_for("stub::tool::a")
            .expect("known descriptor");

        let result = dispatcher.dispatch(sample_call(static_name)).await.unwrap();
        assert_eq!(result, json!({ "tool": "stub::tool::a" }));
    }
}
