[package]
name = "eur-monolith"
version = "0.1.0"
edition = "2024"
authors = ["Eurora <andre@eurora-labs.com>"]
publish = false

[[bin]]
name = "eur-monolith"
path = "src/main.rs"

[dependencies]
eur-proto = { path = "../../proto/eur-proto" }
eur-questions-service = { path = "../../proto/eur-questions-service" }
tonic = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenv = "0.15"
