//! Argument and return types for the web-page adapter.
//!
//! Every type derives `Serialize + Deserialize + JsonSchema` so the
//! `#[adapter]` macro can emit input/output schemas for the descriptor
//! table and so the dispatcher can encode/decode payloads at runtime.
//! The optional `specta` feature additionally emits `specta::Type` so
//! the same shapes show up in the browser-extension TypeScript
//! bindings generated by `euro-browser`.
//!
//! Empty-args methods reuse [`eurora_tools::Empty`] rather than a
//! web-local type so every empty-args tool across adapters shares one
//! input schema.

use std::collections::HashMap;

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

// ---------- get_page_metadata ----------

/// Page-level metadata exposed to the LLM for the active tab.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct PageMetadata {
    /// Fully-qualified URL of the active document, including query and fragment.
    pub url: String,
    /// `document.title` at observation time.
    pub title: String,
    /// Host component of `url` (no scheme, no port).
    pub host: String,
    /// BCP-47 language tag derived from `<html lang>` then
    /// `<meta http-equiv="content-language">`. `None` when neither is set.
    pub language: Option<String>,
    /// Document character set as reported by the browser, when known.
    pub charset: Option<String>,
    /// `<meta name="description">` content, when present.
    pub description: Option<String>,
    /// OpenGraph tags scraped from `<meta property="og:*">`, keyed by the
    /// suffix after `og:` (e.g. `"title"`, `"image"`, `"site_name"`).
    pub og: HashMap<String, String>,
    /// Scroll and viewport metrics at observation time.
    pub viewport: ViewportMetrics,
}

/// Scroll and viewport metrics for the active document.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct ViewportMetrics {
    /// `window.scrollX` in CSS pixels.
    pub scroll_x: f64,
    /// `window.scrollY` in CSS pixels.
    pub scroll_y: f64,
    /// `window.innerWidth` in CSS pixels.
    pub inner_width: f64,
    /// `window.innerHeight` in CSS pixels.
    pub inner_height: f64,
    /// `document.documentElement.scrollHeight` in CSS pixels.
    pub document_height: f64,
}

// ---------- get_accessibility_tree ----------

/// Arguments to `get_accessibility_tree`. All fields are optional; the
/// content-script applies the documented defaults when omitted.
#[derive(Debug, Default, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct GetAccessibilityTreeArgs {
    /// CSS selector for the subtree root. Defaults to `<body>` when omitted.
    pub root_selector: Option<String>,
    /// Maximum traversal depth. Defaults to 12; deeper nodes are pruned and
    /// [`AccessibilityTree::truncated`] is set.
    pub max_depth: Option<u32>,
    /// Soft cap on emitted nodes. Defaults to 500; hard cap is 2 000.
    /// Reaching the cap sets [`AccessibilityTree::truncated`].
    pub max_nodes: Option<u32>,
}

/// Approximate accessibility tree returned by `get_accessibility_tree`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct AccessibilityTree {
    /// Root of the emitted subtree (the element resolved from
    /// `root_selector`, or `<body>` when none was given).
    pub root: AxNode,
    /// Total number of nodes in the emitted tree, including `root`.
    pub node_count: u32,
    /// `true` when traversal hit `max_depth` or `max_nodes` and one or
    /// more subtrees were elided. The model can refine via `root_selector`
    /// or raise `max_nodes` (within the 2 000 hard cap) to see more.
    pub truncated: bool,
}

/// One node in the approximate accessibility tree. The structure mirrors
/// the platform-computed AX tree CDP exposes, but the role and name are
/// resolved client-side from ARIA attributes and implicit element roles.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct AxNode {
    /// Resolved ARIA role (`"button"`, `"link"`, `"textbox"`, …).
    /// Falls back to `"generic"` when no implicit or explicit role applies.
    pub role: String,
    /// Accessible name computed per the
    /// [accname](https://w3c.github.io/accname/) spec — `aria-labelledby`,
    /// then `aria-label`, then associated `<label>`, then `placeholder`,
    /// then text content.
    pub name: Option<String>,
    /// Current value for form controls (`<input>`, `<textarea>`,
    /// `[role=textbox]`, `[role=slider]`, etc.).
    pub value: Option<String>,
    /// Accessible description from `aria-describedby` or the `title` attr.
    pub description: Option<String>,
    /// CSS selector that re-targets this node for DOM-tool follow-ups
    /// (`query_selector`, `insert_text`). Stable for the lifetime of the
    /// observation; may break after page mutations.
    pub selector_path: Option<String>,
    /// Children in document order. Empty for leaf nodes.
    pub children: Vec<AxNode>,
}

// ---------- get_readability_article ----------

/// Mozilla Readability extraction of the page's primary article.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct ReadabilityArticle {
    /// Article title as Readability resolves it.
    pub title: Option<String>,
    /// Author byline, when Readability can identify one.
    pub byline: Option<String>,
    /// Publishing site name, typically from `<meta property="og:site_name">`.
    pub site_name: Option<String>,
    /// BCP-47 language tag for the article body, when known.
    pub language: Option<String>,
    /// Short excerpt suitable for surface previews.
    pub excerpt: Option<String>,
    /// Sanitised HTML body. Subject to a per-call 32 KB truncation cap.
    pub content_html: String,
    /// Plain-text body. Subject to a per-call 32 KB truncation cap.
    pub text_content: String,
    /// Character length of `text_content` before truncation.
    pub length: u32,
}

// ---------- get_selected_text ----------

/// Whatever the user has highlighted in the active document right now.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct SelectedText {
    /// Highlighted text as `window.getSelection().toString()` returns it.
    /// Empty string when no selection is active.
    pub text: String,
    /// XPath to the selection anchor node, when one is present.
    pub anchor_xpath: Option<String>,
    /// XPath to the selection focus node, when one is present.
    pub focus_xpath: Option<String>,
}

// ---------- query_selector ----------

/// Per-match facet the caller wants populated. Stringly-encoded as a
/// `snake_case` discriminator on the wire so the LLM's input schema is
/// a closed enum, not free-form text.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[serde(rename_all = "snake_case")]
pub enum QuerySelectorInclude {
    /// Populate [`DomNode::text`] with `Element.textContent`.
    Text,
    /// Populate [`DomNode::html`] with `Element.outerHTML`.
    Html,
    /// Populate [`DomNode::attributes`] with the element's attribute map.
    Attributes,
    /// Populate [`DomNode::bounds`] with the element's bounding client rect.
    Bounds,
}

/// Arguments to `query_selector`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct QuerySelectorArgs {
    /// CSS selector evaluated against `document`.
    pub selector: String,
    /// Maximum matches to return. Defaults to 50.
    #[serde(default = "default_query_limit")]
    pub limit: u32,
    /// Per-match facets to populate. Empty `include` returns nodes that
    /// carry only [`DomNode::selector_path`].
    #[serde(default)]
    pub include: Vec<QuerySelectorInclude>,
}

fn default_query_limit() -> u32 {
    50
}

/// Result of a `query_selector` invocation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct QuerySelectorResult {
    /// Emitted matches (post-filter, capped by `limit`).
    pub matches: Vec<DomNode>,
    /// Total number of pre-filter matches, before the safety denylist
    /// and `limit` were applied. When this exceeds `matches.len()`, some
    /// elements were elided (hidden / password / file / submit / CSRF-
    /// shaped metas) or truncated.
    pub total_match_count: u32,
    /// `true` when `total_match_count > matches.len()` for any reason
    /// other than the safety denylist (i.e. the model can ask for more
    /// with a higher `limit`).
    pub truncated: bool,
}

/// One DOM match returned from `query_selector`. Fields beyond
/// `selector_path` are populated only when the corresponding
/// [`QuerySelectorInclude`] was passed.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct DomNode {
    /// CSS selector that re-targets this node for DOM-tool follow-ups.
    pub selector_path: String,
    /// `Element.textContent`, truncated to 8 KB. Present iff the caller
    /// passed [`QuerySelectorInclude::Text`].
    pub text: Option<String>,
    /// `Element.outerHTML`, truncated to 32 KB. Present iff the caller
    /// passed [`QuerySelectorInclude::Html`].
    pub html: Option<String>,
    /// Attribute map (`name` → `value`) of the element. Present iff the
    /// caller passed [`QuerySelectorInclude::Attributes`].
    pub attributes: Option<HashMap<String, String>>,
    /// Bounding client rect in CSS pixels. Present iff the caller passed
    /// [`QuerySelectorInclude::Bounds`] and the element is laid out.
    pub bounds: Option<BoundingBox>,
}

/// Bounding rectangle in CSS pixels — mirrors `DOMRect` semantics.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct BoundingBox {
    /// X coordinate of the left edge, relative to the viewport.
    pub x: f64,
    /// Y coordinate of the top edge, relative to the viewport.
    pub y: f64,
    /// Width in CSS pixels.
    pub width: f64,
    /// Height in CSS pixels.
    pub height: f64,
}

// ---------- list_links ----------

/// Arguments to `list_links`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct ListLinksArgs {
    /// CSS selector scoping the search. Defaults to the whole document.
    pub root_selector: Option<String>,
    /// Maximum links to return. Defaults to 100.
    #[serde(default = "default_links_limit")]
    pub limit: u32,
}

fn default_links_limit() -> u32 {
    100
}

/// Result of a `list_links` invocation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct LinksList {
    /// Emitted links (capped by `limit`).
    pub links: Vec<Link>,
    /// Total number of in-scope links, before `limit` was applied.
    pub total: u32,
}

/// One link, suitable for the model to suggest as a navigation target.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct Link {
    /// Resolved absolute URL of the link target.
    pub url: String,
    /// Accessible label of the link, when one can be resolved.
    pub label: Option<String>,
    /// ARIA role (`"link"` for `<a href>`, possibly `"button"` for
    /// link-styled `<button>`s the content-script chose to include).
    pub role: String,
    /// CSS selector that re-targets this element for DOM-tool follow-ups.
    pub selector_path: String,
}

// ---------- list_form_inputs ----------

/// Arguments to `list_form_inputs`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct ListFormInputsArgs {
    /// CSS selector scoping the search. Defaults to the whole document.
    pub root_selector: Option<String>,
    /// Maximum inputs to return. Defaults to 100.
    #[serde(default = "default_inputs_limit")]
    pub limit: u32,
}

fn default_inputs_limit() -> u32 {
    100
}

/// Result of a `list_form_inputs` invocation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct FormInputsList {
    /// Emitted text-typed editable fields (capped by `limit`).
    pub inputs: Vec<FormInput>,
    /// Total number of allowlisted, enabled, in-scope fields before
    /// `limit` was applied. Password, file, hidden, submit, disabled,
    /// and readonly fields are never counted.
    pub total: u32,
}

/// One editable field discovered by `list_form_inputs`. Restricted by
/// [`FormInputKind`] to the allowlist of safely-writable input types.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct FormInput {
    /// Selector-shaped identifier the model must pass back to
    /// `insert_text`. Stable for the lifetime of the observation.
    pub field_id: String,
    /// Accessible label resolved via `<label for>`, `aria-labelledby`,
    /// `aria-label`, or `placeholder` (in that order).
    pub label: Option<String>,
    /// One of the allowlisted editable kinds. The content-script never
    /// emits a [`FormInput`] outside this set.
    pub kind: FormInputKind,
    /// Current value at observation time. Empty string for empty fields.
    pub value: String,
    /// Placeholder text, when set on the underlying element.
    pub placeholder: Option<String>,
    /// `true` when the field is marked `required` (HTML constraint or
    /// `aria-required="true"`).
    pub required: bool,
}

/// Allowlist of editable input kinds the `insert_text` writer accepts.
/// The content-script never returns any other kind, and `insert_text`
/// rejects writes whose target falls outside this set.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
#[serde(rename_all = "snake_case")]
pub enum FormInputKind {
    /// `<input type="text">`.
    Text,
    /// `<input type="search">`.
    Search,
    /// `<input type="email">`.
    Email,
    /// `<input type="url">`.
    Url,
    /// `<input type="tel">`.
    Tel,
    /// `<input type="number">`.
    Number,
    /// `<textarea>`.
    Textarea,
    /// `[contenteditable="true"]` on any element.
    ContentEditable,
}

// ---------- insert_text ----------

/// Arguments to `insert_text`, the single mutating web tool.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct InsertTextArgs {
    /// Selector-shaped identifier previously returned by `list_form_inputs`.
    /// `insert_text` rejects any `field_id` that doesn't resolve to exactly
    /// one allowlisted, enabled, writable element.
    pub field_id: String,
    /// Text to insert. Inserted as-is — no Unicode normalisation, no key
    /// dispatch, no `Enter`-on-newline.
    pub text: String,
    /// When `true`, overwrite the entire field value. When `false`
    /// (default), append `text` to the existing value. Caret position
    /// is not preserved either way.
    #[serde(default)]
    pub replace: bool,
}

/// Result of a successful `insert_text` call.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
#[cfg_attr(feature = "specta", derive(specta::Type))]
pub struct InsertTextResult {
    /// Echo of the [`InsertTextArgs::field_id`] that was written.
    pub field_id: String,
    /// Value of the field immediately before the write.
    pub previous_value: String,
    /// Value of the field immediately after the write.
    pub new_value: String,
}
