// This file has been generated by Specta. DO NOT EDIT.

export type Frame = { 
/**
 * Decides which listener responds to this frame
 */
command: string; 
/**
 * JSON-encoded string
 */
payload: string; 
/**
 * Each uint32 is the request id of the different type
 */
id: Id | null }

/**
 * Each uint32 is the request id of the different type
 */
export type Id = { Request: number } | { Response: number } | { Event: number } | { Error: number } | { Cancel: number }

export type NativeArticleAsset = { url: string; content: string; text_content: string; selected_text: string | null; title: string; site_name: string; language: string; excerpt: string; length: number }

export type NativeArticleSnapshot = { highlighted_text: string | null }

export type NativeIcon = { base64: string | null }

export type NativeMetadata = { url: string | null; icon_base64: string | null }

export type NativeTwitterAsset = { url: string; title: string; tweets: NativeTwitterTweet[]; timestamp: string }

export type NativeTwitterSnapshot = { tweets: NativeTwitterTweet[]; timestamp: string }

export type NativeTwitterTweet = { text: string; timestamp: string | null; author: string | null }

export type NativeYoutubeAsset = { url: string; title: string; transcript: string; current_time: number }

export type NativeYoutubeSnapshot = { current_time: number; video_frame_base64: string; video_frame_width: number; video_frame_height: number }

