// This file has been generated by Specta. DO NOT EDIT.
import Foundation

/// Either side may send this to abort an in-flight request identified
/// by `id`.
public struct CancelFrame: Codable {
    public let id: UInt32
}

/// Categorises the application a client speaks for. Used by the
/// desktop to route observations to the correct activity strategy and
/// to scope outbound requests.
public enum ClientKind: Codable {
    case browser
    case office
}

/// Failure response correlated with a [`RequestFrame`] by `id`.
public struct ErrorFrame: Codable {
    public let id: UInt32
    public let code: UInt32
    public let message: String
    public let details: String?
}

/// Unsolicited notification pushed by a client (e.g. browser tab
/// activation, Word selection change).
public struct EventFrame: Codable {
    public let action: String
    public let payload: String?
}

/// Top-level envelope sent in both directions on the bridge. Every
/// message is a `Frame`; the [`FrameKind`] discriminator identifies the
/// payload variant.
public struct Frame: Codable {
    public let kind: FrameKind
}

/// Frame payload. Serialized as an externally-tagged JSON object —
/// `{ "Request": { ... } }` — to match the shape the browser extension
/// already consumes.
public enum FrameKind: Codable {
    case request(RequestFrame)
    case response(ResponseFrame)
    case event(EventFrame)
    case error(ErrorFrame)
    case cancel(CancelFrame)
    case register(RegisterFrame)
}

/// Mandatory first frame on every connection. Identifies the host
/// process (the bridge), the application process being represented
/// (e.g. the Chrome PID, the Word PID), and which kind of client is on
/// the other end.
public struct RegisterFrame: Codable {
    public let hostPid: UInt32
    public let appPid: UInt32
    public let clientKind: ClientKind

    private enum CodingKeys: String, CodingKey {
        case hostPid = "host_pid"
        case appPid = "app_pid"
        case clientKind = "client_kind"
    }
}

/// Desktop-initiated request to a connected client.
public struct RequestFrame: Codable {
    public let id: UInt32
    public let action: String
    public let payload: String?
}

/// Client reply to a [`RequestFrame`], correlated by `id`.
public struct ResponseFrame: Codable {
    public let id: UInt32
    public let action: String
    public let payload: String?
}

