//! Auto-generated model profiles.
//!
//! DO NOT EDIT THIS FILE MANUALLY.
//! This file is generated from the models.dev project data.
//!
//! Source: <https://github.com/sst/models.dev>
//! License: MIT License
//!
//! Matches Python `langchain_openai.data._profiles`.

use std::sync::LazyLock;

use agent_chain_core::language_models::ModelProfile;
use agent_chain_core::language_models::ModelProfileRegistry;

/// Static model profile registry for OpenAI models.
///
/// This registry is populated at startup from embedded profile data and
/// augmented with the overrides from `profile_augmentations.toml`.
///
/// Matches Python `_PROFILES` dict in `langchain_openai.data._profiles`.
pub static PROFILES: LazyLock<ModelProfileRegistry> = LazyLock::new(build_profiles);

/// Look up a model profile by name.
///
/// Returns a clone of the profile if found, or a default empty profile.
///
/// Matches Python `_get_default_model_profile`.
pub fn get_default_model_profile(model_name: &str) -> ModelProfile {
    PROFILES.get(model_name).cloned().unwrap_or_default()
}

fn build_profiles() -> ModelProfileRegistry {
    let mut registry = ModelProfileRegistry::new();

    registry.insert(
        "gpt-4.1-nano".to_string(),
        ModelProfile {
            max_input_tokens: Some(1047576),
            max_output_tokens: Some(32768),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(false),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "text-embedding-3-small".to_string(),
        ModelProfile {
            max_input_tokens: Some(8191),
            max_output_tokens: Some(1536),
            image_inputs: Some(false),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(false),
            tool_calling: Some(false),
            structured_output: None,
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-4".to_string(),
        ModelProfile {
            max_input_tokens: Some(8192),
            max_output_tokens: Some(8192),
            image_inputs: Some(false),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(false),
            tool_calling: Some(true),
            structured_output: Some(false),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "o1-pro".to_string(),
        ModelProfile {
            max_input_tokens: Some(200000),
            max_output_tokens: Some(100000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-4o-2024-05-13".to_string(),
        ModelProfile {
            max_input_tokens: Some(128000),
            max_output_tokens: Some(4096),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(false),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-5.1-codex".to_string(),
        ModelProfile {
            max_input_tokens: Some(400000),
            max_output_tokens: Some(128000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(true),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-4o-2024-08-06".to_string(),
        ModelProfile {
            max_input_tokens: Some(128000),
            max_output_tokens: Some(16384),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(false),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-4.1-mini".to_string(),
        ModelProfile {
            max_input_tokens: Some(1047576),
            max_output_tokens: Some(32768),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(false),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "o3-deep-research".to_string(),
        ModelProfile {
            max_input_tokens: Some(200000),
            max_output_tokens: Some(100000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: None,
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-3.5-turbo".to_string(),
        ModelProfile {
            max_input_tokens: Some(16385),
            max_output_tokens: Some(4096),
            image_inputs: Some(false),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(false),
            tool_calling: Some(false),
            structured_output: Some(false),
            image_url_inputs: Some(false),
            pdf_inputs: Some(false),
            pdf_tool_message: Some(false),
            image_tool_message: Some(false),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "text-embedding-3-large".to_string(),
        ModelProfile {
            max_input_tokens: Some(8191),
            max_output_tokens: Some(3072),
            image_inputs: Some(false),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(false),
            tool_calling: Some(false),
            structured_output: None,
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-4-turbo".to_string(),
        ModelProfile {
            max_input_tokens: Some(128000),
            max_output_tokens: Some(4096),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(false),
            tool_calling: Some(true),
            structured_output: Some(false),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "o1-preview".to_string(),
        ModelProfile {
            max_input_tokens: Some(128000),
            max_output_tokens: Some(32768),
            image_inputs: Some(false),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(false),
            structured_output: None,
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-5.1-codex-mini".to_string(),
        ModelProfile {
            max_input_tokens: Some(400000),
            max_output_tokens: Some(128000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(true),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "o3-mini".to_string(),
        ModelProfile {
            max_input_tokens: Some(200000),
            max_output_tokens: Some(100000),
            image_inputs: Some(false),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-5.1".to_string(),
        ModelProfile {
            max_input_tokens: Some(400000),
            max_output_tokens: Some(128000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: None,
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "codex-mini-latest".to_string(),
        ModelProfile {
            max_input_tokens: Some(200000),
            max_output_tokens: Some(100000),
            image_inputs: Some(false),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: None,
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-5-nano".to_string(),
        ModelProfile {
            max_input_tokens: Some(400000),
            max_output_tokens: Some(128000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-5-codex".to_string(),
        ModelProfile {
            max_input_tokens: Some(400000),
            max_output_tokens: Some(128000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-4o".to_string(),
        ModelProfile {
            max_input_tokens: Some(128000),
            max_output_tokens: Some(16384),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(false),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-4.1".to_string(),
        ModelProfile {
            max_input_tokens: Some(1047576),
            max_output_tokens: Some(32768),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(false),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "o4-mini".to_string(),
        ModelProfile {
            max_input_tokens: Some(200000),
            max_output_tokens: Some(100000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "o1".to_string(),
        ModelProfile {
            max_input_tokens: Some(200000),
            max_output_tokens: Some(100000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-5-mini".to_string(),
        ModelProfile {
            max_input_tokens: Some(400000),
            max_output_tokens: Some(128000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "o1-mini".to_string(),
        ModelProfile {
            max_input_tokens: Some(128000),
            max_output_tokens: Some(65536),
            image_inputs: Some(false),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(false),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "text-embedding-ada-002".to_string(),
        ModelProfile {
            max_input_tokens: Some(8192),
            max_output_tokens: Some(1536),
            image_inputs: Some(false),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(false),
            tool_calling: Some(false),
            structured_output: None,
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "o3-pro".to_string(),
        ModelProfile {
            max_input_tokens: Some(200000),
            max_output_tokens: Some(100000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-4o-2024-11-20".to_string(),
        ModelProfile {
            max_input_tokens: Some(128000),
            max_output_tokens: Some(16384),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(false),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "o3".to_string(),
        ModelProfile {
            max_input_tokens: Some(200000),
            max_output_tokens: Some(100000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "o4-mini-deep-research".to_string(),
        ModelProfile {
            max_input_tokens: Some(200000),
            max_output_tokens: Some(100000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: None,
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-5-chat-latest".to_string(),
        ModelProfile {
            max_input_tokens: Some(400000),
            max_output_tokens: Some(128000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(false),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-4o-mini".to_string(),
        ModelProfile {
            max_input_tokens: Some(128000),
            max_output_tokens: Some(16384),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(false),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-5".to_string(),
        ModelProfile {
            max_input_tokens: Some(400000),
            max_output_tokens: Some(128000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-5-pro".to_string(),
        ModelProfile {
            max_input_tokens: Some(400000),
            max_output_tokens: Some(272000),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry.insert(
        "gpt-5.1-chat-latest".to_string(),
        ModelProfile {
            max_input_tokens: Some(128000),
            max_output_tokens: Some(16384),
            image_inputs: Some(true),
            audio_inputs: Some(false),
            video_inputs: Some(false),
            image_outputs: Some(false),
            audio_outputs: Some(false),
            video_outputs: Some(false),
            reasoning_output: Some(true),
            tool_calling: Some(true),
            structured_output: Some(true),
            image_url_inputs: Some(true),
            pdf_inputs: Some(true),
            pdf_tool_message: Some(true),
            image_tool_message: Some(true),
            tool_choice: Some(true),
        },
    );

    registry
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_profiles_populated() {
        assert!(!PROFILES.is_empty());
        assert!(PROFILES.len() >= 34);
    }

    #[test]
    fn test_gpt4o_profile() {
        let profile = get_default_model_profile("gpt-4o");
        assert_eq!(profile.max_input_tokens, Some(128000));
        assert_eq!(profile.max_output_tokens, Some(16384));
        assert_eq!(profile.image_inputs, Some(true));
        assert_eq!(profile.tool_calling, Some(true));
        assert_eq!(profile.structured_output, Some(true));
    }

    #[test]
    fn test_gpt35_turbo_overrides() {
        let profile = get_default_model_profile("gpt-3.5-turbo");
        assert_eq!(profile.image_url_inputs, Some(false));
        assert_eq!(profile.pdf_inputs, Some(false));
        assert_eq!(profile.pdf_tool_message, Some(false));
        assert_eq!(profile.image_tool_message, Some(false));
    }

    #[test]
    fn test_o1_profile() {
        let profile = get_default_model_profile("o1");
        assert_eq!(profile.max_input_tokens, Some(200000));
        assert_eq!(profile.max_output_tokens, Some(100000));
        assert_eq!(profile.reasoning_output, Some(true));
        assert_eq!(profile.tool_calling, Some(true));
    }

    #[test]
    fn test_unknown_model_returns_default() {
        let profile = get_default_model_profile("nonexistent-model");
        assert_eq!(profile.max_input_tokens, None);
        assert_eq!(profile.tool_calling, None);
    }

    #[test]
    fn test_gpt5_profile() {
        let profile = get_default_model_profile("gpt-5");
        assert_eq!(profile.max_input_tokens, Some(400000));
        assert_eq!(profile.max_output_tokens, Some(128000));
        assert_eq!(profile.reasoning_output, Some(true));
    }

    #[test]
    fn test_gpt5_pro_profile() {
        let profile = get_default_model_profile("gpt-5-pro");
        assert_eq!(profile.max_output_tokens, Some(272000));
    }

    #[test]
    fn test_embedding_models_no_tool_calling() {
        let profile = get_default_model_profile("text-embedding-3-small");
        assert_eq!(profile.tool_calling, Some(false));
        assert_eq!(profile.structured_output, None);
    }
}
