// This file has been generated by Specta. Do not edit this file manually.
export type AIMessage = {
	content: ContentBlocks,
	id: string | null,
	name: string | null,
	tool_calls: ToolCall[],
	invalid_tool_calls: InvalidToolCall[],
	usage_metadata: UsageMetadata | null,
	additional_kwargs: unknown,
	response_metadata: unknown,
};

export type AIMessageChunk = {
	content: ContentBlocks,
	id: string | null,
	name: string | null,
	tool_calls: ToolCall[],
	invalid_tool_calls: InvalidToolCall[],
	tool_call_chunks: ToolCallChunk[],
	usage_metadata: UsageMetadata | null,
	additional_kwargs: unknown,
	response_metadata: unknown,
	chunk_position: ChunkPosition | null,
};

export type Annotation = { type: "citation"; id?: string | null; url?: string | null; title?: string | null; start_index?: bigint | null; end_index?: bigint | null; cited_text?: string | null; extras?: unknown | null } | { type: "non_standard_annotation"; id?: string | null; value: unknown };

export type AnyMessage = { type: "human" } & HumanMessage | { type: "system" } & SystemMessage | { type: "ai" } & AIMessage | { type: "tool" } & ToolMessage | { type: "chat" } & ChatMessage | { type: "remove" } & RemoveMessage;

export type AudioContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: unknown | null,
};

export type BlockIndex = bigint | string;

export type ChatMessage = {
	content: ContentBlocks,
	role: string,
	id: string | null,
	name: string | null,
	additional_kwargs: unknown,
	response_metadata: unknown,
};

/**
 *  Frame sent by the server over the chat WebSocket.
 * 
 *  Clients should accumulate `Chunk` payloads (using agent-chain's chunk-merge
 *  semantics) and replace placeholder state with the `Final.messages` payload
 *  when the turn ends.
 */
export type ChatServerMessage = 
// The user's message has been persisted; clients should display it.
{ type: "confirmed_human_message"; message: MessageNode } | 
// One streaming chunk from the AI.
{ type: "chunk"; chunk: AIMessageChunk } | 
/**
 *  The turn ended successfully; tree positions for everything that was
 *  persisted during this turn (human + AI + any tool messages).
 */
{ type: "final"; messages: MessageNode[] } | 
// The turn aborted with an error. The connection is closed after this.
{ type: "error"; kind: string; message: string };

export type ChunkPosition = "last";

export type Claims = {
	sub: string,
	email: string,
	display_name?: string | null,
	exp: bigint,
	iat: bigint,
	token_type: string,
	role: Role,
	aud?: string,
	email_verified?: boolean,
	/**
	 *  RFC 7519 JWT ID. Guarantees that two tokens minted for
	 *  the same subject within the same second never collide
	 *  after hashing (see refresh-token rotation).
	 */
	jti?: string,
};

export type ContentBlock = { type: "text" } & TextContentBlock | { type: "invalid_tool_call" } & InvalidToolCallBlock | { type: "reasoning" } & ReasoningContentBlock | { type: "non_standard" } & NonStandardContentBlock | { type: "image" } & ImageContentBlock | { type: "video" } & VideoContentBlock | { type: "audio" } & AudioContentBlock | { type: "text-plain" } & PlainTextContentBlock | { type: "file" } & FileContentBlock | { type: "tool_call" } & ToolCallBlock | { type: "tool_call_chunk" } & ToolCallChunkBlock | { type: "server_tool_call" } & ServerToolCall | { type: "server_tool_call_chunk" } & ServerToolCallChunk | { type: "server_tool_result" } & ServerToolResult;

export type ContentBlocks = ContentBlock[];

export type FileContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: unknown | null,
};

export type HumanMessage = {
	content: ContentBlocks,
	id: string | null,
	name: string | null,
	additional_kwargs: unknown,
	response_metadata: unknown,
};

export type ImageContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: unknown | null,
};

export type InputTokenDetails = ({ [key in string]: bigint }) & {
	audio?: bigint | null,
	cache_creation?: bigint | null,
	cache_read?: bigint | null,
};

export type InvalidToolCall = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	error?: string | null,
	type?: string | null,
};

export type InvalidToolCallBlock = {
	id: string | null,
	name: string | null,
	args: string | null,
	error: string | null,
	index?: BlockIndex | null,
	extras?: unknown | null,
};

export type LoginOutcome = { kind: "success" } | { kind: "canceled" } | { kind: "rejected" };

// One node in the message tree returned by message-list endpoints.
export type MessageNode = {
	parent_id?: string | null,
	message: AnyMessage,
	children?: MessageNode[],
	sibling_index: number,
	depth: number,
};

export type NonStandardContentBlock = {
	id?: string | null,
	value: unknown,
	index?: BlockIndex | null,
};

export type OutputTokenDetails = ({ [key in string]: bigint }) & {
	audio?: bigint | null,
	reasoning?: bigint | null,
};

export type PlainTextContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type: string,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	text?: string | null,
	title?: string | null,
	context?: string | null,
	extras?: unknown | null,
};

export type Query = {
	text: string,
	assets: string[],
	parent_message_id: string | null,
};

export type ReasoningContentBlock = {
	id?: string | null,
	reasoning?: string | null,
	index?: BlockIndex | null,
	extras?: unknown | null,
};

export type RemoveMessage = {
	id: string,
	name?: string | null,
	additional_kwargs?: unknown,
	response_metadata?: unknown,
};

export type Role = "Free" | "Tier1";

export type SearchMessageResultView = {
	id: string,
	thread_id: string,
	message_type: string,
	snippet: string,
	rank: number,
};

export type SearchThreadResultView = {
	id: string,
	title: string,
	rank: number,
};

export type ServerToolCall = {
	id: string,
	name: string,
	args: unknown,
	index?: BlockIndex | null,
	extras?: unknown | null,
};

export type ServerToolCallChunk = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	index?: BlockIndex | null,
	extras?: unknown | null,
};

export type ServerToolResult = {
	id?: string | null,
	tool_call_id: string,
	status: ServerToolStatus,
	output?: unknown | null,
	index?: BlockIndex | null,
	extras?: unknown | null,
};

export type ServerToolStatus = "success" | "error";

export type SystemMessage = {
	content: ContentBlocks,
	id: string | null,
	name: string | null,
	additional_kwargs: unknown,
	response_metadata: unknown,
};

export type TextContentBlock = {
	id?: string | null,
	text: string,
	annotations?: Annotation[] | null,
	index?: BlockIndex | null,
	extras?: unknown | null,
};

export type Thread = {
	id: string | null,
	title: string,
	created_at: string,
	updated_at: string,
};

export type ToolCall = {
	id: string | null,
	name: string,
	args: unknown,
	type?: string | null,
};

export type ToolCallBlock = {
	id: string | null,
	name: string,
	args: unknown,
	index?: BlockIndex | null,
	extras?: unknown | null,
};

export type ToolCallChunk = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	index?: number | null,
	type?: string | null,
};

export type ToolCallChunkBlock = {
	id: string | null,
	name: string | null,
	args: string | null,
	index?: BlockIndex | null,
	extras?: unknown | null,
};

export type ToolMessage = {
	content: ContentBlocks,
	tool_call_id: string,
	id: string | null,
	name: string | null,
	status: ToolStatus,
	artifact: unknown | null,
	additional_kwargs: unknown,
	response_metadata: unknown,
};

export type ToolStatus = "success" | "error";

export type UsageMetadata = {
	input_tokens: bigint,
	output_tokens: bigint,
	total_tokens: bigint,
	input_token_details?: InputTokenDetails | null,
	output_token_details?: OutputTokenDetails | null,
};

export type VideoContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: unknown | null,
};
import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void
const ARGS_MAP = { 'auth':'{"auth_state_changed":["claims"],"get_display_name":[],"get_email":[],"get_role":[],"is_authenticated":[],"login":["login","password"],"logout":[],"refresh_session":[],"register":["email","password"],"start_login":[]}', 'chat':'{"cancel_query":["thread_id"],"send_query":["thread_id","channel","query"]}', 'thread':'{"create":[],"delete":["thread_id"],"generate_title":["thread_id"],"get_messages":["thread_id","limit","offset","all_variants"],"list":["limit","offset"],"search_messages":["query","limit","offset"],"search_threads":["query","limit","offset"],"switch_branch":["thread_id","message_id","direction"]}' }
export type Router = { "auth": {auth_state_changed: (claims: {
	sub: string,
	email: string,
	display_name: string | null,
	exp: bigint,
	iat: bigint,
	token_type: string,
	role: Role,
	aud: string,
	email_verified: boolean,
	/**
	 *  RFC 7519 JWT ID. Guarantees that two tokens minted for
	 *  the same subject within the same second never collide
	 *  after hashing (see refresh-token rotation).
	 */
	jti: string,
} | null) => Promise<void>, 
get_display_name: () => Promise<string | null>, 
get_email: () => Promise<string>, 
get_role: () => Promise<string>, 
is_authenticated: () => Promise<boolean>, 
login: (login: string, password: string) => Promise<null>, 
logout: () => Promise<null>, 
refresh_session: () => Promise<null>, 
register: (email: string, password: string) => Promise<null>, 
start_login: () => Promise<LoginOutcome>},
"chat": {cancel_query: (threadId: string) => Promise<null>, 
send_query: (threadId: string, channel: TAURI_CHANNEL<ChatServerMessage>, query: Query) => Promise<null>},
"thread": {create: () => Promise<Thread>, 
delete: (threadId: string) => Promise<null>, 
generate_title: (threadId: string) => Promise<Thread>, 
get_messages: (threadId: string, limit: number, offset: number, allVariants: boolean) => Promise<MessageNode[]>, 
list: (limit: number, offset: number) => Promise<Thread[]>, 
search_messages: (query: string, limit: number, offset: number) => Promise<SearchMessageResultView[]>, 
search_threads: (query: string, limit: number, offset: number) => Promise<SearchThreadResultView[]>, 
switch_branch: (threadId: string, messageId: string, direction: number) => Promise<MessageNode[]>} };

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
