// This file has been generated by Specta. Do not edit this file manually.
export type Annotation = { Citation: ProtoCitation } | { NonStandard: ProtoNonStandardAnnotation };

export type BaseMessageWithSibling = {
	parent_id: string,
	message: ProtoBaseMessage | null,
	children: BaseMessageWithSibling[],
	sibling_index: number,
	depth: number,
};

export type Block = { Text: ProtoTextContentBlock } | { InvalidToolCall: ProtoInvalidToolCallBlock } | { Reasoning: ProtoReasoningContentBlock } | { NonStandard: ProtoNonStandardContentBlock } | { Image: ProtoImageContentBlock } | { Video: ProtoVideoContentBlock } | { Audio: ProtoAudioContentBlock } | { PlainText: ProtoPlainTextContentBlock } | { File: ProtoFileContentBlock } | { ToolCall: ProtoToolCallBlock } | { ToolCallChunk: ProtoToolCallChunkBlock } | { ServerToolCall: ProtoServerToolCall } | { ServerToolCallChunk: ProtoServerToolCallChunk } | { ServerToolResult: ProtoServerToolResult };

export type ChatStreamFinalMessage = {
	messages: BaseMessageWithSibling[],
};

export type ChatStreamResponse = {
	payload: Payload | null,
};

export type Claims = {
	sub: string,
	email: string,
	display_name?: string | null,
	exp: bigint,
	iat: bigint,
	token_type: string,
	role: Role,
	aud?: string,
	email_verified?: boolean,
	/**
	 *  RFC 7519 JWT ID. Guarantees that two tokens minted for
	 *  the same subject within the same second never collide
	 *  after hashing (see refresh-token rotation).
	 */
	jti?: string,
};

export type GetLoginTokenArgs = {
	/**
	 *  Redirect URI the OAuth flow should send the user to once authentication
	 *  completes. Echoed verbatim into the `redirect_uri` query param the web
	 *  login page consumes via `validateAppRedirectUri`.
	 */
	redirect_uri: string,
};

export type Index = { IntIndex: bigint } | { StrIndex: string };

export type LoginToken = {
	code_challenge: string,
	expires_in: bigint,
	url: string,
};

export type Message = { Human: ProtoHumanMessage } | { System: ProtoSystemMessage } | { Ai: ProtoAiMessage } | { Tool: ProtoToolMessage } | { Chat: ProtoChatMessage } | { Remove: ProtoRemoveMessage };

export type Payload = { Chunk: ProtoAiMessageChunk } | { FinalMessage: ChatStreamFinalMessage } | { ConfirmedHumanMessage: BaseMessageWithSibling };

export type ProtoAiMessage = {
	content: ProtoContentBlock[],
	id: string | null,
	name: string | null,
	tool_calls: ProtoToolCall[],
	invalid_tool_calls: ProtoInvalidToolCall[],
	usage_metadata: ProtoUsageMetadata | null,
	additional_kwargs: string | null,
	response_metadata: string | null,
};

export type ProtoAiMessageChunk = {
	content: ProtoContentBlock[],
	id: string | null,
	name: string | null,
	tool_calls: ProtoToolCall[],
	invalid_tool_calls: ProtoInvalidToolCall[],
	tool_call_chunks: ProtoToolCallChunk[],
	usage_metadata: ProtoUsageMetadata | null,
	additional_kwargs: string | null,
	response_metadata: string | null,
	chunk_position: number | null,
};

export type ProtoAnnotation = {
	annotation: Annotation | null,
};

export type ProtoAudioContentBlock = {
	id: string | null,
	file_id: string | null,
	mime_type: string | null,
	index: ProtoBlockIndex | null,
	url: string | null,
	base64: string | null,
	extras: string | null,
};

export type ProtoBaseMessage = {
	message: Message | null,
};

export type ProtoBlockIndex = {
	index: Index | null,
};

export type ProtoChatMessage = {
	content: ProtoContentBlock[],
	role: string,
	id: string | null,
	name: string | null,
	additional_kwargs: string | null,
	response_metadata: string | null,
};

export type ProtoCitation = {
	id: string | null,
	url: string | null,
	title: string | null,
	start_index: bigint | null,
	end_index: bigint | null,
	cited_text: string | null,
	extras: string | null,
};

export type ProtoContentBlock = {
	block: Block | null,
};

export type ProtoFileContentBlock = {
	id: string | null,
	file_id: string | null,
	mime_type: string | null,
	index: ProtoBlockIndex | null,
	url: string | null,
	base64: string | null,
	extras: string | null,
};

export type ProtoHumanMessage = {
	content: ProtoContentBlock[],
	id: string | null,
	name: string | null,
	additional_kwargs: string | null,
	response_metadata: string | null,
};

export type ProtoImageContentBlock = {
	id: string | null,
	file_id: string | null,
	mime_type: string | null,
	index: ProtoBlockIndex | null,
	url: string | null,
	base64: string | null,
	extras: string | null,
};

export type ProtoInputTokenDetails = {
	audio: bigint | null,
	cache_creation: bigint | null,
	cache_read: bigint | null,
	extra: string | null,
};

export type ProtoInvalidToolCall = {
	name: string | null,
	args: string | null,
	id: string | null,
	error: string | null,
	call_type: string | null,
};

export type ProtoInvalidToolCallBlock = {
	id: string | null,
	name: string | null,
	args: string | null,
	error: string | null,
	index: ProtoBlockIndex | null,
	extras: string | null,
};

export type ProtoNonStandardAnnotation = {
	id: string | null,
	value: string,
};

export type ProtoNonStandardContentBlock = {
	id: string | null,
	value: string,
	index: ProtoBlockIndex | null,
};

export type ProtoOutputTokenDetails = {
	audio: bigint | null,
	reasoning: bigint | null,
	extra: string | null,
};

export type ProtoPlainTextContentBlock = {
	id: string | null,
	file_id: string | null,
	mime_type: string,
	index: ProtoBlockIndex | null,
	url: string | null,
	base64: string | null,
	text: string | null,
	title: string | null,
	context: string | null,
	extras: string | null,
};

export type ProtoReasoningContentBlock = {
	id: string | null,
	reasoning: string | null,
	index: ProtoBlockIndex | null,
	extras: string | null,
};

export type ProtoRemoveMessage = {
	id: string,
	name: string | null,
	additional_kwargs: string | null,
	response_metadata: string | null,
};

export type ProtoServerToolCall = {
	id: string,
	name: string,
	args: string,
	index: ProtoBlockIndex | null,
	extras: string | null,
};

export type ProtoServerToolCallChunk = {
	name: string | null,
	args: string | null,
	id: string | null,
	index: ProtoBlockIndex | null,
	extras: string | null,
};

export type ProtoServerToolResult = {
	id: string | null,
	tool_call_id: string,
	status: number,
	output: string | null,
	index: ProtoBlockIndex | null,
	extras: string | null,
};

export type ProtoSystemMessage = {
	content: ProtoContentBlock[],
	id: string | null,
	name: string | null,
	additional_kwargs: string | null,
	response_metadata: string | null,
};

export type ProtoTextContentBlock = {
	id: string | null,
	text: string,
	annotations: ProtoAnnotation[],
	index: ProtoBlockIndex | null,
	extras: string | null,
};

export type ProtoToolCall = {
	id: string | null,
	name: string,
	args: string,
	call_type: string | null,
};

export type ProtoToolCallBlock = {
	id: string | null,
	name: string,
	args: string,
	index: ProtoBlockIndex | null,
	extras: string | null,
};

export type ProtoToolCallChunk = {
	name: string | null,
	args: string | null,
	id: string | null,
	index: number | null,
	chunk_type: string | null,
};

export type ProtoToolCallChunkBlock = {
	id: string | null,
	name: string | null,
	args: string | null,
	index: ProtoBlockIndex | null,
	extras: string | null,
};

export type ProtoToolMessage = {
	content: ProtoContentBlock[],
	tool_call_id: string,
	id: string | null,
	name: string | null,
	status: number,
	artifact: string | null,
	additional_kwargs: string | null,
	response_metadata: string | null,
};

export type ProtoUsageMetadata = {
	input_tokens: bigint,
	output_tokens: bigint,
	total_tokens: bigint,
	input_token_details: ProtoInputTokenDetails | null,
	output_token_details: ProtoOutputTokenDetails | null,
};

export type ProtoVideoContentBlock = {
	id: string | null,
	file_id: string | null,
	mime_type: string | null,
	index: ProtoBlockIndex | null,
	url: string | null,
	base64: string | null,
	extras: string | null,
};

export type Query = {
	text: string,
	assets: string[],
	parent_message_id: string | null,
};

export type Role = "Free" | "Tier1";

export type SearchMessageResultView = {
	id: string,
	thread_id: string,
	message_type: string,
	snippet: string,
	rank: number,
};

export type SearchThreadResultView = {
	id: string,
	title: string,
	rank: number,
};

export type Thread = {
	id: string | null,
	title: string,
	created_at: string,
	updated_at: string,
};
import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void
const ARGS_MAP = { 'auth':'{"auth_state_changed":["claims"],"complete_login":["callback_url"],"get_display_name":[],"get_email":[],"get_login_token":["args"],"get_role":[],"is_authenticated":[],"login":["login","password"],"logout":[],"refresh_session":[],"register":["email","password"]}', 'chat':'{"cancel_query":["thread_id"],"send_query":["thread_id","channel","query"]}', 'thread':'{"create":[],"delete":["thread_id"],"generate_title":["thread_id","content"],"get_messages":["thread_id","limit","offset","all_variants"],"list":["limit","offset"],"search_messages":["query","limit","offset"],"search_threads":["query","limit","offset"],"switch_branch":["thread_id","message_id","direction"]}' }
export type Router = { "auth": {auth_state_changed: (claims: {
	sub: string,
	email: string,
	display_name: string | null,
	exp: bigint,
	iat: bigint,
	token_type: string,
	role: Role,
	aud: string,
	email_verified: boolean,
	/**
	 *  RFC 7519 JWT ID. Guarantees that two tokens minted for
	 *  the same subject within the same second never collide
	 *  after hashing (see refresh-token rotation).
	 */
	jti: string,
} | null) => Promise<void>, 
complete_login: (callbackUrl: string) => Promise<boolean>, 
get_display_name: () => Promise<string | null>, 
get_email: () => Promise<string>, 
get_login_token: (args: GetLoginTokenArgs) => Promise<LoginToken>, 
get_role: () => Promise<string>, 
is_authenticated: () => Promise<boolean>, 
login: (login: string, password: string) => Promise<null>, 
logout: () => Promise<null>, 
refresh_session: () => Promise<null>, 
register: (email: string, password: string) => Promise<null>},
"chat": {cancel_query: (threadId: string) => Promise<null>, 
send_query: (threadId: string, channel: TAURI_CHANNEL<ChatStreamResponse>, query: Query) => Promise<null>},
"thread": {create: () => Promise<Thread>, 
delete: (threadId: string) => Promise<null>, 
generate_title: (threadId: string, content: string) => Promise<Thread>, 
get_messages: (threadId: string, limit: number, offset: number, allVariants: boolean) => Promise<BaseMessageWithSibling[]>, 
list: (limit: number, offset: number) => Promise<Thread[]>, 
search_messages: (query: string, limit: number, offset: number) => Promise<SearchMessageResultView[]>, 
search_threads: (query: string, limit: number, offset: number) => Promise<SearchThreadResultView[]>, 
switch_branch: (threadId: string, messageId: string, direction: number) => Promise<BaseMessageWithSibling[]>} };

export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
