// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from '@tauri-apps/api/core';
import * as __TAURI_EVENT from '@tauri-apps/api/event';

/** Commands */
export const commands = {
	authStartLogin: async () =>
		await typedError<LoginOutcome, string>(__TAURI_INVOKE('auth_start_login')),
	authLogin: async (login: string, password: string) =>
		await typedError<null, string>(__TAURI_INVOKE('auth_login', { login, password })),
	authRegister: async (email: string, password: string) =>
		await typedError<null, string>(__TAURI_INVOKE('auth_register', { email, password })),
	authLogout: async () => await typedError<null, string>(__TAURI_INVOKE('auth_logout')),
	authIsAuthenticated: async () =>
		await typedError<boolean, string>(__TAURI_INVOKE('auth_is_authenticated')),
	authGetAccessTokenPayload: async () =>
		await typedError<Claims, string>(__TAURI_INVOKE('auth_get_access_token_payload')),
	authRefreshSession: async () =>
		await typedError<null, string>(__TAURI_INVOKE('auth_refresh_session')),
	threadList: async (limit: number, offset: number) =>
		await typedError<Thread[], string>(__TAURI_INVOKE('thread_list', { limit, offset })),
	threadCreate: async () => await typedError<Thread, string>(__TAURI_INVOKE('thread_create')),
	threadDelete: async (threadId: string) =>
		await typedError<null, string>(__TAURI_INVOKE('thread_delete', { threadId })),
	threadGetMessages: async (threadId: string, limit: number, offset: number) =>
		await typedError<MessageNode[], string>(
			__TAURI_INVOKE('thread_get_messages', { threadId, limit, offset }),
		),
	threadSwitchBranch: async (threadId: string, messageId: string, direction: number) =>
		await typedError<MessageNode[], string>(
			__TAURI_INVOKE('thread_switch_branch', { threadId, messageId, direction }),
		),
	threadGenerateTitle: async (threadId: string) =>
		await typedError<Thread, string>(__TAURI_INVOKE('thread_generate_title', { threadId })),
	threadSearchThreads: async (query: string, limit: number, offset: number) =>
		await typedError<SearchThreadResult[], string>(
			__TAURI_INVOKE('thread_search_threads', { query, limit, offset }),
		),
	threadSearchMessages: async (query: string, limit: number, offset: number) =>
		await typedError<SearchMessageResult[], string>(
			__TAURI_INVOKE('thread_search_messages', { query, limit, offset }),
		),
	chatSendQuery: async (
		threadId: string,
		channel: Channel<ChatServerMessage>,
		request: ChatSendRequest,
	) =>
		await typedError<null, string>(
			__TAURI_INVOKE('chat_send_query', { threadId, channel, request }),
		),
	chatRegenerate: async (
		threadId: string,
		aiMessageId: string,
		channel: Channel<ChatServerMessage>,
	) =>
		await typedError<null, string>(
			__TAURI_INVOKE('chat_regenerate', { threadId, aiMessageId, channel }),
		),
	chatCancelQuery: async (threadId: string) =>
		await typedError<null, string>(__TAURI_INVOKE('chat_cancel_query', { threadId })),
};

/** Events */
export const events = {
	authStateChanged: makeEvent<AuthStateChanged>('auth-state-changed'),
};

/* Types */
export type AIMessage = {
	content: ContentBlocks;
	id?: string | null;
	name?: string | null;
	tool_calls?: ToolCall[];
	invalid_tool_calls?: InvalidToolCall[];
	usage_metadata?: UsageMetadata | null;
	additional_kwargs?: { [key in string]: unknown };
	response_metadata?: { [key in string]: unknown };
};

export type AIMessageChunk = {
	content: ContentBlocks;
	id?: string | null;
	name?: string | null;
	tool_calls?: ToolCall[];
	invalid_tool_calls?: InvalidToolCall[];
	tool_call_chunks: ToolCallChunk[];
	usage_metadata?: UsageMetadata | null;
	additional_kwargs?: { [key in string]: unknown };
	response_metadata?: { [key in string]: unknown };
	chunk_position?: ChunkPosition | null;
};

export type Annotation =
	| {
			type: 'citation';
			id?: string | null;
			url?: string | null;
			title?: string | null;
			start_index?: bigint | null;
			end_index?: bigint | null;
			cited_text?: string | null;
			extras?: { [key in string]: unknown } | null;
	  }
	| { type: 'non_standard_annotation'; id?: string | null; value: { [key in string]: unknown } };

/**
 *  Tagged union of every message variant. Wire format is internally tagged on
 *  the `type` field — `{"type": "human", "content": ..., ...}` etc. The inner
 *  per-variant structs (`HumanMessage`, `AIMessage`, ...) deliberately do NOT
 *  carry their own `type` field; the discriminant is added at the union level
 *  and only there. This keeps the Rust types and the specta-generated TS types
 *  in lockstep with the actual JSON shape.
 */
export type AnyMessage =
	| ({
			type: 'human';
	  } & HumanMessage)
	| ({
			type: 'system';
	  } & SystemMessage)
	| ({
			type: 'ai';
	  } & AIMessage)
	| ({
			type: 'tool';
	  } & ToolMessage)
	| ({
			type: 'chat';
	  } & ChatMessage)
	| ({
			type: 'remove';
	  } & RemoveMessage);

export type AudioContentBlock = {
	id?: string | null;
	file_id?: string | null;
	mime_type?: string | null;
	index?: BlockIndex | null;
	url?: string | null;
	base64?: string | null;
	extras?: { [key in string]: unknown } | null;
};

export type AuthStateChanged = {
	claims: Claims | null;
};

export type BlockIndex = number | string;

export type ChatMessage = {
	content: ContentBlocks;
	role: string;
	id?: string | null;
	name?: string | null;
	additional_kwargs?: { [key in string]: unknown };
	response_metadata?: { [key in string]: unknown };
};

/**
 *  Payload of a [`ChatClientMessage::Send`] frame.
 *
 *  When `parent_message_id` is present the turn is interpreted as an edit of
 *  an existing branch; the service rewinds `active_leaf` accordingly.
 */
export type ChatSendRequest = {
	content_blocks: ContentBlock[];
	parent_message_id?: string | null;
	asset_chips_json?: string | null;
};

/**
 *  Frame sent by the server over the chat WebSocket.
 *
 *  Clients should accumulate `Chunk` payloads (using agent-chain's chunk-merge
 *  semantics) and replace placeholder state with the `Final.messages` payload
 *  when the turn ends.
 */
export type ChatServerMessage =
	/**  The user's message has been persisted; clients should display it. */
	| { type: 'confirmed_human_message'; message: MessageNode }
	/**  One streaming chunk from the AI. */
	| { type: 'chunk'; chunk: AIMessageChunk }
	/**
	 *  The turn ended successfully; tree positions for everything that was
	 *  persisted during this turn (human + AI + any tool messages).
	 */
	| { type: 'final'; messages: MessageNode[] }
	/**  The turn aborted with an error. The connection is closed after this. */
	| { type: 'error'; kind: string; message: string };

export type ChunkPosition = 'last';

export type Claims = {
	sub: string;
	email: string;
	display_name?: string | null;
	exp: bigint;
	iat: bigint;
	token_type: string;
	role: Role;
	aud?: string;
	email_verified?: boolean;
	/**
	 *  RFC 7519 JWT ID. Guarantees that two tokens minted for
	 *  the same subject within the same second never collide
	 *  after hashing (see refresh-token rotation).
	 */
	jti?: string;
};

export type ContentBlock =
	| ({
			type: 'text';
	  } & TextContentBlock)
	| ({
			type: 'invalid_tool_call';
	  } & InvalidToolCallBlock)
	| ({
			type: 'reasoning';
	  } & ReasoningContentBlock)
	| ({
			type: 'non_standard';
	  } & NonStandardContentBlock)
	| ({
			type: 'image';
	  } & ImageContentBlock)
	| ({
			type: 'video';
	  } & VideoContentBlock)
	| ({
			type: 'audio';
	  } & AudioContentBlock)
	| ({
			type: 'text-plain';
	  } & PlainTextContentBlock)
	| ({
			type: 'file';
	  } & FileContentBlock)
	| ({
			type: 'tool_call';
	  } & ToolCallBlock)
	| ({
			type: 'tool_call_chunk';
	  } & ToolCallChunkBlock)
	| ({
			type: 'server_tool_call';
	  } & ServerToolCall)
	| ({
			type: 'server_tool_call_chunk';
	  } & ServerToolCallChunk)
	| ({
			type: 'server_tool_result';
	  } & ServerToolResult);

export type ContentBlocks = ContentBlock[];

export type FileContentBlock = {
	id?: string | null;
	file_id?: string | null;
	mime_type?: string | null;
	index?: BlockIndex | null;
	url?: string | null;
	base64?: string | null;
	extras?: { [key in string]: unknown } | null;
};

export type HumanMessage = {
	content: ContentBlocks;
	id?: string | null;
	name?: string | null;
	additional_kwargs?: { [key in string]: unknown };
	response_metadata?: { [key in string]: unknown };
};

export type ImageContentBlock = {
	id?: string | null;
	file_id?: string | null;
	mime_type?: string | null;
	index?: BlockIndex | null;
	url?: string | null;
	base64?: string | null;
	extras?: { [key in string]: unknown } | null;
};

export type InputTokenDetails = {
	audio?: bigint | null;
	cache_creation?: bigint | null;
	cache_read?: bigint | null;
} & { [key in string]: bigint };

export type InvalidToolCall = {
	name?: string | null;
	args?: string | null;
	id?: string | null;
	error?: string | null;
	type?: string | null;
};

export type InvalidToolCallBlock = {
	id?: string | null;
	name?: string | null;
	args?: string | null;
	error?: string | null;
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

export type LoginOutcome = { kind: 'success' } | { kind: 'canceled' } | { kind: 'rejected' };

/**  One node in the message tree returned by message-list endpoints. */
export type MessageNode = {
	parent_id?: string | null;
	message: AnyMessage;
	children?: MessageNode[];
	sibling_index: number;
	depth: number;
};

export type NonStandardContentBlock = {
	id?: string | null;
	value?: { [key in string]: unknown };
	index?: BlockIndex | null;
};

export type OutputTokenDetails = {
	audio?: bigint | null;
	reasoning?: bigint | null;
} & { [key in string]: bigint };

export type PlainTextContentBlock = {
	id?: string | null;
	file_id?: string | null;
	mime_type: string;
	index?: BlockIndex | null;
	url?: string | null;
	base64?: string | null;
	text?: string | null;
	title?: string | null;
	context?: string | null;
	extras?: { [key in string]: unknown } | null;
};

export type ReasoningContentBlock = {
	id?: string | null;
	reasoning?: string | null;
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

export type RemoveMessage = {
	id: string;
	name?: string | null;
	additional_kwargs?: { [key in string]: unknown };
	response_metadata?: { [key in string]: unknown };
};

export type Role = 'Free' | 'Tier1';

/**  One message hit returned by full-text search. */
export type SearchMessageResult = {
	id: string;
	thread_id: string;
	message_type: string;
	rank: number | null;
	created_at: string;
	snippet: string;
};

/**  One thread hit returned by full-text search. */
export type SearchThreadResult = {
	id: string;
	title: string;
	rank: number | null;
	updated_at: string;
};

export type ServerToolCall = {
	id: string;
	name: string;
	args?: { [key in string]: unknown };
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

export type ServerToolCallChunk = {
	name?: string | null;
	args?: string | null;
	id?: string | null;
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

export type ServerToolResult = {
	id?: string | null;
	tool_call_id: string;
	status: ServerToolStatus;
	output?: unknown | null;
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

export type ServerToolStatus = 'success' | 'error';

export type SystemMessage = {
	content: ContentBlocks;
	id?: string | null;
	name?: string | null;
	additional_kwargs?: { [key in string]: unknown };
	response_metadata?: { [key in string]: unknown };
};

export type TextContentBlock = {
	id?: string | null;
	text: string;
	annotations?: Annotation[] | null;
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

/**  A persisted thread row as returned to the client. */
export type Thread = {
	id: string;
	user_id: string;
	title: string;
	created_at: string;
	updated_at: string;
	active_leaf_id?: string | null;
};

export type ToolCall = {
	id?: string | null;
	name: string;
	/**
	 *  Always a JSON object on the wire. The struct-side type stays
	 *  `serde_json::Value` for ergonomic constructor input, but the specta-
	 *  generated TS type is `Record<string, unknown>` to reflect that.
	 */
	args: { [key in string]: unknown };
	type?: string | null;
};

export type ToolCallBlock = {
	id?: string | null;
	name: string;
	args?: { [key in string]: unknown };
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

export type ToolCallChunk = {
	name?: string | null;
	args?: string | null;
	id?: string | null;
	index?: number | null;
	type?: string | null;
};

export type ToolCallChunkBlock = {
	id?: string | null;
	name?: string | null;
	args?: string | null;
	index?: BlockIndex | null;
	extras?: { [key in string]: unknown } | null;
};

export type ToolMessage = {
	content: ContentBlocks;
	tool_call_id: string;
	id?: string | null;
	name?: string | null;
	status?: ToolStatus;
	artifact?: unknown | null;
	additional_kwargs?: { [key in string]: unknown };
	response_metadata?: { [key in string]: unknown };
};

export type ToolStatus = 'success' | 'error';

export type UsageMetadata = {
	input_tokens: bigint;
	output_tokens: bigint;
	total_tokens: bigint;
	input_token_details?: InputTokenDetails | null;
	output_token_details?: OutputTokenDetails | null;
};

export type VideoContentBlock = {
	id?: string | null;
	file_id?: string | null;
	mime_type?: string | null;
	index?: BlockIndex | null;
	url?: string | null;
	base64?: string | null;
	extras?: { [key in string]: unknown } | null;
};

/* Tauri Specta runtime */
async function typedError<T, E>(
	result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
	try {
		return { status: 'ok', data: await result };
	} catch (e) {
		if (e instanceof Error) throw e;
		return { status: 'error', error: e as any };
	}
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(
	name: string,
	serialize?: (payload: T) => unknown,
	deserialize?: (payload: any) => T,
) {
	const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) =>
		cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
	const mapPayload = (payload: T) => (serialize ? serialize(payload) : payload);

	const base = {
		listen: async (cb: __TAURI_EVENT.EventCallback<T>) =>
			await __TAURI_EVENT.listen(name, mapEvent(cb)),
		once: async (cb: __TAURI_EVENT.EventCallback<T>) =>
			await __TAURI_EVENT.once(name, mapEvent(cb)),
		emit: ((payload: T) =>
			__TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
	};

	const fn = (
		target: import('@tauri-apps/api/webview').Webview | import('@tauri-apps/api/window').Window,
	) => ({
		listen: async (cb: __TAURI_EVENT.EventCallback<T>) =>
			await target.listen(name, mapEvent(cb)),
		once: async (cb: __TAURI_EVENT.EventCallback<T>) => await target.once(name, mapEvent(cb)),
		emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
	});

	return Object.assign(fn, base);
}
