// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**
	 *  Open the chosen provider's authorisation page in an in-app browser,
	 *  complete sign-in, and exchange the device's PKCE verifier for
	 *  session tokens once the redirect fires.
	 * 
	 *  **Flow shape.** The mobile crate generates a fresh PKCE pair locally
	 *  and POSTs the challenge to the backend's `/auth/oauth/mobile/url`
	 *  endpoint. The backend stamps that challenge as the OAuth `state`
	 *  (so it round-trips through Google / GitHub) and returns the provider
	 *  authorisation URL. After the user completes sign-in, the provider
	 *  302s to the backend's `/auth/oauth/{provider}/mobile-callback`,
	 *  which atomically completes login and 302s to
	 *  `eurora://mobile/callback?status=ok|error`. The in-app browser
	 *  captures the redirect; we then redeem the verifier (still in this
	 *  awaiting frame) for our own access / refresh tokens.
	 * 
	 *  **Browser-session sharing.** We deliberately do *not* set
	 *  `prefers_ephemeral_session: true`. Sharing cookies with the system
	 *  browser is what enables the "I'm already signed in" UX users expect:
	 * 
	 *  - "Sign in with Google" recognises the user's existing Google
	 *    session in the system browser and shows the account picker
	 *    instead of prompting for email / password / 2FA;
	 *  - iOS Keychain / Android Autofill and password managers can fill
	 *    saved credentials for our domain;
	 *  - the user's existing session on our own domain (if any) is
	 *    honoured.
	 * 
	 *  The trade-off is that the in-app browser sees whatever is currently
	 *  signed in to the user's system browser — which is exactly what users
	 *  mean when they tap "Sign in with Google". For workflows that
	 *  explicitly need a clean session, the user can sign out in the system
	 *  browser first.
	 */
	authStartLogin: (provider: Provider) => typedError<LoginOutcome, string>(__TAURI_INVOKE("auth_start_login", { provider })),
	/**
	 *  Native Apple sign-in via `tauri-plugin-apple-auth`. On iOS this
	 *  drives `ASAuthorizationController` (the system Apple sheet, FaceID /
	 *  TouchID, no browser); on every other target the plugin returns
	 *  [`AppleSignInOutcome::NativeUnavailable`] and we surface that to the
	 *  frontend so it can fall back to [`auth_start_login`].
	 * 
	 *  Unlike Google, the iOS flow does not need a client ID — the
	 *  `ASAuthorizationAppleIDProvider` request is bound to the iOS Bundle
	 *  ID via the provisioning profile's Sign in with Apple capability.
	 *  The backend's dual-audience verifier accepts both
	 *  `APPLE_SERVICE_ID` (web) and `APPLE_BUNDLE_ID` (native iOS) audiences,
	 *  so the resulting `(provider, sub)` pair lines up with web sign-ins
	 *  of the same Apple ID.
	 */
	authStartLoginAppleNative: () => typedError<LoginOutcome, string>(__TAURI_INVOKE("auth_start_login_apple_native")),
	/**
	 *  Native Google sign-in via `tauri-plugin-google-auth`. On iOS this
	 *  drives the GoogleSignIn SDK (account picker, no browser); on Android
	 *  the Credential Manager API (system bottom sheet). Returns
	 *  [`LoginOutcome::NativeUnavailable`] when the device can't service
	 *  the request — Android without Play Services, or any non-mobile
	 *  platform — so the frontend can fall back to [`auth_start_login`].
	 * 
	 *  We pass the platform-appropriate Google client ID:
	 *  - iOS uses the iOS OAuth client (`GOOGLE_CLIENT_ID_IOS`); the
	 *    resulting JWT carries `aud == GOOGLE_CLIENT_ID_IOS`, which the
	 *    backend accepts via its `accepted_audiences` list.
	 *  - Android Credential Manager only takes the *server* client ID
	 *    (`GOOGLE_CLIENT_ID`); the resulting JWT carries `aud ==
	 *    GOOGLE_CLIENT_ID` so the backend's primary verifier accepts it.
	 */
	authStartLoginGoogleNative: () => typedError<LoginOutcome, string>(__TAURI_INVOKE("auth_start_login_google_native")),
	authLogin: (login: string, password: string) => typedError<null, string>(__TAURI_INVOKE("auth_login", { login, password })),
	authRegister: (email: string, password: string) => typedError<null, string>(__TAURI_INVOKE("auth_register", { email, password })),
	authLogout: () => typedError<null, string>(__TAURI_INVOKE("auth_logout")),
	authIsAuthenticated: () => typedError<boolean, string>(__TAURI_INVOKE("auth_is_authenticated")),
	authGetAccessTokenPayload: () => typedError<Claims, string>(__TAURI_INVOKE("auth_get_access_token_payload")),
	authRefreshSession: () => typedError<null, string>(__TAURI_INVOKE("auth_refresh_session")),
	settingsGetTelemetryConsent: () => __TAURI_INVOKE<TelemetryConsent>("settings_get_telemetry_consent"),
	settingsGetLocalTelemetry: () => __TAURI_INVOKE<TelemetryLocal>("settings_get_local_telemetry"),
	/**
	 *  Persist the user's response to the telemetry consent prompt. Stamps
	 *  the consent version monotonically via
	 *  [`TelemetryConsent::record_for_desktop`], lazily allocates a stable
	 *  `distinct_id`, reapplies the native Sentry guard, emits
	 *  [`ConsentGate`] with `required: false` so the frontend can route
	 *  away from the prompt, and returns the canonical post-stamp consent
	 *  so the frontend's optimistic state stays in sync.
	 */
	settingsRecordTelemetryConsent: (consent: TelemetryConsent) => typedError<TelemetryConsent, SettingsError>(__TAURI_INVOKE("settings_record_telemetry_consent", { consent })),
	systemGetTelemetryBootstrap: () => typedError<TelemetryBootstrap, SystemError>(__TAURI_INVOKE("system_get_telemetry_bootstrap")),
	/**
	 *  Frontend handshake: called from the root layout once event listeners
	 *  are attached. The backend reads the current consent state and emits
	 *  [`ConsentGate`] with `required` set accordingly. See the desktop
	 *  equivalent for the design rationale.
	 */
	frontendReady: () => typedError<null, SystemError>(__TAURI_INVOKE("frontend_ready")),
	systemReinitTelemetry: () => __TAURI_INVOKE<void>("system_reinit_telemetry"),
	systemRotateTelemetryDistinctId: () => typedError<string, SystemError>(__TAURI_INVOKE("system_rotate_telemetry_distinct_id")),
	threadList: (limit: number, offset: number) => typedError<Thread[], ThreadError>(__TAURI_INVOKE("thread_list", { limit, offset })),
	threadListByActivity: (activityId: string, limit: number, offset: number) => typedError<Thread[], ThreadError>(__TAURI_INVOKE("thread_list_by_activity", { activityId, limit, offset })),
	threadCreate: () => typedError<Thread, ThreadError>(__TAURI_INVOKE("thread_create")),
	threadDelete: (threadId: string) => typedError<null, ThreadError>(__TAURI_INVOKE("thread_delete", { threadId })),
	threadGetMessages: (threadId: string, limit: number, offset: number) => typedError<MessageNode[], ThreadError>(__TAURI_INVOKE("thread_get_messages", { threadId, limit, offset })),
	threadSwitchBranch: (threadId: string, messageId: string, direction: number) => typedError<MessageNode[], ThreadError>(__TAURI_INVOKE("thread_switch_branch", { threadId, messageId, direction })),
	threadGenerateTitle: (threadId: string) => typedError<Thread, ThreadError>(__TAURI_INVOKE("thread_generate_title", { threadId })),
	threadSearchThreads: (query: string, limit: number, offset: number) => typedError<SearchThreadResult[], ThreadError>(__TAURI_INVOKE("thread_search_threads", { query, limit, offset })),
	threadSearchMessages: (query: string, limit: number, offset: number) => typedError<SearchMessageResult[], ThreadError>(__TAURI_INVOKE("thread_search_messages", { query, limit, offset })),
	chatCollectContext: (threadId: string) => typedError<ChatContext, StreamError>(__TAURI_INVOKE("chat_collect_context", { threadId })),
	chatSendQuery: (threadId: string, channel: Channel<ChatServerMessage>, request: ChatSendRequest) => typedError<null, StreamError>(__TAURI_INVOKE("chat_send_query", { threadId, channel, request })),
	chatRegenerate: (threadId: string, aiMessageId: string, channel: Channel<ChatServerMessage>) => typedError<null, StreamError>(__TAURI_INVOKE("chat_regenerate", { threadId, aiMessageId, channel })),
	chatCancelQuery: (threadId: string) => typedError<null, StreamError>(__TAURI_INVOKE("chat_cancel_query", { threadId })),
};

/** Events */
export const events = {
	authStateChanged: makeEvent<AuthStateChanged>("auth-state-changed"),
	consentGate: makeEvent<ConsentGate>("consent-gate"),
};

/* Types */
export type AIMessage = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	tool_calls?: ToolCall[],
	invalid_tool_calls?: InvalidToolCall[],
	usage_metadata?: UsageMetadata | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

export type AIMessageChunk = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	tool_calls?: ToolCall[],
	invalid_tool_calls?: InvalidToolCall[],
	tool_call_chunks: ToolCallChunk[],
	usage_metadata?: UsageMetadata | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
	chunk_position?: ChunkPosition | null,
};

export type Annotation = { type: "citation"; id?: string | null; url?: string | null; title?: string | null; start_index?: bigint | null; end_index?: bigint | null; cited_text?: string | null; extras?: { [key in string]: unknown } | null } | { type: "non_standard_annotation"; id?: string | null; value: { [key in string]: unknown } };

/**
 *  Tagged union of every message variant. Wire format is internally tagged on
 *  the `type` field — `{"type": "human", "content": ..., ...}` etc. The inner
 *  per-variant structs (`HumanMessage`, `AIMessage`, ...) deliberately do NOT
 *  carry their own `type` field; the discriminant is added at the union level
 *  and only there. This keeps the Rust types and the specta-generated TS types
 *  in lockstep with the actual JSON shape.
 */
export type AnyMessage = {
	type: "human",
} & HumanMessage | {
	type: "system",
} & SystemMessage | {
	type: "ai",
} & AIMessage | {
	type: "tool",
} & ToolMessage | {
	type: "chat",
} & ChatMessage | {
	type: "remove",
} & RemoveMessage;

export type AudioContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

/**
 *  Backend → frontend auth-state transition. Mirrors the shape of
 *  [`crate::AuthEvent`] for the JS side; `claims == None` means signed out.
 */
export type AuthStateChanged = {
	claims: Claims | null,
};

export type BlockIndex = number | string;

/**
 *  Per-turn host context returned by `chat_collect_context`.
 * 
 *  `content_blocks` are inlined directly — large payloads are rewritten
 *  into asset references server-side at chat-turn time, so the wire
 *  format here can carry raw bytes/text without the client having to
 *  round-trip them.
 */
export type ChatContext = {
	contentBlocks: ContentBlock[],
	assetChips: ContextChip[],
};

export type ChatMessage = {
	content: ContentBlocks,
	role: string,
	id?: string | null,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

/**
 *  Payload of a [`ChatClientMessage::Send`] frame.
 * 
 *  When `parent_message_id` is present the turn is interpreted as an edit of
 *  an existing branch; the service rewinds `active_leaf` accordingly.
 */
export type ChatSendRequest = {
	content_blocks: ContentBlock[],
	parent_message_id?: string | null,
	asset_chips_json?: string | null,
};

/**
 *  Frame sent by the server over the chat WebSocket.
 * 
 *  Clients should accumulate `Chunk` payloads (using agent-chain's chunk-merge
 *  semantics) and replace placeholder state with the `Final.messages` payload
 *  when the turn ends.
 */
export type ChatServerMessage = 
/**  The user's message has been persisted; clients should display it. */
{ type: "confirmed_human_message"; message: MessageNode } | 
/**  One streaming chunk from the AI. */
{ type: "chunk"; chunk: AIMessageChunk } | 
/**
 *  The turn ended successfully; tree positions for everything that was
 *  persisted during this turn (human + AI + any tool messages).
 */
{ type: "final"; messages: MessageNode[] } | 
/**  The turn aborted with an error. The connection is closed after this. */
{ type: "error"; kind: string; message: string };

export type ChunkPosition = "last";

export type Claims = {
	sub: string,
	email: string,
	display_name?: string | null,
	exp: bigint,
	iat: bigint,
	token_type: string,
	role: Role,
	aud?: string,
	email_verified?: boolean,
	/**
	 *  RFC 7519 JWT ID. Guarantees that two tokens minted for
	 *  the same subject within the same second never collide
	 *  after hashing (see refresh-token rotation).
	 */
	jti?: string,
};

/**
 *  Pushed from Rust to the frontend whenever the mobile telemetry
 *  consent gate flips. Fired once during startup (in response to
 *  [`frontend_ready`]) and again whenever the gate changes (e.g. after
 *  [`crate::procedures::settings_procedures::settings_record_telemetry_consent`]).
 * 
 *  Today mobile shares the `desktop.telemetry` cloud record with the
 *  desktop client; Phase 10 partitions mobile into its own section
 *  once a mobile telemetry stack ships.
 */
export type ConsentGate = {
	required: boolean,
};

export type ContentBlock = {
	type: "text",
} & TextContentBlock | {
	type: "invalid_tool_call",
} & InvalidToolCallBlock | {
	type: "reasoning",
} & ReasoningContentBlock | {
	type: "non_standard",
} & NonStandardContentBlock | {
	type: "image",
} & ImageContentBlock | {
	type: "video",
} & VideoContentBlock | {
	type: "audio",
} & AudioContentBlock | {
	type: "text-plain",
} & PlainTextContentBlock | {
	type: "file",
} & FileContentBlock | {
	type: "tool_call",
} & ToolCallBlock | {
	type: "tool_call_chunk",
} & ToolCallChunkBlock | {
	type: "server_tool_call",
} & ServerToolCall | {
	type: "server_tool_call_chunk",
} & ServerToolCallChunk | {
	type: "server_tool_result",
} & ServerToolResult;

export type ContentBlocks = ContentBlock[];

/**
 *  Per-asset context chip surfaced alongside [`ChatContext`] content blocks.
 * 
 *  Lives here (rather than in `euro-activity`) because both desktop and
 *  mobile chat IPC layers emit it: desktop populates it from the timeline,
 *  mobile populates it from native pickers. Keeping the wire shape in
 *  `thread-core` lets the IPC commands stay app-agnostic and avoids
 *  dragging the desktop-only `euro-activity` graph into mobile.
 */
export type ContextChip = {
	id: string,
	name: string,
	icon: string | null,
	domain: string | null,
};

export type FileContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

export type HumanMessage = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

export type ImageContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

export type InputTokenDetails = {
	audio?: bigint | null,
	cache_creation?: bigint | null,
	cache_read?: bigint | null,
} & { [key in string]: bigint };

export type InvalidToolCall = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	error?: string | null,
	type?: string | null,
};

export type InvalidToolCallBlock = {
	id?: string | null,
	name?: string | null,
	args?: string | null,
	error?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type LoginOutcome = { kind: "success" } | { kind: "canceled" } | 
/**
 *  Provider or backend refused the sign-in for a non-cancellation
 *  reason. `reason` is the underlying error category — useful for
 *  surfacing diagnostics, not for branching on the UI side. The
 *  frontend should treat every `rejected` outcome the same.
 */
{ kind: "rejected"; reason: string } | 
/**
 *  Native sign-in is not available on this device (e.g. Android
 *  without Play Services). The frontend should retry via the
 *  in-app browser flow.
 */
{ kind: "native_unavailable" };

/**  One node in the message tree returned by message-list endpoints. */
export type MessageNode = {
	parent_id?: string | null,
	message: AnyMessage,
	children?: MessageNode[],
	sibling_index: number,
	depth: number,
};

export type NonStandardContentBlock = {
	id?: string | null,
	value?: { [key in string]: unknown },
	index?: BlockIndex | null,
};

export type OutputTokenDetails = {
	audio?: bigint | null,
	reasoning?: bigint | null,
} & { [key in string]: bigint };

export type PlainTextContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type: string,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	text?: string | null,
	title?: string | null,
	context?: string | null,
	extras?: { [key in string]: unknown } | null,
};

/**
 *  Third-party identity provider supported by the auth service.
 * 
 *  Wire format is lowercase JSON (`"google"`, `"github"`, `"apple"`)
 *  so it reads naturally in URLs and request bodies.
 */
export type Provider = "google" | "github" | "apple";

export type ReasoningContentBlock = {
	id?: string | null,
	reasoning?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type RemoveMessage = {
	id: string,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

export type Role = "Free" | "Tier1";

/**  One message hit returned by full-text search. */
export type SearchMessageResult = {
	id: string,
	thread_id: string,
	message_type: string,
	rank: number | null,
	created_at: string,
	snippet: string,
};

/**  One thread hit returned by full-text search. */
export type SearchThreadResult = {
	id: string,
	title: string,
	rank: number | null,
	updated_at: string,
};

export type ServerToolCall = {
	id: string,
	name: string,
	args?: { [key in string]: unknown },
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ServerToolCallChunk = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ServerToolResult = {
	id?: string | null,
	tool_call_id: string,
	status: ServerToolStatus,
	output?: unknown | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ServerToolStatus = "success" | "error";

/**
 *  Typed error surface for the `settings_*` IPC commands. Externally
 *  tagged so the JS side gets `{ type: "Persistence", data: "..." }`
 *  and can branch on `type` instead of parsing strings.
 */
export type SettingsError = { type: "Persistence"; data: string };

/**
 *  Typed error surface for the streaming `chat_*` IPC commands.
 *  Externally tagged so the JS side can branch on `error.type`.
 *  `Cancelled` is split out from the rest so the UI can suppress its
 *  own cancel-induced errors instead of showing a toast for them; an
 *  upstream [`crate::Error`] (e.g. a deleted thread mid-stream) is
 *  wrapped in `Thread` so the JS side can drill into the same
 *  [`ThreadError`] variants it handles for CRUD calls.
 */
export type StreamError = { type: "Cancelled" } | { type: "Timeout"; data: number } | { type: "Channel"; data: string } | { type: "StateUnavailable"; data: string } | { type: "Thread"; data: ThreadError };

/**
 *  Typed error surface for the `system_*` IPC commands. Externally
 *  tagged so the JS side gets `{ type: "Persistence", data: "..." }`
 *  and can branch on `type` without parsing strings.
 */
export type SystemError = { type: "Persistence"; data: string };

export type SystemMessage = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

/**
 *  Single payload the mobile frontend fetches once at startup to bring
 *  up its Sentry / PostHog SDKs. Bundles the user's persisted consent,
 *  the local anonymous identifier, the embedded build-time keys, the
 *  release identity, and **precomputed policy decisions** so the
 *  frontend doesn't reproduce the consent-gating rules in TypeScript.
 * 
 *  `None` on any build-time field means "this surface is disabled in
 *  this build". `euro-telemetry/build.rs` enforces all-or-nothing
 *  consistency: a build with a DSN always carries a channel and a
 *  release, so the frontend never has to defend against a
 *  half-configured payload.
 */
export type TelemetryBootstrap = {
	consent: TelemetryConsent,
	distinctId: string | null,
	sentryDsn: string | null,
	posthogKey: string | null,
	posthogHost: string | null,
	channel: string | null,
	release: string | null,
	allowsErrors: boolean,
	allowsMetrics: boolean,
	allowsIdentification: boolean,
};

/**
 *  Per-platform telemetry consent record. Lives under each platform
 *  section of [`crate::CloudSettings`] — never under
 *  [`crate::SharedSettings`] — because consent must be specific to the
 *  data actually collected, and each platform ships a different
 *  telemetry stack (Sentry + PostHog on desktop, platform-native SDKs
 *  on mobile, etc.). A user agreeing on desktop has not seen, and
 *  cannot legally cover, what mobile or web will collect.
 * 
 *  `distinct_id` is intentionally absent — it is an anonymous
 *  per-install identifier whose rotation must break cross-device
 *  linkage, and so stays in the platform's local file rather than
 *  crossing the wire.
 * 
 *  ## `consent_version` semantics
 * 
 *  `consent_version` records the schema version of the consent prompt
 *  the user agreed to *on this platform*.
 * 
 *  - `0` (the `Default`) means the user has **never** seen the prompt.
 *  - Any value `>= DESKTOP_CONSENT_VERSION` (or the analogue for other
 *    platforms) means the user has consented to the current schema.
 *  - A value between `1` and `current - 1` means the user consented to
 *    an older prompt; the client must re-prompt.
 * 
 *  The value is **monotonically non-decreasing** by contract. The only
 *  writer is the platform's consent procedure, which uses
 *  [`Self::record_for_desktop`] (analogous methods for other platforms
 *  will land when those clients ship). Regular settings-page saves
 *  must *not* touch this field; the IPC layer enforces this by
 *  clamping incoming values against the stored version.
 */
export type TelemetryConsent = {
	consentVersion?: number,
	anonymousMetrics?: boolean,
	anonymousErrors?: boolean,
	nonAnonymousMetrics?: boolean,
} & { [key in string]: unknown };

/**
 *  Local-only telemetry state. Persisted next to the rest of
 *  [`crate::LocalSettings`] in `local.json`; never crosses the wire to
 *  the cloud-sync backend.
 */
export type TelemetryLocal = {
	/**
	 *  Anonymous per-install identifier. `None` until the user accepts
	 *  telemetry for the first time, then a fresh UUID v4 that survives
	 *  until the user explicitly rotates it.
	 */
	distinctId?: string | null,
};

export type TextContentBlock = {
	id?: string | null,
	text: string,
	annotations?: Annotation[] | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

/**  A persisted thread row as returned to the client. */
export type Thread = {
	id: string,
	user_id: string,
	title: string,
	created_at: string,
	updated_at: string,
	active_leaf_id?: string | null,
};

/**
 *  Typed error surface for the CRUD/search `thread_*` IPC commands.
 *  Externally tagged so the JS side can branch on `error.type` without
 *  parsing strings. `NotFound` lifts [`crate::Error::ThreadNotFound`] to
 *  a dedicated variant so the UI can render an empty state instead of a
 *  generic toast.
 */
export type ThreadError = { type: "NotFound" } | { type: "Backend"; data: string } | { type: "BadResponse"; data: string } | { type: "StateUnavailable"; data: string } | { type: "Internal"; data: string };

export type ToolCall = {
	id?: string | null,
	name: string,
	/**
	 *  Always a JSON object on the wire. The struct-side type stays
	 *  `serde_json::Value` for ergonomic constructor input, but the specta-
	 *  generated TS type is `Record<string, unknown>` to reflect that.
	 */
	args: { [key in string]: unknown },
	type?: string | null,
};

export type ToolCallBlock = {
	id?: string | null,
	name: string,
	args?: { [key in string]: unknown },
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ToolCallChunk = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	index?: number | null,
	type?: string | null,
};

export type ToolCallChunkBlock = {
	id?: string | null,
	name?: string | null,
	args?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ToolMessage = {
	content: ContentBlocks,
	tool_call_id: string,
	id?: string | null,
	name?: string | null,
	status?: ToolStatus,
	artifact?: unknown | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

export type ToolStatus = "success" | "error";

export type UsageMetadata = {
	input_tokens: bigint,
	output_tokens: bigint,
	total_tokens: bigint,
	input_token_details?: InputTokenDetails | null,
	output_token_details?: OutputTokenDetails | null,
};

export type VideoContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

