[package]
name = "eur-eurora-provider"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
ferrous-llm-core = { version = "0.5.0", features = ["dynamic-image"] }
thiserror = "2.0.12"
tokio = { workspace = true }
tokio-stream = { workspace = true }
async-trait = "0.1.77"
url = "2.5.1"
tonic = { workspace = true, features = ["tls-native-roots", "channel"] }
futures = { workspace = true }
prost = { workspace = true }
chrono = { workspace = true }
prost-types = { workspace = true }
async-stream = "0.3.1"
image = { workspace = true }
eur-secret = { workspace = true }
eur-user = { workspace = true }
tonic-prost = { workspace = true }
tracing = { workspace = true }
base64 = { workspace = true }
tonic-async-interceptor = "0.14.1"
tower = "0.5.2"

[build-dependencies]
tonic-prost-build = { workspace = true }
