// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


export type ContextChip = { id: string; extension_id: string; name: string; attrs: Partial<{ [key in string]: string }>; icon: string | null; position: number | null }

export type LoginToken = { code_challenge: string; expires_in: bigint; url: string }

export type Query = { text: string; assets: string[] }

export type ResponseChunk = { chunk: string }

const ARGS_MAP = { 'window':'{"resize_launcher_window":["height","scale_factor"],"get_scale_factor":["height"]}', 'context_chip':'{"get":[]}', '':'{"send_query":["channel","query"]}', 'third_party':'{"save_api_key":["api_key"],"check_api_key_exists":[],"initialize_openai_client":[]}', 'monitor':'{"capture_monitor":["monitor_name"]}', 'auth':'{"poll_for_login":[],"get_login_token":[]}' }
export type Router = { 'window': { get_scale_factor: (height: number) => Promise<number>, 
resize_launcher_window: (height: number, scaleFactor: number) => Promise<null> },
'monitor': { capture_monitor: (monitorName: string) => Promise<string> },
'': { send_query: (channel: TAURI_CHANNEL<ResponseChunk>, query: Query) => Promise<string> },
'context_chip': { get: () => Promise<ContextChip[]> },
'third_party': { check_api_key_exists: () => Promise<boolean>, 
save_api_key: (apiKey: string) => Promise<null>, 
initialize_openai_client: () => Promise<boolean> },
'auth': { poll_for_login: () => Promise<boolean>, 
get_login_token: () => Promise<LoginToken> } };


export type { InferCommandOutput }
export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
