// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	authGetLoginToken: () => typedError<LoginToken, AuthError>(__TAURI_INVOKE("auth_get_login_token")),
	authPollForLogin: () => typedError<boolean, AuthError>(__TAURI_INVOKE("auth_poll_for_login")),
	authRegister: (email: string, password: string) => typedError<null, AuthError>(__TAURI_INVOKE("auth_register", { email, password })),
	authLogin: (login: string, password: string) => typedError<null, AuthError>(__TAURI_INVOKE("auth_login", { login, password })),
	authLogout: () => typedError<null, AuthError>(__TAURI_INVOKE("auth_logout")),
	authIsAuthenticated: () => typedError<boolean, AuthError>(__TAURI_INVOKE("auth_is_authenticated")),
	authGetAccessTokenPayload: () => typedError<Claims, AuthError>(__TAURI_INVOKE("auth_get_access_token_payload")),
	authRefreshSession: () => typedError<null, AuthError>(__TAURI_INVOKE("auth_refresh_session")),
	authResendVerificationEmail: () => typedError<null, AuthError>(__TAURI_INVOKE("auth_resend_verification_email")),
	chatCollectContext: (threadId: string) => typedError<ChatContext, StreamError>(__TAURI_INVOKE("chat_collect_context", { threadId })),
	chatSendQuery: (threadId: string, channel: Channel<ChatServerMessage>, request: ChatSendRequest) => typedError<null, StreamError>(__TAURI_INVOKE("chat_send_query", { threadId, channel, request })),
	chatRegenerate: (threadId: string, aiMessageId: string, channel: Channel<ChatServerMessage>) => typedError<null, StreamError>(__TAURI_INVOKE("chat_regenerate", { threadId, aiMessageId, channel })),
	chatCancelQuery: (threadId: string) => typedError<null, StreamError>(__TAURI_INVOKE("chat_cancel_query", { threadId })),
	paymentCreateCheckoutUrl: () => typedError<string, PaymentError>(__TAURI_INVOKE("payment_create_checkout_url")),
	paymentIsSubscribed: () => typedError<boolean, PaymentError>(__TAURI_INVOKE("payment_is_subscribed")),
	settingsGetGeneral: () => __TAURI_INVOKE<GeneralSettings>("settings_get_general"),
	settingsSetGeneral: (generalSettings: GeneralSettings) => typedError<GeneralSettings, SettingsError>(__TAURI_INVOKE("settings_set_general", { generalSettings })),
	settingsGetApi: () => __TAURI_INVOKE<APISettings>("settings_get_api"),
	settingsSetApi: (apiSettings: APISettings) => typedError<APISettings, SettingsError>(__TAURI_INVOKE("settings_set_api", { apiSettings })),
	settingsGetShared: () => __TAURI_INVOKE<SharedSettings>("settings_get_shared"),
	settingsSetShared: (shared: SharedSettings) => typedError<SharedSettings, SettingsError>(__TAURI_INVOKE("settings_set_shared", { shared })),
	settingsGetDesktop: () => __TAURI_INVOKE<DesktopSettings>("settings_get_desktop"),
	/**
	 *  Write the entire desktop section. The frontend's appearance and
	 *  telemetry pages each operate on a subset of fields; both target this
	 *  one command, so a partial-section write is achieved by reading the
	 *  current section, patching the relevant fields, and writing the whole
	 *  thing back.
	 * 
	 *  Side effects: clamps scales via [`DesktopSettings::sanitize`], stamps
	 *  `telemetry.consent_version` to the current build's value, lazily
	 *  allocates a local `distinct_id`, and reapplies the native Sentry
	 *  guard to match the new consent decision.
	 */
	settingsSetDesktop: (desktop: DesktopSettings) => typedError<DesktopSettings, SettingsError>(__TAURI_INVOKE("settings_set_desktop", { desktop })),
	/**
	 *  Returns the per-install telemetry state — currently just the
	 *  anonymous distinct id. The cross-device consent toggles live under
	 *  the cloud `desktop` section and are surfaced via
	 *  [`settings_get_desktop`].
	 */
	settingsGetLocalTelemetry: () => __TAURI_INVOKE<TelemetryLocal>("settings_get_local_telemetry"),
	/**
	 *  Convenience read for the early-boot / pre-auth path where the
	 *  frontend needs only the consent toggles. Equivalent to
	 *  `settings_get_desktop().telemetry`, but typed so the IPC surface
	 *  documents that *only* the consent block crosses this boundary.
	 */
	settingsGetTelemetryConsent: () => __TAURI_INVOKE<TelemetryConsent>("settings_get_telemetry_consent"),
	systemCheckBackendConnection: (serverAddress: string | null) => typedError<string, SystemError>(__TAURI_INVOKE("system_check_backend_connection", { serverAddress })),
	systemGetLlmInfo: () => typedError<RedactedLlmConfig, SystemError>(__TAURI_INVOKE("system_get_llm_info")),
	/**
	 *  Probe an arbitrary URL by hitting /llm/info — used by the connection
	 *  picker's "Test connection" button before persisting the URL.
	 */
	systemTestBackendUrl: (url: string) => typedError<RedactedLlmConfig, SystemError>(__TAURI_INVOKE("system_test_backend_url", { url })),
	/**
	 *  The backend URL the desktop binary was built against. Surfaced to
	 *  the frontend so the connection picker can show what `Default` mode
	 *  resolves to — the value differs per release (dev builds point at
	 *  localhost, end-user binaries at the shipping organisation's hosted
	 *  backend).
	 */
	systemGetDefaultBackendUrl: () => __TAURI_INVOKE<string>("system_get_default_backend_url"),
	systemListActivities: () => typedError<ContextChip[], SystemError>(__TAURI_INVOKE("system_list_activities")),
	systemCheckForUpdate: () => typedError<{
	version: string,
	body: string | null,
} | null, SystemError>(__TAURI_INVOKE("system_check_for_update")),
	systemInstallUpdate: () => typedError<null, SystemError>(__TAURI_INVOKE("system_install_update")),
	systemQuit: () => __TAURI_INVOKE<void>("system_quit"),
	systemCheckAccessibilityPermission: () => __TAURI_INVOKE<boolean>("system_check_accessibility_permission"),
	systemRequestAccessibilityPermission: () => __TAURI_INVOKE<void>("system_request_accessibility_permission"),
	systemGetBrowserExtensionState: (processName: string) => __TAURI_INVOKE<BrowserExtensionState>("system_get_browser_extension_state", { processName }),
	systemOpenBrowserExtensionSettings: (processName: string) => typedError<null, SystemError>(__TAURI_INVOKE("system_open_browser_extension_settings", { processName })),
	systemOpenUrlInBrowser: (processId: number, url: string) => typedError<null, SystemError>(__TAURI_INVOKE("system_open_url_in_browser", { processId, url })),
	systemFocusMainWindow: () => typedError<null, SystemError>(__TAURI_INVOKE("system_focus_main_window")),
	systemGetTelemetryBootstrap: () => typedError<TelemetryBootstrap, SystemError>(__TAURI_INVOKE("system_get_telemetry_bootstrap")),
	systemNeedsTelemetryConsent: () => __TAURI_INVOKE<boolean>("system_needs_telemetry_consent"),
	systemReinitTelemetry: () => __TAURI_INVOKE<void>("system_reinit_telemetry"),
	systemRotateTelemetryDistinctId: () => typedError<string, SystemError>(__TAURI_INVOKE("system_rotate_telemetry_distinct_id")),
	threadList: (limit: number, offset: number) => typedError<Thread[], ThreadError>(__TAURI_INVOKE("thread_list", { limit, offset })),
	threadCreate: () => typedError<Thread, ThreadError>(__TAURI_INVOKE("thread_create")),
	threadDelete: (threadId: string) => typedError<null, ThreadError>(__TAURI_INVOKE("thread_delete", { threadId })),
	threadGetMessages: (threadId: string, limit: number, offset: number) => typedError<MessageNode[], ThreadError>(__TAURI_INVOKE("thread_get_messages", { threadId, limit, offset })),
	threadSwitchBranch: (threadId: string, messageId: string, direction: number) => typedError<MessageNode[], ThreadError>(__TAURI_INVOKE("thread_switch_branch", { threadId, messageId, direction })),
	threadGenerateTitle: (threadId: string) => typedError<Thread, ThreadError>(__TAURI_INVOKE("thread_generate_title", { threadId })),
	threadSearchThreads: (query: string, limit: number, offset: number) => typedError<SearchThreadResult[], ThreadError>(__TAURI_INVOKE("thread_search_threads", { query, limit, offset })),
	threadSearchMessages: (query: string, limit: number, offset: number) => typedError<SearchMessageResult[], ThreadError>(__TAURI_INVOKE("thread_search_messages", { query, limit, offset })),
};

/** Events */
export const events = {
	authStateChanged: makeEvent<AuthStateChanged>("auth-state-changed"),
	browserExtensionStatusChanged: makeEvent<BrowserExtensionStatusChanged>("browser-extension-status-changed"),
	timelineAppEvent: makeEvent<TimelineAppEvent>("timeline-app-event"),
	timelineAssetsEvent: makeEvent<TimelineAssetsEvent>("timeline-assets-event"),
};

/* Types */
export type AIMessage = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	tool_calls?: ToolCall[],
	invalid_tool_calls?: InvalidToolCall[],
	usage_metadata?: UsageMetadata | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

export type AIMessageChunk = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	tool_calls?: ToolCall[],
	invalid_tool_calls?: InvalidToolCall[],
	tool_call_chunks: ToolCallChunk[],
	usage_metadata?: UsageMetadata | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
	chunk_position?: ChunkPosition | null,
};

export type APISettings = {
	mode: ConnectionMode,
};

export type AccentColor = {
	/**  Dominant color in CSS form: lowercase `#rrggbb`. */
	hex: string,
	/**
	 *  Text/foreground color (`#000000` or `#ffffff`) chosen via WCAG relative
	 *  luminance. Use for text rendered on top of `hex`.
	 */
	onHex: string,
	/**
	 *  Icon-background color (`#000000` or `#ffffff`) chosen via NTSC
	 *  perceived brightness. Use for shapes that visually contrast with `hex`.
	 */
	iconBg: string,
};

export type Annotation = { type: "citation"; id?: string | null; url?: string | null; title?: string | null; start_index?: bigint | null; end_index?: bigint | null; cited_text?: string | null; extras?: { [key in string]: unknown } | null } | { type: "non_standard_annotation"; id?: string | null; value: { [key in string]: unknown } };

/**
 *  Tagged union of every message variant. Wire format is internally tagged on
 *  the `type` field — `{"type": "human", "content": ..., ...}` etc. The inner
 *  per-variant structs (`HumanMessage`, `AIMessage`, ...) deliberately do NOT
 *  carry their own `type` field; the discriminant is added at the union level
 *  and only there. This keeps the Rust types and the specta-generated TS types
 *  in lockstep with the actual JSON shape.
 */
export type AnyMessage = {
	type: "human",
} & HumanMessage | {
	type: "system",
} & SystemMessage | {
	type: "ai",
} & AIMessage | {
	type: "tool",
} & ToolMessage | {
	type: "chat",
} & ChatMessage | {
	type: "remove",
} & RemoveMessage;

export type AudioContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

/**
 *  Typed error surface for the `auth_*` IPC commands. Externally tagged
 *  so the JS side gets `{ type: "NotAuthenticated" }` and can branch on
 *  the variant. The split between `NotAuthenticated` (the user must sign
 *  in again) and `Backend` (transient — local credentials are intact)
 *  matches `euro_auth::AuthError::is_logged_out` / `is_transient`, so
 *  the UI can decide whether to bounce the user to the login screen or
 *  just toast and retry.
 */
export type AuthError = { type: "NotAuthenticated" } | { type: "Backend"; data: string } | { type: "LoginTokenExpired" } | { type: "Config"; data: string } | { type: "Persistence"; data: string } | { type: "StateUnavailable"; data: string } | { type: "Internal"; data: string };

export type AuthStateChanged = {
	claims: Claims | null,
};

export type BlockIndex = number | string;

/**
 *  What the desktop frontend should render for a given browser when its
 *  Eurora extension isn't currently driving messages back to the app.
 * 
 *  Resolution combines two signals — whether a native messenger is
 *  registered on the bridge for that browser, and (for browsers whose
 *  extension ships bundled with a host app) the latest
 *  [`BundledExtensionState`] the host has published. The variants are
 *  ordered from "everything works" to "we don't recognize this process".
 * 
 *  Snake-case Specta tags so the externally-tagged JSON matches what the
 *  existing TS bindings file consumes for tagged unions elsewhere in the
 *  app (`{ "kind": "not_installed", "install_url": "…" }`).
 */
export type BrowserExtensionState = 
/**
 *  Extension is connected to the bridge. The frontend should render
 *  no install affordance for this browser.
 */
{ kind: "connected" } | 
/**
 *  No client is registered for this browser, but the extension is
 *  distributed via a public store. The frontend should offer to open
 *  `install_url` in the focused browser.
 */
{ kind: "not_installed"; install_url: string } | 
/**
 *  The extension is installed but the user has it disabled in the
 *  browser's settings. Bundled browsers (Safari) only — there is no
 *  API to flip this state programmatically, so the frontend should
 *  deep-link the user into the relevant settings page.
 */
{ kind: "disabled" } | 
/**
 *  The browser has no record of the bundled extension. Typically
 *  means the host app has never been launched on this machine.
 */
{ kind: "not_discovered" } | 
/**
 *  We can't determine the extension's state right now. The frontend
 *  should hide the affordance entirely rather than showing stale or
 *  misleading guidance.
 */
{ kind: "unknown" } | 
/**
 *  Process name doesn't match any browser Eurora knows about. The
 *  frontend should hide the affordance.
 */
{ kind: "unsupported" };

/**
 *  Push event fired whenever a browser's extension state transitions —
 *  a native messenger registers/disconnects, or a bundled host publishes
 *  a fresh state. The frontend uses this to update the install
 *  affordance without polling.
 */
export type BrowserExtensionStatusChanged = {
	process_name: string,
	state: BrowserExtensionState,
};

/**
 *  Per-turn host context returned by `chat_collect_context`.
 * 
 *  `content_blocks` are inlined directly — large payloads are rewritten
 *  into asset references server-side at chat-turn time, so the wire
 *  format here can carry raw bytes/text without the client having to
 *  round-trip them.
 */
export type ChatContext = {
	contentBlocks: ContentBlock[],
	assetChips: ContextChip[],
};

export type ChatMessage = {
	content: ContentBlocks,
	role: string,
	id?: string | null,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

/**
 *  Payload of a [`ChatClientMessage::Send`] frame.
 * 
 *  When `parent_message_id` is present the turn is interpreted as an edit of
 *  an existing branch; the service rewinds `active_leaf` accordingly.
 */
export type ChatSendRequest = {
	content_blocks: ContentBlock[],
	parent_message_id?: string | null,
	asset_chips_json?: string | null,
};

/**
 *  Frame sent by the server over the chat WebSocket.
 * 
 *  Clients should accumulate `Chunk` payloads (using agent-chain's chunk-merge
 *  semantics) and replace placeholder state with the `Final.messages` payload
 *  when the turn ends.
 */
export type ChatServerMessage = 
/**  The user's message has been persisted; clients should display it. */
{ type: "confirmed_human_message"; message: MessageNode } | 
/**  One streaming chunk from the AI. */
{ type: "chunk"; chunk: AIMessageChunk } | 
/**
 *  The turn ended successfully; tree positions for everything that was
 *  persisted during this turn (human + AI + any tool messages).
 */
{ type: "final"; messages: MessageNode[] } | 
/**  The turn aborted with an error. The connection is closed after this. */
{ type: "error"; kind: string; message: string };

export type ChunkPosition = "last";

export type Claims = {
	sub: string,
	email: string,
	display_name?: string | null,
	exp: bigint,
	iat: bigint,
	token_type: string,
	role: Role,
	aud?: string,
	email_verified?: boolean,
	/**
	 *  RFC 7519 JWT ID. Guarantees that two tokens minted for
	 *  the same subject within the same second never collide
	 *  after hashing (see refresh-token rotation).
	 */
	jti?: string,
};

/**
 *  Where the desktop app should send authenticated requests.
 * 
 *  `Default` carries no parameters because its URL is baked in, which
 *  keeps "I want to talk to the URL this binary was built against"
 *  expressible as a stable enum value rather than a magic string.
 *  `Custom` covers everything else (self-hosted homelab, a colleague's
 *  tunnel, a different organisation's infrastructure).
 */
export type ConnectionMode = { kind: "default" } | { kind: "custom"; url: string };

export type ContentBlock = {
	type: "text",
} & TextContentBlock | {
	type: "invalid_tool_call",
} & InvalidToolCallBlock | {
	type: "reasoning",
} & ReasoningContentBlock | {
	type: "non_standard",
} & NonStandardContentBlock | {
	type: "image",
} & ImageContentBlock | {
	type: "video",
} & VideoContentBlock | {
	type: "audio",
} & AudioContentBlock | {
	type: "text-plain",
} & PlainTextContentBlock | {
	type: "file",
} & FileContentBlock | {
	type: "tool_call",
} & ToolCallBlock | {
	type: "tool_call_chunk",
} & ToolCallChunkBlock | {
	type: "server_tool_call",
} & ServerToolCall | {
	type: "server_tool_call_chunk",
} & ServerToolCallChunk | {
	type: "server_tool_result",
} & ServerToolResult;

export type ContentBlocks = ContentBlock[];

/**
 *  Per-asset context chip surfaced alongside [`ChatContext`] content blocks.
 * 
 *  Lives here (rather than in `euro-activity`) because both desktop and
 *  mobile chat IPC layers emit it: desktop populates it from the timeline,
 *  mobile populates it from native pickers. Keeping the wire shape in
 *  `thread-core` lets the IPC commands stay app-agnostic and avoids
 *  dragging the desktop-only `euro-activity` graph into mobile.
 */
export type ContextChip = {
	id: string,
	name: string,
	icon: string | null,
	domain: string | null,
};

/**
 *  Desktop-only cloud-synced settings. Mobile and web each have their
 *  own platform sections to keep concepts that don't translate (window
 *  chrome scaling, telemetry SDKs that don't run on the other
 *  platforms) cleanly partitioned.
 * 
 *  The custom `Default` impl here is the *wire fallback* used by
 *  `#[serde(default)]` when a partial blob is read off the network.
 *  Scales default to [`DEFAULT_SCALE`] rather than the derive-default
 *  `0.0` because a zero-size UI is unrecoverable; an inert sensible
 *  value is the only safe fallback. The product-blessed fresh-install
 *  values live in `assets/defaults.jsonc` and are reached through
 *  [`crate::CloudSettings::default()`].
 */
export type DesktopSettings = {
	/**
	 *  Multiplier applied to the document's root font-size, scaling every
	 *  rem-anchored design token (text, spacing, controls) together.
	 */
	interfaceScale?: number | null,
	/**
	 *  Additional multiplier layered on top of `interface_scale` that
	 *  affects only typography utilities, leaving spacing and control
	 *  sizes alone.
	 */
	textScale?: number | null,
	/**
	 *  Desktop-scoped telemetry consent. Covers what the desktop
	 *  client collects (Sentry, PostHog) and nothing else; mobile and
	 *  web each carry their own record because consent must be
	 *  specific to the data actually collected.
	 */
	telemetry?: TelemetryConsent,
} & { [key in string]: unknown };

export type FileContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

export type GeneralSettings = {
	autostart: boolean,
};

export type HumanMessage = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

export type ImageContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

export type InputTokenDetails = {
	audio?: bigint | null,
	cache_creation?: bigint | null,
	cache_read?: bigint | null,
} & { [key in string]: bigint };

export type InvalidToolCall = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	error?: string | null,
	type?: string | null,
};

export type InvalidToolCallBlock = {
	id?: string | null,
	name?: string | null,
	args?: string | null,
	error?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type LoginToken = {
	code_challenge: string,
	/**
	 *  Seconds remaining until the login challenge expires. `u32` so the TS
	 *  bindings stay on plain `number` — twenty-minute TTLs fit trivially
	 *  and there's no scenario where this needs more than 32 bits.
	 */
	expires_in: number,
	url: string,
};

/**  One node in the message tree returned by message-list endpoints. */
export type MessageNode = {
	parent_id?: string | null,
	message: AnyMessage,
	children?: MessageNode[],
	sibling_index: number,
	depth: number,
};

/**  Pointer to a model owned by a specific provider. */
export type ModelRef = {
	provider: string,
	model: string,
};

export type NonStandardContentBlock = {
	id?: string | null,
	value?: { [key in string]: unknown },
	index?: BlockIndex | null,
};

export type OutputTokenDetails = {
	audio?: bigint | null,
	reasoning?: bigint | null,
} & { [key in string]: bigint };

/**
 *  Typed error surface for the `payment_*` IPC commands. Externally
 *  tagged so the JS side can branch on `error.type`. `Auth` re-uses the
 *  auth surface so the same "session expired" handler in the frontend
 *  catches both auth-touching commands and payment-touching commands
 *  without a parallel mapping.
 */
export type PaymentError = { type: "Auth"; data: AuthError } | { type: "Backend"; data: string } | { type: "BadResponse"; data: string };

export type PlainTextContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type: string,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	text?: string | null,
	title?: string | null,
	context?: string | null,
	extras?: { [key in string]: unknown } | null,
};

export type ReasoningContentBlock = {
	id?: string | null,
	reasoning?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type RedactedAwsCreds = { kind: "default" } | { kind: "static"; access_key_id: string };

export type RedactedGoogleCreds = { kind: "api_key"; has_key: boolean } | { kind: "service_account"; path: string };

/**
 *  View of [`LlmConfig`] safe to serialise across the wire and into logs.
 * 
 *  Mirrors the shape of [`LlmConfig`] but replaces every secret-bearing field
 *  with a boolean flag indicating whether a value is present. Consumers
 *  (e.g. the desktop app's connection panel) can show "you're connected to
 *  OpenAI / gpt-4o-mini" without ever seeing the API key.
 */
export type RedactedLlmConfig = {
	providers: { [key in string]: RedactedProvider },
	roles: Roles,
};

export type RedactedProvider = { kind: "openai"; has_api_key: boolean; base_url: string | null; organization: string | null } | { kind: "anthropic"; has_api_key: boolean; base_url: string | null } | { kind: "google"; credentials: RedactedGoogleCreds; project: string | null } | { kind: "bedrock"; region: string; credentials: RedactedAwsCreds } | { kind: "openai_compatible"; base_url: string; has_api_key: boolean; header_names: string[]; has_overrides: boolean };

export type RemoveMessage = {
	id: string,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

export type Role = "Free" | "Tier1";

/**
 *  Per-role model assignments. `chat` and `title` are mandatory; `vision` is
 *  only required when the deployment expects to handle image-bearing
 *  messages.
 */
export type Roles = {
	chat: ModelRef,
	title: ModelRef,
	vision: ModelRef | null,
};

/**  One message hit returned by full-text search. */
export type SearchMessageResult = {
	id: string,
	thread_id: string,
	message_type: string,
	rank: number | null,
	created_at: string,
	snippet: string,
};

/**  One thread hit returned by full-text search. */
export type SearchThreadResult = {
	id: string,
	title: string,
	rank: number | null,
	updated_at: string,
};

export type ServerToolCall = {
	id: string,
	name: string,
	args?: { [key in string]: unknown },
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ServerToolCallChunk = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ServerToolResult = {
	id?: string | null,
	tool_call_id: string,
	status: ServerToolStatus,
	output?: unknown | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ServerToolStatus = "success" | "error";

/**
 *  Typed error surface for the `settings_*` IPC commands. Externally
 *  tagged so the JS side gets `{ type: "Persistence", data: "..." }`
 *  and can branch on `type` instead of parsing strings. Variants are
 *  grouped by failure mode rather than by command, since several
 *  commands share `Persistence` (any setter that hits the on-disk
 *  settings files).
 */
export type SettingsError = { type: "Persistence"; data: string } | { type: "EndpointSwitch"; data: string };

/**
 *  Cross-platform cloud-synced settings. Anything in this section
 *  applies identically on desktop, mobile, and web; per-platform
 *  concepts live in the platform sections of [`crate::CloudSettings`].
 * 
 *  Telemetry consent is deliberately *not* here: each platform ships
 *  a different telemetry stack and so collects different categories
 *  of data, which means consent has to be platform-specific (see
 *  [`crate::TelemetryConsent`]).
 */
export type SharedSettings = {
	theme?: ThemePreference,
	dynamicAccent?: boolean,
} & { [key in string]: unknown };

/**
 *  Typed error surface for the streaming `chat_*` IPC commands.
 *  Externally tagged so the JS side can branch on `error.type`.
 *  `Cancelled` is split out from the rest so the UI can suppress its
 *  own cancel-induced errors instead of showing a toast for them; an
 *  upstream [`crate::Error`] (e.g. a deleted thread mid-stream) is
 *  wrapped in `Thread` so the JS side can drill into the same
 *  [`ThreadError`] variants it handles for CRUD calls.
 */
export type StreamError = { type: "Cancelled" } | { type: "Timeout"; data: number } | { type: "Channel"; data: string } | { type: "StateUnavailable"; data: string } | { type: "Thread"; data: ThreadError };

/**
 *  Typed error surface for the `system_*` IPC commands. Externally tagged
 *  so the JS side gets `{ type: "BackendUnreachable", data: "..." }` and
 *  can branch on `type` without parsing strings. Variants are grouped by
 *  failure mode rather than by command, since several commands share a
 *  failure mode (e.g. anything that touches the LLM endpoint can hit
 *  `BackendUnreachable` / `BadResponse`).
 */
export type SystemError = { type: "BackendUnreachable"; data: string } | { type: "InvalidUrl"; data: string } | { type: "BadResponse"; data: string } | { type: "Updater"; data: string } | { type: "NoUpdateAvailable" } | { type: "UnsupportedBrowser"; data: string } | { type: "Bridge"; data: string } | { type: "StateUnavailable"; data: string } | { type: "Persistence"; data: string } | { type: "Window"; data: string };

export type SystemMessage = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

/**
 *  Single payload the desktop frontend fetches once at startup to bring
 *  up its Sentry / PostHog SDKs. Bundles the user's persisted consent
 *  state, the local anonymous identifier, the embedded build-time keys,
 *  and the release identity so the SDKs can tag events with channel +
 *  version.
 * 
 *  `None` on any field means "this surface is disabled in this build".
 *  `build.rs` enforces all-or-nothing consistency: a build with a DSN
 *  always carries a channel and a release, so the frontend never has
 *  to defend against a half-configured payload.
 */
export type TelemetryBootstrap = {
	consent: TelemetryConsent,
	distinctId: string | null,
	sentryDsn: string | null,
	posthogKey: string | null,
	posthogHost: string | null,
	channel: string | null,
	release: string | null,
};

/**
 *  Per-platform telemetry consent record. Lives under each platform
 *  section of [`crate::CloudSettings`] — never under `SharedSettings` —
 *  because consent must be specific to the data actually collected,
 *  and each platform ships a different telemetry stack (Sentry +
 *  PostHog on desktop, platform-native SDKs on mobile, etc.). A user
 *  agreeing on desktop has not seen, and cannot legally cover, what
 *  mobile or web will collect.
 * 
 *  `distinct_id` is intentionally absent — it is an anonymous
 *  per-install identifier whose rotation must break cross-device
 *  linkage, and so stays in the platform's local file rather than
 *  crossing the wire.
 * 
 *  `consent_version` records the schema version of the consent prompt
 *  the user agreed to *on this platform*. Bumping
 *  `CURRENT_CONSENT_VERSION` in the client forces a re-prompt; because
 *  the record is per-platform, the bump propagates independently to
 *  each device.
 * 
 *  The derived `Default` here is the *wire fallback* used by
 *  `#[serde(default)]` when a partial blob is read off the network
 *  (every field collapses to `false` / `0` — the inert choice). The
 *  product-blessed fresh-install values live in `assets/defaults.jsonc`
 *  and are reached through [`crate::CloudSettings::default()`].
 */
export type TelemetryConsent = {
	consentVersion?: number,
	anonymousMetrics?: boolean,
	anonymousErrors?: boolean,
	nonAnonymousMetrics?: boolean,
} & { [key in string]: unknown };

/**
 *  Local-only telemetry state. Persisted next to the rest of
 *  [`crate::LocalSettings`] in `local.json`; never crosses the wire to
 *  the cloud-sync backend.
 */
export type TelemetryLocal = {
	/**
	 *  Anonymous per-install identifier. `None` until the user accepts
	 *  telemetry for the first time, then a fresh UUID v4 that survives
	 *  until the user explicitly rotates it.
	 */
	distinctId?: string | null,
};

export type TextContentBlock = {
	id?: string | null,
	text: string,
	annotations?: Annotation[] | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

/**
 *  User's preferred colour scheme. `System` defers to the OS-level
 *  setting; `Light` / `Dark` pin it explicitly across devices.
 */
export type ThemePreference = "system" | "light" | "dark";

/**  A persisted thread row as returned to the client. */
export type Thread = {
	id: string,
	user_id: string,
	title: string,
	created_at: string,
	updated_at: string,
	active_leaf_id?: string | null,
};

/**
 *  Typed error surface for the CRUD/search `thread_*` IPC commands.
 *  Externally tagged so the JS side can branch on `error.type` without
 *  parsing strings. `NotFound` lifts [`crate::Error::ThreadNotFound`] to
 *  a dedicated variant so the UI can render an empty state instead of a
 *  generic toast.
 */
export type ThreadError = { type: "NotFound" } | { type: "Backend"; data: string } | { type: "BadResponse"; data: string } | { type: "StateUnavailable"; data: string } | { type: "Internal"; data: string };

export type TimelineAppEvent = {
	name: string,
	accent: AccentColor | null,
	iconBase64: string | null,
	/**
	 *  Executable name of the focused process. Used by the frontend to
	 *  resolve which browser (if any) the user is currently on so it can
	 *  surface the matching extension install affordance.
	 */
	processName: string,
	/**
	 *  OS-level process id of the focused process. Required when the
	 *  frontend wants to act on that specific browser instance (for
	 *  example, opening a URL inside it rather than the OS default).
	 */
	processId: number,
};

export type TimelineAssetsEvent = ContextChip[];

export type ToolCall = {
	id?: string | null,
	name: string,
	/**
	 *  Always a JSON object on the wire. The struct-side type stays
	 *  `serde_json::Value` for ergonomic constructor input, but the specta-
	 *  generated TS type is `Record<string, unknown>` to reflect that.
	 */
	args: { [key in string]: unknown },
	type?: string | null,
};

export type ToolCallBlock = {
	id?: string | null,
	name: string,
	args?: { [key in string]: unknown },
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ToolCallChunk = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	index?: number | null,
	type?: string | null,
};

export type ToolCallChunkBlock = {
	id?: string | null,
	name?: string | null,
	args?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ToolMessage = {
	content: ContentBlocks,
	tool_call_id: string,
	id?: string | null,
	name?: string | null,
	status?: ToolStatus,
	artifact?: unknown | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

export type ToolStatus = "success" | "error";

export type UpdateInfo = {
	version: string,
	body: string | null,
};

export type UsageMetadata = {
	input_tokens: bigint,
	output_tokens: bigint,
	total_tokens: bigint,
	input_token_details?: InputTokenDetails | null,
	output_token_details?: OutputTokenDetails | null,
};

export type VideoContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

