// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	authGetLoginToken: () => typedError<LoginToken, AuthError>(__TAURI_INVOKE("auth_get_login_token")),
	authPollForLogin: () => typedError<boolean, AuthError>(__TAURI_INVOKE("auth_poll_for_login")),
	authRegister: (email: string, password: string) => typedError<null, AuthError>(__TAURI_INVOKE("auth_register", { email, password })),
	authLogin: (login: string, password: string) => typedError<null, AuthError>(__TAURI_INVOKE("auth_login", { login, password })),
	authLogout: () => typedError<null, AuthError>(__TAURI_INVOKE("auth_logout")),
	authIsAuthenticated: () => typedError<boolean, AuthError>(__TAURI_INVOKE("auth_is_authenticated")),
	authGetAccessTokenPayload: () => typedError<Claims, AuthError>(__TAURI_INVOKE("auth_get_access_token_payload")),
	authRefreshSession: () => typedError<null, AuthError>(__TAURI_INVOKE("auth_refresh_session")),
	authResendVerificationEmail: () => typedError<null, AuthError>(__TAURI_INVOKE("auth_resend_verification_email")),
	/**
	 *  Fetch the most-recent persisted activities and decorate each with the
	 *  presentation data the timeline rail needs (accent colour + a
	 *  `data:`-URL icon).
	 * 
	 *  Per-row icon fetches fan out concurrently via `join_all`; reqwest's
	 *  HTTP/2 pool multiplexes them over a single connection. Failures on a
	 *  single icon log + degrade to `(accent: None, icon_base64: None)` so
	 *  one bad asset can't block the rest of the page from rendering.
	 */
	activityList: (limit: number, offset: number) => typedError<SavedActivity[], SavedActivityError>(__TAURI_INVOKE("activity_list", { limit, offset })),
	chatCollectContext: (threadId: string) => typedError<ChatContext, StreamError>(__TAURI_INVOKE("chat_collect_context", { threadId })),
	chatSendQuery: (threadId: string, channel: Channel<ChatServerMessage>, request: ChatSendRequest) => typedError<null, StreamError>(__TAURI_INVOKE("chat_send_query", { threadId, channel, request })),
	chatRegenerate: (threadId: string, aiMessageId: string, channel: Channel<ChatServerMessage>) => typedError<null, StreamError>(__TAURI_INVOKE("chat_regenerate", { threadId, aiMessageId, channel })),
	chatCancelQuery: (threadId: string) => typedError<null, StreamError>(__TAURI_INVOKE("chat_cancel_query", { threadId })),
	paymentCreateCheckoutUrl: () => typedError<string, PaymentError>(__TAURI_INVOKE("payment_create_checkout_url")),
	paymentIsSubscribed: () => typedError<boolean, PaymentError>(__TAURI_INVOKE("payment_is_subscribed")),
	settingsGetGeneral: () => __TAURI_INVOKE<GeneralSettings>("settings_get_general"),
	settingsSetGeneral: (generalSettings: GeneralSettings) => typedError<GeneralSettings, SettingsError>(__TAURI_INVOKE("settings_set_general", { generalSettings })),
	settingsGetApi: () => __TAURI_INVOKE<APISettings>("settings_get_api"),
	settingsSetApi: (apiSettings: APISettings) => typedError<APISettings, SettingsError>(__TAURI_INVOKE("settings_set_api", { apiSettings })),
	settingsGetShared: () => __TAURI_INVOKE<SharedSettings>("settings_get_shared"),
	settingsSetShared: (shared: SharedSettings) => typedError<SharedSettings, SettingsError>(__TAURI_INVOKE("settings_set_shared", { shared })),
	settingsGetDesktop: () => __TAURI_INVOKE<DesktopSettings>("settings_get_desktop"),
	/**
	 *  Write the entire desktop section. Used by the appearance page and
	 *  anything else that mutates non-consent desktop state — the consent
	 *  prompt has its own dedicated procedure
	 *  ([`settings_record_telemetry_consent`]) so this one does **not** stamp
	 *  a consent version.
	 * 
	 *  `consent_version` is monotonically non-decreasing: incoming values
	 *  below the stored version are clamped up. This protects against a
	 *  misbehaving caller (or an older client) accidentally rolling back
	 *  the user's recorded consent while editing unrelated fields. Scale
	 *  fields are clamped at the IPC boundary by their newtypes
	 *  (`InterfaceScale` / `TextScale`), so no extra validation pass is
	 *  required here either.
	 */
	settingsSetDesktop: (desktop: DesktopSettings) => typedError<DesktopSettings, SettingsError>(__TAURI_INVOKE("settings_set_desktop", { desktop })),
	/**
	 *  Persist the user's response to the desktop telemetry consent prompt.
	 * 
	 *  The frontend hands the desired toggle state in `consent`; the backend
	 *  authoritatively stamps the consent version via
	 *  [`TelemetryConsent::record_for_desktop`] (monotonic — a newer
	 *  recorded version from another client is left alone). Lazily allocates
	 *  the local anonymous `distinct_id`, reapplies the native Sentry guard
	 *  so the new choice takes effect immediately, and emits
	 *  [`ConsentGate`] with `required: false` so the frontend can route
	 *  away from the consent page.
	 */
	settingsRecordTelemetryConsent: (consent: TelemetryConsent) => typedError<TelemetryConsent, SettingsError>(__TAURI_INVOKE("settings_record_telemetry_consent", { consent })),
	/**
	 *  Returns the per-install telemetry state — currently just the
	 *  anonymous distinct id. The cross-device consent toggles live under
	 *  the cloud `desktop` section and are surfaced via
	 *  [`settings_get_desktop`].
	 */
	settingsGetLocalTelemetry: () => __TAURI_INVOKE<TelemetryLocal>("settings_get_local_telemetry"),
	/**
	 *  Convenience read for the early-boot / pre-auth path where the
	 *  frontend needs only the consent toggles. Equivalent to
	 *  `settings_get_desktop().telemetry`, but typed so the IPC surface
	 *  documents that *only* the consent block crosses this boundary.
	 */
	settingsGetTelemetryConsent: () => __TAURI_INVOKE<TelemetryConsent>("settings_get_telemetry_consent"),
	systemCheckBackendConnection: (serverAddress: string | null) => typedError<string, SystemError>(__TAURI_INVOKE("system_check_backend_connection", { serverAddress })),
	systemGetLlmInfo: () => typedError<RedactedLlmConfig, SystemError>(__TAURI_INVOKE("system_get_llm_info")),
	/**
	 *  Probe an arbitrary URL by hitting /llm/info — used by the connection
	 *  picker's "Test connection" button before persisting the URL.
	 */
	systemTestBackendUrl: (url: string) => typedError<RedactedLlmConfig, SystemError>(__TAURI_INVOKE("system_test_backend_url", { url })),
	/**
	 *  The backend URL the desktop binary was built against. Surfaced to
	 *  the frontend so the connection picker can show what `Default` mode
	 *  resolves to — the value differs per release (dev builds point at
	 *  localhost, end-user binaries at the shipping organisation's hosted
	 *  backend).
	 */
	systemGetDefaultBackendUrl: () => __TAURI_INVOKE<string>("system_get_default_backend_url"),
	systemListActivities: () => typedError<ContextChip[], SystemError>(__TAURI_INVOKE("system_list_activities")),
	systemCheckForUpdate: () => typedError<{
	version: string,
	body: string | null,
} | null, SystemError>(__TAURI_INVOKE("system_check_for_update")),
	systemInstallUpdate: () => typedError<null, SystemError>(__TAURI_INVOKE("system_install_update")),
	systemQuit: () => __TAURI_INVOKE<void>("system_quit"),
	systemCheckAccessibilityPermission: () => __TAURI_INVOKE<boolean>("system_check_accessibility_permission"),
	systemRequestAccessibilityPermission: () => __TAURI_INVOKE<void>("system_request_accessibility_permission"),
	systemGetBrowserExtensionState: (processName: string) => __TAURI_INVOKE<BrowserExtensionState>("system_get_browser_extension_state", { processName }),
	systemOpenBrowserExtensionSettings: (processName: string) => typedError<null, SystemError>(__TAURI_INVOKE("system_open_browser_extension_settings", { processName })),
	systemOpenUrlInBrowser: (processId: number, url: string) => typedError<null, SystemError>(__TAURI_INVOKE("system_open_url_in_browser", { processId, url })),
	systemFocusMainWindow: () => typedError<null, SystemError>(__TAURI_INVOKE("system_focus_main_window")),
	systemGetTelemetryBootstrap: () => typedError<TelemetryBootstrap, SystemError>(__TAURI_INVOKE("system_get_telemetry_bootstrap")),
	/**
	 *  Frontend handshake: called from the root layout once event listeners
	 *  are attached. The backend reads the current desktop consent state and
	 *  emits [`ConsentGate`] with `required` set accordingly, so the
	 *  frontend can route to the consent prompt without ever computing the
	 *  rule in TypeScript. This is the only entry point that evaluates the
	 *  gate at startup — emitting from `setup()` would race the listener
	 *  registration.
	 */
	frontendReady: () => typedError<null, SystemError>(__TAURI_INVOKE("frontend_ready")),
	systemReinitTelemetry: () => __TAURI_INVOKE<void>("system_reinit_telemetry"),
	systemRotateTelemetryDistinctId: () => typedError<string, SystemError>(__TAURI_INVOKE("system_rotate_telemetry_distinct_id")),
	threadList: (limit: number, offset: number) => typedError<Thread[], ThreadError>(__TAURI_INVOKE("thread_list", { limit, offset })),
	threadListByActivity: (activityId: string, limit: number, offset: number) => typedError<Thread[], ThreadError>(__TAURI_INVOKE("thread_list_by_activity", { activityId, limit, offset })),
	threadCreate: () => typedError<Thread, ThreadError>(__TAURI_INVOKE("thread_create")),
	threadDelete: (threadId: string) => typedError<null, ThreadError>(__TAURI_INVOKE("thread_delete", { threadId })),
	threadGetMessages: (threadId: string, limit: number, offset: number) => typedError<MessageNode[], ThreadError>(__TAURI_INVOKE("thread_get_messages", { threadId, limit, offset })),
	threadSwitchBranch: (threadId: string, messageId: string, direction: number) => typedError<MessageNode[], ThreadError>(__TAURI_INVOKE("thread_switch_branch", { threadId, messageId, direction })),
	threadGenerateTitle: (threadId: string) => typedError<Thread, ThreadError>(__TAURI_INVOKE("thread_generate_title", { threadId })),
	threadSearchThreads: (query: string, limit: number, offset: number) => typedError<SearchThreadResult[], ThreadError>(__TAURI_INVOKE("thread_search_threads", { query, limit, offset })),
	threadSearchMessages: (query: string, limit: number, offset: number) => typedError<SearchMessageResult[], ThreadError>(__TAURI_INVOKE("thread_search_messages", { query, limit, offset })),
};

/** Events */
export const events = {
	authStateChanged: makeEvent<AuthStateChanged>("auth-state-changed"),
	browserExtensionStatusChanged: makeEvent<BrowserExtensionStatusChanged>("browser-extension-status-changed"),
	consentGate: makeEvent<ConsentGate>("consent-gate"),
	savedActivityCreated: makeEvent<SavedActivityCreated>("saved-activity-created"),
	savedActivityEnded: makeEvent<SavedActivityEnded>("saved-activity-ended"),
	timelineAppEvent: makeEvent<TimelineAppEvent>("timeline-app-event"),
	timelineAssetsEvent: makeEvent<TimelineAssetsEvent>("timeline-assets-event"),
};

/* Types */
export type AIMessage = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	tool_calls?: ToolCall[],
	invalid_tool_calls?: InvalidToolCall[],
	usage_metadata?: UsageMetadata | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

export type AIMessageChunk = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	tool_calls?: ToolCall[],
	invalid_tool_calls?: InvalidToolCall[],
	tool_call_chunks: ToolCallChunk[],
	usage_metadata?: UsageMetadata | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
	chunk_position?: ChunkPosition | null,
};

export type APISettings = {
	mode: ConnectionMode,
};

export type AccentColor = {
	/**  Dominant color in CSS form: lowercase `#rrggbb`. */
	hex: string,
	/**
	 *  Text/foreground color (`#000000` or `#ffffff`) chosen via WCAG relative
	 *  luminance. Use for text rendered on top of `hex`.
	 */
	onHex: string,
	/**
	 *  Icon-background color (`#000000` or `#ffffff`) chosen via NTSC
	 *  perceived brightness. Use for shapes that visually contrast with `hex`.
	 */
	iconBg: string,
};

export type Annotation = { type: "citation"; id?: string | null; url?: string | null; title?: string | null; start_index?: bigint | null; end_index?: bigint | null; cited_text?: string | null; extras?: { [key in string]: unknown } | null } | { type: "non_standard_annotation"; id?: string | null; value: { [key in string]: unknown } };

/**
 *  Tagged union of every message variant. Wire format is internally tagged on
 *  the `type` field — `{"type": "human", "content": ..., ...}` etc. The inner
 *  per-variant structs (`HumanMessage`, `AIMessage`, ...) deliberately do NOT
 *  carry their own `type` field; the discriminant is added at the union level
 *  and only there. This keeps the Rust types and the specta-generated TS types
 *  in lockstep with the actual JSON shape.
 */
export type AnyMessage = {
	type: "human",
} & HumanMessage | {
	type: "system",
} & SystemMessage | {
	type: "ai",
} & AIMessage | {
	type: "tool",
} & ToolMessage | {
	type: "chat",
} & ChatMessage | {
	type: "remove",
} & RemoveMessage;

export type AudioContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

/**
 *  Typed error surface for the `auth_*` IPC commands. Externally tagged
 *  so the JS side gets `{ type: "NotAuthenticated" }` and can branch on
 *  the variant. The split between `NotAuthenticated` (the user must sign
 *  in again) and `Backend` (transient — local credentials are intact)
 *  matches `euro_auth::AuthError::is_logged_out` / `is_transient`, so
 *  the UI can decide whether to bounce the user to the login screen or
 *  just toast and retry.
 */
export type AuthError = { type: "NotAuthenticated" } | { type: "Backend"; data: string } | { type: "LoginTokenExpired" } | { type: "Config"; data: string } | { type: "Persistence"; data: string } | { type: "StateUnavailable"; data: string } | { type: "Internal"; data: string };

/**
 *  Backend → frontend auth-state transition. Mirrors the shape of
 *  [`crate::AuthEvent`] for the JS side; `claims == None` means signed out.
 */
export type AuthStateChanged = {
	claims: Claims | null,
};

export type BlockIndex = number | string;

/**
 *  What the desktop frontend should render for a given browser when its
 *  Eurora extension isn't currently driving messages back to the app.
 * 
 *  Resolution combines two signals — whether a native messenger is
 *  registered on the bridge for that browser, and (for browsers whose
 *  extension ships bundled with a host app) the latest
 *  [`BundledExtensionState`] the host has published. The variants are
 *  ordered from "everything works" to "we don't recognize this process".
 * 
 *  Snake-case Specta tags so the externally-tagged JSON matches what the
 *  existing TS bindings file consumes for tagged unions elsewhere in the
 *  app (`{ "kind": "not_installed", "install_url": "…" }`).
 */
export type BrowserExtensionState = 
/**
 *  Extension is connected to the bridge. The frontend should render
 *  no install affordance for this browser.
 */
{ kind: "connected" } | 
/**
 *  No client is registered for this browser, but the extension is
 *  distributed via a public store. The frontend should offer to open
 *  `install_url` in the focused browser.
 */
{ kind: "not_installed"; install_url: string } | 
/**
 *  The extension is installed but the user has it disabled in the
 *  browser's settings. Bundled browsers (Safari) only — there is no
 *  API to flip this state programmatically, so the frontend should
 *  deep-link the user into the relevant settings page.
 */
{ kind: "disabled" } | 
/**
 *  The browser has no record of the bundled extension. Typically
 *  means the host app has never been launched on this machine.
 */
{ kind: "not_discovered" } | 
/**
 *  We can't determine the extension's state right now. The frontend
 *  should hide the affordance entirely rather than showing stale or
 *  misleading guidance.
 */
{ kind: "unknown" } | 
/**
 *  Process name doesn't match any browser Eurora knows about. The
 *  frontend should hide the affordance.
 */
{ kind: "unsupported" };

/**
 *  Push event fired whenever a browser's extension state transitions —
 *  a native messenger registers/disconnects, or a bundled host publishes
 *  a fresh state. The frontend uses this to update the install
 *  affordance without polling.
 */
export type BrowserExtensionStatusChanged = {
	process_name: string,
	state: BrowserExtensionState,
};

/**
 *  Per-turn host context returned by `chat_collect_context`.
 * 
 *  `content_blocks` are inlined directly — large payloads are rewritten
 *  into asset references server-side at chat-turn time, so the wire
 *  format here can carry raw bytes/text without the client having to
 *  round-trip them.
 */
export type ChatContext = {
	contentBlocks: ContentBlock[],
	assetChips: ContextChip[],
};

export type ChatMessage = {
	content: ContentBlocks,
	role: string,
	id?: string | null,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

/**
 *  Payload of a [`ChatClientMessage::Send`] frame.
 * 
 *  When `parent_message_id` is present the turn is interpreted as an edit of
 *  an existing branch; the service rewinds `active_leaf` accordingly.
 * 
 *  `activity_id` captures the desktop client's currently-tracked activity
 *  when the user sent the message, so the server can record the link in
 *  `activity_threads`. Optional because non-desktop clients (web, mobile)
 *  have no timeline; absent values skip the link step entirely.
 */
export type ChatSendRequest = {
	content_blocks: ContentBlock[],
	parent_message_id?: string | null,
	asset_chips_json?: string | null,
	activity_id?: string | null,
};

/**
 *  Frame sent by the server over the chat WebSocket.
 * 
 *  Clients should accumulate `Chunk` payloads (using agent-chain's chunk-merge
 *  semantics) and replace placeholder state with the `Final.messages` payload
 *  when the turn ends. The tool-routing pair `ToolRequest` + `ToolCancel`
 *  drives remote-tool RPC over the same socket.
 */
export type ChatServerMessage = 
/**  The user's message has been persisted; clients should display it. */
{ type: "confirmed_human_message"; message: MessageNode } | 
/**  One streaming chunk from the AI. */
{ type: "chunk"; chunk: AIMessageChunk } | 
/**
 *  The turn ended successfully; tree positions for everything that was
 *  persisted during this turn (human + AI + any tool messages).
 */
{ type: "final"; messages: MessageNode[] } | 
/**  The turn aborted with an error. The connection is closed after this. */
{ type: "error"; kind: string; message: string } | 
/**
 *  Request the client to execute a tool on its side and return the
 *  result via [`ChatClientMessage::ToolResponse`] correlated by
 *  `call_id`.
 */
{ type: "tool_request"; call_id: number; descriptor: WireToolDescriptor; arguments: unknown } | 
/**
 *  Abort an in-flight `ToolRequest`. Sent when the user cancels the
 *  turn or the server's tool budget is exhausted before the client's
 *  response arrives.
 */
{ type: "tool_cancel"; call_id: number };

export type ChunkPosition = "last";

export type Claims = {
	sub: string,
	email: string,
	display_name?: string | null,
	exp: bigint,
	iat: bigint,
	token_type: string,
	role: Role,
	aud?: string,
	email_verified?: boolean,
	/**
	 *  RFC 7519 JWT ID. Guarantees that two tokens minted for
	 *  the same subject within the same second never collide
	 *  after hashing (see refresh-token rotation).
	 */
	jti?: string,
};

/**
 *  Where the desktop app should send authenticated requests.
 * 
 *  `Default` carries no parameters because its URL is baked in, which
 *  keeps "I want to talk to the URL this binary was built against"
 *  expressible as a stable enum value rather than a magic string.
 *  `Custom` covers everything else (self-hosted homelab, a colleague's
 *  tunnel, a different organisation's infrastructure).
 */
export type ConnectionMode = { kind: "default" } | { kind: "custom"; url: string };

/**
 *  Pushed from Rust to the frontend whenever the desktop telemetry
 *  consent gate flips. Fired once during startup (in response to
 *  [`frontend_ready`]) with the current state, and again whenever the
 *  gate changes (e.g. after [`crate::procedures::settings::settings_record_telemetry_consent`]).
 * 
 *  The frontend's root layout listens for this event and routes to the
 *  consent prompt when `required` is `true`. No comparison against a
 *  consent-version constant lives in TypeScript — that decision is
 *  entirely Rust's, and the frontend trusts the event payload.
 */
export type ConsentGate = {
	required: boolean,
};

export type ContentBlock = {
	type: "text",
} & TextContentBlock | {
	type: "invalid_tool_call",
} & InvalidToolCallBlock | {
	type: "reasoning",
} & ReasoningContentBlock | {
	type: "non_standard",
} & NonStandardContentBlock | {
	type: "image",
} & ImageContentBlock | {
	type: "video",
} & VideoContentBlock | {
	type: "audio",
} & AudioContentBlock | {
	type: "text-plain",
} & PlainTextContentBlock | {
	type: "file",
} & FileContentBlock | {
	type: "tool_call",
} & ToolCallBlock | {
	type: "tool_call_chunk",
} & ToolCallChunkBlock | {
	type: "server_tool_call",
} & ServerToolCall | {
	type: "server_tool_call_chunk",
} & ServerToolCallChunk | {
	type: "server_tool_result",
} & ServerToolResult;

export type ContentBlocks = ContentBlock[];

/**
 *  Per-asset context chip surfaced alongside [`ChatContext`] content blocks.
 * 
 *  Lives here (rather than in `euro-activity`) because both desktop and
 *  mobile chat IPC layers emit it: desktop populates it from the timeline,
 *  mobile populates it from native pickers. Keeping the wire shape in
 *  `thread-core` lets the IPC commands stay app-agnostic and avoids
 *  dragging the desktop-only `euro-activity` graph into mobile.
 */
export type ContextChip = {
	id: string,
	name: string,
	icon: string | null,
	domain: string | null,
};

/**
 *  Desktop-only cloud-synced settings. Mobile and web each have their
 *  own platform sections to keep concepts that don't translate (window
 *  chrome scaling, telemetry SDKs that don't run on the other
 *  platforms) cleanly partitioned.
 * 
 *  The derived `Default` is both the fresh-install value and the
 *  per-field fallback used by `#[serde(default)]` when an older client
 *  wrote a partial blob. Scales default to [`DEFAULT_SCALE`] (via
 *  [`InterfaceScale::DEFAULT`] / [`TextScale::DEFAULT`]) rather than
 *  `0.0`, because a zero-size UI is unrecoverable; an inert sensible
 *  value is the only safe fallback. Telemetry consent defaults to the
 *  "never asked" sentinel (`consent_version == 0`) so a fresh install
 *  is routed through the consent prompt rather than silently
 *  auto-consented — see [`crate::TelemetryConsent`].
 * 
 *  `interface_scale` and `text_scale` carry their invariants in the
 *  type, not in a separate validation pass: any value of type
 *  [`InterfaceScale`] or [`TextScale`] is by construction finite and
 *  within `[MIN, MAX]`. Deserialization, `From<f32>`, and the
 *  `bon`-generated builder all route through the clamping
 *  constructor, so a corrupt cloud blob, a misbehaving client, or a
 *  hand-rolled patch via `extras` all collapse to safe values before
 *  they ever land in the struct.
 */
export type DesktopSettings = {
	/**
	 *  Multiplier applied to the document's root font-size, scaling every
	 *  rem-anchored design token (text, spacing, controls) together.
	 */
	interfaceScale?: InterfaceScale,
	/**
	 *  Additional multiplier layered on top of `interface_scale` that
	 *  affects only typography utilities, leaving spacing and control
	 *  sizes alone.
	 */
	textScale?: TextScale,
	/**
	 *  Desktop-scoped telemetry consent. Covers what the desktop
	 *  client collects (Sentry, PostHog) and nothing else; mobile and
	 *  web each carry their own record because consent must be
	 *  specific to the data actually collected.
	 */
	telemetry?: TelemetryConsent,
} & { [key in string]: unknown };

export type FileContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

export type GeneralSettings = {
	autostart: boolean,
};

export type HumanMessage = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

export type ImageContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

export type InputTokenDetails = {
	audio?: bigint | null,
	cache_creation?: bigint | null,
	cache_read?: bigint | null,
} & { [key in string]: bigint };

/**
 *  Interface-scale multiplier applied to the document's root font-size,
 *  scaling every rem-anchored design token (text, spacing, controls)
 *  together. Always finite and within
 *  `[InterfaceScale::MIN, InterfaceScale::MAX]` by construction.
 * 
 *  Bounds are chosen against window chrome: below `MIN` the layout
 *  drops below useful tap-target sizes on Linux / Windows; above `MAX`
 *  the fixed-size titlebar and traffic-light buttons start overlapping
 *  content.
 */
export type InterfaceScale = number | null;

export type InvalidToolCall = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	error?: string | null,
	type?: string | null,
};

export type InvalidToolCallBlock = {
	id?: string | null,
	name?: string | null,
	args?: string | null,
	error?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type LoginToken = {
	code_challenge: string,
	/**
	 *  Seconds remaining until the login challenge expires. `u32` so the TS
	 *  bindings stay on plain `number` — twenty-minute TTLs fit trivially
	 *  and there's no scenario where this needs more than 32 bits.
	 */
	expires_in: number,
	url: string,
};

/**  One node in the message tree returned by message-list endpoints. */
export type MessageNode = {
	parent_id?: string | null,
	message: AnyMessage,
	children?: MessageNode[],
	sibling_index: number,
	depth: number,
};

/**  Pointer to a model owned by a specific provider. */
export type ModelRef = {
	provider: string,
	model: string,
};

export type NonStandardContentBlock = {
	id?: string | null,
	value?: { [key in string]: unknown },
	index?: BlockIndex | null,
};

export type OutputTokenDetails = {
	audio?: bigint | null,
	reasoning?: bigint | null,
} & { [key in string]: bigint };

/**
 *  Typed error surface for the `payment_*` IPC commands. Externally
 *  tagged so the JS side can branch on `error.type`. `Auth` re-uses the
 *  auth surface so the same "session expired" handler in the frontend
 *  catches both auth-touching commands and payment-touching commands
 *  without a parallel mapping.
 */
export type PaymentError = { type: "Auth"; data: AuthError } | { type: "Backend"; data: string } | { type: "BadResponse"; data: string };

export type PlainTextContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type: string,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	text?: string | null,
	title?: string | null,
	context?: string | null,
	extras?: { [key in string]: unknown } | null,
};

export type ReasoningContentBlock = {
	id?: string | null,
	reasoning?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type RedactedAwsCreds = { kind: "default" } | { kind: "static"; access_key_id: string };

export type RedactedGoogleCreds = { kind: "api_key"; has_key: boolean } | { kind: "service_account"; path: string };

/**
 *  View of [`LlmConfig`] safe to serialise across the wire and into logs.
 * 
 *  Mirrors the shape of [`LlmConfig`] but replaces every secret-bearing field
 *  with a boolean flag indicating whether a value is present. Consumers
 *  (e.g. the desktop app's connection panel) can show "you're connected to
 *  OpenAI / gpt-4o-mini" without ever seeing the API key.
 */
export type RedactedLlmConfig = {
	providers: { [key in string]: RedactedProvider },
	roles: Roles,
};

export type RedactedProvider = { kind: "openai"; has_api_key: boolean; base_url: string | null; organization: string | null } | { kind: "anthropic"; has_api_key: boolean; base_url: string | null } | { kind: "google"; credentials: RedactedGoogleCreds; project: string | null } | { kind: "bedrock"; region: string; credentials: RedactedAwsCreds } | { kind: "openai_compatible"; base_url: string; has_api_key: boolean; header_names: string[]; has_overrides: boolean };

export type RemoveMessage = {
	id: string,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

export type Role = "Free" | "Tier1";

/**
 *  Per-role model assignments. `chat` and `title` are mandatory; `vision` is
 *  only required when the deployment expects to handle image-bearing
 *  messages.
 */
export type Roles = {
	chat: ModelRef,
	title: ModelRef,
	vision: ModelRef | null,
};

/**
 *  Frontend-facing view of one persisted activity.
 * 
 *  `accent` and `icon_base64` are populated by the desktop tauri layer
 *  (decoded from the asset's PNG bytes); both are `None` whenever the
 *  activity has no icon or the icon fetch failed — treat them as
 *  presentation hints, never as load-bearing fields.
 */
export type SavedActivity = {
	id: string,
	name: string,
	processName: string,
	windowTitle: string,
	startedAt: string,
	endedAt: string | null,
	accent: AccentColor | null,
	/**
	 *  `data:<mime>;base64,...` URL suitable for direct embedding in
	 *  `<img src>`. Bare base64 would force the frontend to know the
	 *  mime out-of-band, which it currently does not.
	 */
	iconBase64: string | null,
};

/**
 *  Push event fired after the cloud `POST /activities` succeeds for a
 *  freshly-tracked activity. Lets the desktop frontend prepend the new
 *  row to the timeline rail without re-polling `GET /activities`.
 */
export type SavedActivityCreated = SavedActivity;

/**
 *  Push event fired after the cloud closing PATCH of `ended_at` succeeds
 *  for a previously-tracked activity. Lets the desktop frontend update
 *  the matching row's `endedAt` in place — without it the row keeps the
 *  `null` it was created with and the timeline rail's duration-based
 *  connector height stays clamped to the minimum until the next reload.
 * 
 *  Payload is intentionally minimal: the frontend already has the rest
 *  of the row in memory, so only the id and the now-known end timestamp
 *  are shipped over the wire.
 */
export type SavedActivityEnded = {
	id: string,
	endedAt: string,
};

/**
 *  Errors surfaced to the frontend from [`activity_list`].
 * 
 *  Externally tagged so the JS side gets `{ type: "Network", data: "..." }`
 *  and can branch on `type` rather than parsing strings. Variants are
 *  intentionally narrow — any failure to fetch a *single* icon falls back
 *  to `accent: None, icon_base64: None` on that row instead of failing
 *  the whole call.
 */
export type SavedActivityError = { type: "StateUnavailable"; data: string } | { type: "Network"; data: string };

/**  One message hit returned by full-text search. */
export type SearchMessageResult = {
	id: string,
	thread_id: string,
	message_type: string,
	rank: number | null,
	created_at: string,
	snippet: string,
};

/**  One thread hit returned by full-text search. */
export type SearchThreadResult = {
	id: string,
	title: string,
	rank: number | null,
	updated_at: string,
};

export type ServerToolCall = {
	id: string,
	name: string,
	args?: { [key in string]: unknown },
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ServerToolCallChunk = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ServerToolResult = {
	id?: string | null,
	tool_call_id: string,
	status: ServerToolStatus,
	output?: unknown | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ServerToolStatus = "success" | "error";

/**
 *  Typed error surface for the `settings_*` IPC commands. Externally
 *  tagged so the JS side gets `{ type: "Persistence", data: "..." }`
 *  and can branch on `type` instead of parsing strings. Variants are
 *  grouped by failure mode rather than by command, since several
 *  commands share `Persistence` (any setter that hits the on-disk
 *  settings files).
 */
export type SettingsError = { type: "Persistence"; data: string } | { type: "EndpointSwitch"; data: string };

/**
 *  Cross-platform cloud-synced settings. Anything in this section
 *  applies identically on desktop, mobile, and web; per-platform
 *  concepts live in the platform sections of [`crate::CloudSettings`].
 * 
 *  Telemetry consent is deliberately *not* here: each platform ships
 *  a different telemetry stack and so collects different categories
 *  of data, which means consent has to be platform-specific (see
 *  [`crate::TelemetryConsent`]).
 * 
 *  `dynamic_accent` defaults to `true` — the design pulls the OS / wallpaper
 *  accent by default and a user who has never touched the toggle should see
 *  the dynamic behaviour. This is the one field where the product default
 *  differs from `bool::default()`, which is why this struct has a hand-rolled
 *  `Default` instead of `#[derive]`.
 */
export type SharedSettings = {
	theme?: ThemePreference,
	dynamicAccent?: boolean,
} & { [key in string]: unknown };

/**
 *  Typed error surface for the streaming `chat_*` IPC commands.
 *  Externally tagged so the JS side can branch on `error.type`.
 *  `Cancelled` is split out from the rest so the UI can suppress its
 *  own cancel-induced errors instead of showing a toast for them; an
 *  upstream [`crate::Error`] (e.g. a deleted thread mid-stream) is
 *  wrapped in `Thread` so the JS side can drill into the same
 *  [`ThreadError`] variants it handles for CRUD calls.
 */
export type StreamError = { type: "Cancelled" } | { type: "Timeout"; data: number } | { type: "Channel"; data: string } | { type: "StateUnavailable"; data: string } | { type: "Thread"; data: ThreadError };

/**
 *  Typed error surface for the `system_*` IPC commands. Externally tagged
 *  so the JS side gets `{ type: "BackendUnreachable", data: "..." }` and
 *  can branch on `type` without parsing strings. Variants are grouped by
 *  failure mode rather than by command, since several commands share a
 *  failure mode (e.g. anything that touches the LLM endpoint can hit
 *  `BackendUnreachable` / `BadResponse`).
 */
export type SystemError = { type: "BackendUnreachable"; data: string } | { type: "InvalidUrl"; data: string } | { type: "BadResponse"; data: string } | { type: "Updater"; data: string } | { type: "NoUpdateAvailable" } | { type: "UnsupportedBrowser"; data: string } | { type: "Bridge"; data: string } | { type: "StateUnavailable"; data: string } | { type: "Persistence"; data: string } | { type: "Window"; data: string };

export type SystemMessage = {
	content: ContentBlocks,
	id?: string | null,
	name?: string | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

/**
 *  Single payload the desktop frontend fetches once at startup to bring
 *  up its Sentry / PostHog SDKs. Bundles the user's persisted consent
 *  state, the local anonymous identifier, the embedded build-time keys,
 *  the release identity, and **precomputed policy decisions** so the
 *  frontend doesn't reproduce the consent-gating rules in TypeScript.
 * 
 *  `consent` is included verbatim so the settings UI can render which
 *  toggles are currently set; the SDK init paths consume
 *  [`Self::allows_errors`] / [`Self::allows_metrics`] /
 *  [`Self::allows_identification`] instead of reading the consent
 *  fields directly.
 * 
 *  `None` on any of the build-time fields means "this surface is
 *  disabled in this build". `build.rs` enforces all-or-nothing
 *  consistency: a build with a DSN always carries a channel and a
 *  release, so the frontend never has to defend against a
 *  half-configured payload.
 */
export type TelemetryBootstrap = {
	consent: TelemetryConsent,
	distinctId: string | null,
	sentryDsn: string | null,
	posthogKey: string | null,
	posthogHost: string | null,
	channel: string | null,
	release: string | null,
	/**
	 *  `true` when the user has recorded consent at the current desktop
	 *  version *and* opted into anonymous error reporting.
	 */
	allowsErrors: boolean,
	/**
	 *  `true` when the user has recorded consent at the current desktop
	 *  version *and* opted into anonymous metrics.
	 */
	allowsMetrics: boolean,
	/**
	 *  `true` when, additionally to [`Self::allows_metrics`], the user
	 *  has opted into non-anonymous identification.
	 */
	allowsIdentification: boolean,
};

/**
 *  Per-platform telemetry consent record. Lives under each platform
 *  section of [`crate::CloudSettings`] — never under
 *  [`crate::SharedSettings`] — because consent must be specific to the
 *  data actually collected, and each platform ships a different
 *  telemetry stack (Sentry + PostHog on desktop, platform-native SDKs
 *  on mobile, etc.). A user agreeing on desktop has not seen, and
 *  cannot legally cover, what mobile or web will collect.
 * 
 *  `distinct_id` is intentionally absent — it is an anonymous
 *  per-install identifier whose rotation must break cross-device
 *  linkage, and so stays in the platform's local file rather than
 *  crossing the wire.
 * 
 *  ## `consent_version` semantics
 * 
 *  `consent_version` records the schema version of the consent prompt
 *  the user agreed to *on this platform*.
 * 
 *  - `0` (the `Default`) means the user has **never** seen the prompt.
 *  - Any value `>= DESKTOP_CONSENT_VERSION` (or the analogue for other
 *    platforms) means the user has consented to the current schema.
 *  - A value between `1` and `current - 1` means the user consented to
 *    an older prompt; the client must re-prompt.
 * 
 *  The value is **monotonically non-decreasing** by contract. The only
 *  writer is the platform's consent procedure, which uses
 *  [`Self::record_for_desktop`] (analogous methods for other platforms
 *  will land when those clients ship). Regular settings-page saves
 *  must *not* touch this field; the IPC layer enforces this by
 *  clamping incoming values against the stored version.
 */
export type TelemetryConsent = {
	consentVersion?: number,
	anonymousMetrics?: boolean,
	anonymousErrors?: boolean,
	nonAnonymousMetrics?: boolean,
} & { [key in string]: unknown };

/**
 *  Local-only telemetry state. Persisted next to the rest of
 *  [`crate::LocalSettings`] in `local.json`; never crosses the wire to
 *  the cloud-sync backend.
 */
export type TelemetryLocal = {
	/**
	 *  Anonymous per-install identifier. `None` until the user accepts
	 *  telemetry for the first time, then a fresh UUID v4 that survives
	 *  until the user explicitly rotates it.
	 */
	distinctId?: string | null,
};

export type TextContentBlock = {
	id?: string | null,
	text: string,
	annotations?: Annotation[] | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

/**
 *  Additional multiplier layered on top of [`InterfaceScale`] that
 *  affects only typography utilities, leaving spacing and control
 *  sizes alone. Always finite and within
 *  `[TextScale::MIN, TextScale::MAX]` by construction.
 * 
 *  Bounds currently mirror [`InterfaceScale`] but the type is separate
 *  so they can diverge — text legibility may eventually want a wider
 *  range than the chrome-anchored interface bounds allow, and the type
 *  system already enforces that the two fields can't be swapped at
 *  call sites.
 */
export type TextScale = number | null;

/**
 *  User's preferred colour scheme. `System` defers to the OS-level
 *  setting; `Light` / `Dark` pin it explicitly across devices.
 */
export type ThemePreference = "system" | "light" | "dark";

/**  A persisted thread row as returned to the client. */
export type Thread = {
	id: string,
	user_id: string,
	title: string,
	created_at: string,
	updated_at: string,
	active_leaf_id?: string | null,
};

/**
 *  Typed error surface for the CRUD/search `thread_*` IPC commands.
 *  Externally tagged so the JS side can branch on `error.type` without
 *  parsing strings. `NotFound` lifts [`crate::Error::ThreadNotFound`] to
 *  a dedicated variant so the UI can render an empty state instead of a
 *  generic toast.
 */
export type ThreadError = { type: "NotFound" } | { type: "Backend"; data: string } | { type: "BadResponse"; data: string } | { type: "StateUnavailable"; data: string } | { type: "Internal"; data: string };

export type TimelineAppEvent = {
	name: string,
	accent: AccentColor | null,
	iconBase64: string | null,
	/**
	 *  Executable name of the focused process. Used by the frontend to
	 *  resolve which browser (if any) the user is currently on so it can
	 *  surface the matching extension install affordance.
	 */
	processName: string,
	/**
	 *  OS-level process id of the focused process. Required when the
	 *  frontend wants to act on that specific browser instance (for
	 *  example, opening a URL inside it rather than the OS default).
	 */
	processId: number,
};

export type TimelineAssetsEvent = ContextChip[];

export type ToolCall = {
	id?: string | null,
	name: string,
	/**
	 *  Always a JSON object on the wire. The struct-side type stays
	 *  `serde_json::Value` for ergonomic constructor input, but the specta-
	 *  generated TS type is `Record<string, unknown>` to reflect that.
	 */
	args: { [key in string]: unknown },
	type?: string | null,
};

export type ToolCallBlock = {
	id?: string | null,
	name: string,
	args?: { [key in string]: unknown },
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ToolCallChunk = {
	name?: string | null,
	args?: string | null,
	id?: string | null,
	index?: number | null,
	type?: string | null,
};

export type ToolCallChunkBlock = {
	id?: string | null,
	name?: string | null,
	args?: string | null,
	index?: BlockIndex | null,
	extras?: { [key in string]: unknown } | null,
};

export type ToolMessage = {
	content: ContentBlocks,
	tool_call_id: string,
	id?: string | null,
	name?: string | null,
	status?: ToolStatus,
	artifact?: unknown | null,
	additional_kwargs?: { [key in string]: unknown },
	response_metadata?: { [key in string]: unknown },
};

/**
 *  Where a tool runs. The server uses this to dispatch each call:
 *  `ServerLocal` tools execute in-process on the backend; everything else
 *  is routed back to the client over the chat WebSocket as a `ToolRequest`,
 *  and from there the client picks the right destination (bridge, native
 *  app, ACP session).
 * 
 *  `#[non_exhaustive]` so adding new sources later is non-breaking for
 *  downstream consumers that `match` on the enum.
 */
export type ToolSource = 
/**
 *  Routed via `euro-bridge` to a registered app of `app_kind` (in v1,
 *  `"browser"`).
 */
{ kind: "bridge"; app_kind: string } | 
/**  Runs in-process on the client (native Tauri tools). */
{ kind: "client_local" } | 
/**  Runs in-process on the backend (Firecrawl, describe-image). */
{ kind: "server_local" } | 
/**  Piped through an ACP session. */
{ kind: "acp" };

export type ToolStatus = "success" | "error";

export type UpdateInfo = {
	version: string,
	body: string | null,
};

export type UsageMetadata = {
	input_tokens: bigint,
	output_tokens: bigint,
	total_tokens: bigint,
	input_token_details?: InputTokenDetails | null,
	output_token_details?: OutputTokenDetails | null,
};

export type VideoContentBlock = {
	id?: string | null,
	file_id?: string | null,
	mime_type?: string | null,
	index?: BlockIndex | null,
	url?: string | null,
	base64?: string | null,
	extras?: { [key in string]: unknown } | null,
};

/**
 *  Wire-side descriptor for a tool. One per call, one per entry in the
 *  per-turn `CapabilityUpdate.tools` list.
 * 
 *  The framework form (`eurora_tools::ToolDescriptor`) is the in-process
 *  `&'static`-everywhere shape; this is its serializable counterpart, owned
 *  and ready for transport. The server only ever sees this form.
 */
export type WireToolDescriptor = {
	/**
	 *  Fully-qualified tool name, namespaced with `::`
	 *  (e.g. `browser::youtube::get_current_timestamp`).
	 */
	name: string,
	/**
	 *  Human-readable description shown to the LLM. Produced by the
	 *  framework macro from the first paragraph of the trait method's
	 *  rustdoc.
	 */
	description: string,
	/**  JSON Schema for the tool's `arguments` payload. */
	input_schema: unknown,
	/**  JSON Schema for the tool's success payload. */
	output_schema: unknown,
	/**
	 *  Per-call timeout in milliseconds. Used by the server's bus to bound
	 *  in-flight remote calls; the framework's `ToolDescriptor.timeout`
	 *  converts to/from this field. `u32` ms (~49 days) is bounded well
	 *  above any sensible per-tool budget and keeps the wire shape inside
	 *  JS's safe integer range.
	 */
	timeout_ms: number,
	/**  Where the tool runs. The server uses this to pick a dispatch path. */
	source: ToolSource,
	/**
	 *  Context keys whose presence is required for this tool to be
	 *  surfaced to the LLM in a given turn (e.g.
	 *  `["youtube::watch_page"]`).
	 */
	required_contexts?: string[],
	/**
	 *  If true, the server must obtain explicit user approval before
	 *  dispatching the call. Not enforced in v1 (all v1 tools are
	 *  read-only) but declared so the protocol is stable.
	 */
	requires_user_approval?: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

