// This file has been generated by Specta. Do not edit this file manually.
/**
 *  Frame sent by the client over the chat WebSocket.
 * 
 *  Bidirectional from day one; the current set is `Send` (start a turn) and
 *  `Cancel` (interrupt the in-flight turn). New variants can be added without
 *  breaking older clients because serde rejects unknown tagged variants only
 *  on deserialize, never on encode.
 */
export type ChatClientMessage = { type: "send" } & ChatSendRequest | { type: "cancel" };

/**
 *  Payload of a [`ChatClientMessage::Send`] frame.
 * 
 *  `content_blocks` carries a `Vec<agent_chain::ContentBlock>` as JSON. When
 *  `parent_message_id` is present the turn is interpreted as an edit of an
 *  existing branch; the service rewinds `active_leaf` accordingly.
 */
export type ChatSendRequest = {
	content_blocks: unknown[],
	parent_message_id?: string | null,
	asset_chips_json?: string | null,
};

/**
 *  Frame sent by the server over the chat WebSocket.
 * 
 *  `chunk` carries an `AIMessageChunk` JSON; the client should accumulate
 *  chunks (using agent-chain's chunk-merge semantics) and replace placeholder
 *  state with the `final_messages` payload when the turn ends.
 */
export type ChatServerMessage = 
// The user's message has been persisted; clients should display it.
{ type: "confirmed_human_message"; message: MessageNode } | 
// One streaming chunk from the AI.
{ type: "chunk"; chunk: unknown } | 
/**
 *  The turn ended successfully; tree positions for everything that was
 *  persisted during this turn (human + AI + any tool messages).
 */
{ type: "final"; messages: MessageNode[] } | 
// The turn aborted with an error. The connection is closed after this.
{ type: "error"; kind: string; message: string };

// Request body for `POST /threads`.
export type CreateThreadRequest = {
	title?: string | null,
};

// Response body for `POST /threads`.
export type CreateThreadResponse = {
	thread: Thread,
};

// Response body for `DELETE /threads/{thread_id}`.
export type DeleteThreadResponse = Record<string, never>;

// Request body for `POST /threads/{thread_id}/title`.
export type GenerateThreadTitleRequest = {
	content: string,
};

// Response body for `POST /threads/{thread_id}/title`.
export type GenerateThreadTitleResponse = {
	thread: Thread,
};

// Query parameters for `GET /threads/{thread_id}/messages`.
export type GetMessagesQuery = {
	limit?: number | null,
	offset?: number | null,
	all_variants?: boolean,
};

// Response body for endpoints that return the message tree.
export type GetMessagesResponse = {
	messages: MessageNode[],
};

// Response body for `GET /threads/{thread_id}`.
export type GetThreadResponse = {
	thread: Thread,
};

// Query parameters for `GET /threads`.
export type ListThreadsQuery = {
	limit?: number | null,
	offset?: number | null,
};

// Response body for `GET /threads`.
export type ListThreadsResponse = {
	threads: Thread[],
};

/**
 *  One node in the message tree returned by message-list endpoints.
 * 
 *  `message` is an `agent_chain::AnyMessage` serialized as JSON. We type the
 *  field as [`serde_json::Value`] so this crate stays free of the agent-chain
 *  dependency, and override the TypeScript representation to `unknown` so
 *  the frontend converter narrows it explicitly. The same trick on
 *  `children` works around `specta-typescript`'s lack of recursive type
 *  references at this version (it would inline the type and stack-overflow);
 *  the runtime JSON shape is still a real recursive `MessageNode` tree.
 */
export type MessageNode = {
	parent_id?: string | null,
	message: unknown,
	children?: unknown[],
	sibling_index: number,
	depth: number,
};

/**
 *  Request body for `POST /threads/{thread_id}/preliminary-blocks`.
 * 
 *  `content_blocks` carries `agent_chain` `ContentBlock` JSON values; the
 *  service rewrites large in-line payloads into asset references and returns
 *  the rewritten blocks.
 */
export type SavePreliminaryContentBlocksRequest = {
	content_blocks: unknown[],
};

// Response body for `POST /threads/{thread_id}/preliminary-blocks`.
export type SavePreliminaryContentBlocksResponse = {
	content_blocks: unknown[],
};

// One message hit returned by full-text search.
export type SearchMessageResult = {
	id: string,
	thread_id: string,
	message_type: string,
	rank: number,
	created_at: string,
	snippet: string,
};

// Query parameters for `GET /threads/messages/search`.
export type SearchMessagesQuery = {
	q: string,
	limit?: number | null,
	offset?: number | null,
};

// Response body for `GET /threads/messages/search`.
export type SearchMessagesResponse = {
	results: SearchMessageResult[],
};

// One thread hit returned by full-text search.
export type SearchThreadResult = {
	id: string,
	title: string,
	rank: number,
	updated_at: string,
};

// Query parameters for `GET /threads/search`.
export type SearchThreadsQuery = {
	q: string,
	limit?: number | null,
	offset?: number | null,
};

// Response body for `GET /threads/search`.
export type SearchThreadsResponse = {
	results: SearchThreadResult[],
};

/**
 *  Request body for `POST /threads/{thread_id}/messages/switch-branch`.
 * 
 *  `direction` is `-1`, `0`, or `1` — left sibling, no sibling change, right
 *  sibling — matching the gRPC contract this replaces.
 */
export type SwitchBranchRequest = {
	message_id: string,
	direction: number,
};

// A persisted thread row as returned to the client.
export type Thread = {
	id: string,
	user_id: string,
	title: string,
	created_at: string,
	updated_at: string,
	active_leaf_id?: string | null,
};

/**
 *  JSON error body returned by the thread service on non-2xx responses.
 * 
 *  Mirrors the shape used by [`activity-core`](https://docs.rs/activity-core)
 *  so the desktop client can decode failures uniformly across HTTP services.
 */
export type ThreadErrorResponse = {
	error: string,
	message: string,
	details?: string | null,
};
