// This file has been generated by Specta. Do not edit this file manually.
/**
 *  Either side may send this to abort an in-flight request identified
 *  by `id`.
 */
export type CancelFrame = {
	id: number,
};

/**  Failure response correlated with a [`RequestFrame`] by `id`. */
export type ErrorFrame = {
	id: number,
	code: number,
	message: string,
	details?: string | null,
};

/**
 *  Unsolicited notification pushed by a client (e.g. browser tab
 *  activation, Word selection change).
 */
export type EventFrame = {
	action: string,
	payload?: string | null,
};

/**
 *  Top-level envelope sent in both directions on the bridge. Every
 *  message is a `Frame`; the [`FrameKind`] discriminator identifies the
 *  payload variant.
 */
export type Frame = {
	kind: FrameKind,
};

/**
 *  Frame payload. Serialized as an externally-tagged JSON object —
 *  `{ "Request": { ... } }` — to match the shape the browser extension
 *  already consumes.
 */
export type FrameKind = ({ Request: RequestFrame }) & { Cancel?: never; Error?: never; Event?: never; Register?: never; Response?: never; Shutdown?: never } | ({ Response: ResponseFrame }) & { Cancel?: never; Error?: never; Event?: never; Register?: never; Request?: never; Shutdown?: never } | ({ Event: EventFrame }) & { Cancel?: never; Error?: never; Register?: never; Request?: never; Response?: never; Shutdown?: never } | ({ Error: ErrorFrame }) & { Cancel?: never; Event?: never; Register?: never; Request?: never; Response?: never; Shutdown?: never } | ({ Cancel: CancelFrame }) & { Error?: never; Event?: never; Register?: never; Request?: never; Response?: never; Shutdown?: never } | ({ Register: RegisterFrame }) & { Cancel?: never; Error?: never; Event?: never; Request?: never; Response?: never; Shutdown?: never } | ({ Shutdown: ShutdownFrame }) & { Cancel?: never; Error?: never; Event?: never; Register?: never; Request?: never; Response?: never };

/**
 *  Mandatory first frame on every connection. Identifies the host
 *  process (the bridge) and the application process being represented.
 * 
 *  `app_pid` is the OS PID for clients that have one (browsers via the
 *  native-messaging host, the macOS launcher representing Safari).
 *  Sandboxed clients without access to a real PID — Office.js add-ins
 *  in particular — synthesize a stable per-session identifier and set
 *  `app_kind` to a logical name (e.g. `"microsoft-word"`) so the
 *  desktop can locate the client without relying on OS process lookup.
 */
export type RegisterFrame = {
	host_pid: number,
	app_pid: number,
	/**
	 *  Logical client identifier for non-PID-based integrations.
	 *  `None` for clients whose `app_pid` corresponds to a real OS
	 *  process discoverable via process-name lookup.
	 */
	app_kind?: string | null,
};

/**  Desktop-initiated request to a connected client. */
export type RequestFrame = {
	id: number,
	action: string,
	payload?: string | null,
};

/**  Client reply to a [`RequestFrame`], correlated by `id`. */
export type ResponseFrame = {
	id: number,
	action: string,
	payload?: string | null,
};

/**
 *  Desktop-initiated request that the receiving client (currently:
 *  browser native-messaging hosts) terminate cleanly. Sent when the
 *  desktop has just installed an updated messenger binary on disk and
 *  wants stale connections to drop so the browser respawns from the new
 *  binary. The `reason` is informational only (logged by the recipient).
 */
export type ShutdownFrame = {
	reason?: string | null,
};

/**
 *  Snapshot of a Word document's textual content as it travels over the
 *  bridge.
 * 
 *  Sent by the Office add-in's runtime as the JSON payload of a
 *  `ResponseFrame` for `GET_ASSETS`. The desktop deserializes this
 *  directly — there is no `NativeMessage` discriminator wrapper because
 *  the WebSocket transport (unlike Chrome's stdio native-messaging)
 *  does not require a single envelope shape per message.
 * 
 *  This is a pure wire type: it derives [`specta::Type`] so it appears in
 *  the TypeScript bindings consumed by the add-in. The desktop wraps it
 *  in a [`WordAsset`] (with a stable UUID) before storing.
 */
export type WordDocumentAsset = {
	/**
	 *  Document title as reported by `Word.Document.properties.title`,
	 *  or a fallback string when the document is unsaved/untitled.
	 */
	document_name: string,
	/**  Full document body text (`Word.Document.body.text`). */
	text: string,
};
