[package]
name = "eur-openai"
version = "0.1.0"
edition = "2024"

[dependencies]
openai-api-rs = { git = "https://github.com/AndreRoelofs/openai-api-rs.git", branch = "main" }
eur-proto = { path = "../../proto/eur-proto" }
base64 = "0.22.0"
config = "0.15.11"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"
thiserror = "2.0.12"
tokio = { workspace = true }
futures-util = "0.3"
futures = "0.3"
eur-util = { path = "../eur-util" }
eur-prompt-kit = { path = "../eur-prompt-kit" }
