[package]
name = "eur-client-questions"
version = "0.0.0"
edition = "2024"
authors = ["Eurora <eurora@company.com>"]
publish = false

[dependencies]
eur-proto = { path = "../../proto/eur-proto" }
eur-client-grpc = { path = "../eur-client-grpc" }
anyhow = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
prost = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
