[package]
name = "eur-fs"
version = "0.0.0"
edition = "2024"
authors.workspace = true
publish = false

[dependencies]
serde = { workspace = true, features = ["std"] }
bstr = { workspace = true }
anyhow = { workspace = true }
walkdir = "2.5.0"
toml = { workspace = true }
