name: Documentation
description: Request to update or improve Eurora documentation
labels: [documentation]
body:
    - type: textarea
      attributes:
          label: What is the improvement or update you wish to see?
          description: The Eurora docs are missing information about X.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Is there any context that might help us understand?
          description: A clear description of any added context that might help us understand.
      validations:
          required: false
    - type: input
      attributes:
          label: Does the docs page already exist? If so, please link to it.
          description: https://docs.eurora-labs.com/features/virtual-branches
      validations:
          required: false
