[package]
name = "eur-stripe-service"
version = "0.1.0"
edition = "2024"
authors = ["Eurora Labs <contact@eurora-labs.com>"]
description = "Eurora Stripe service"
publish = false

[dependencies]
# Stripe
async-stripe = { version = "0.41", features = ["runtime-tokio-hyper-rustls", "webhook-endpoints"] }

# HTTP Server
axum = { version = "0.8.4", features = ["macros", "json"] }
tower = { version = "0.5.2", features = ["util"] }
tower-http = { version = "0.6.6", features = ["cors", "trace"] }

# Async runtime
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal", "fs"] }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"

# Database
eur-remote-db = { path = "../eur-remote-db" }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "uuid", "chrono"] }
uuid = { workspace = true, features = ["v4", "serde"] }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Logging
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Configuration
dotenv = "0.15"
config = "0.15.13"

# Time
chrono = { workspace = true, features = ["serde"] }

# HTTP client
reqwest = { version = "0.12.12", features = ["json"] }
