[package]
name = "eur-auth-client"
version = "0.1.0"
edition = "2024"
authors = ["Eurora <eurora@company.com>"]
description = "Eurora client authentication"
publish = false

[dependencies]
eur-proto = { workspace = true }
anyhow = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
