[package]
name = "eur-client-grpc"
version = "0.0.0"
edition = "2024"
authors.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true, default-features = false }
tracing = { workspace = true }
