[package]
name = "eur-client-grpc"
version = "0.0.0"
edition = "2024"
authors = ["Eurora <eurora@company.com>"]
publish = false

[dependencies]
anyhow = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
