[package]
name = "eur-update-service"
version = "0.1.0"
edition = "2024"
authors = ["Eurora <eurora@company.com>"]
description = "Eurora Update Service"
publish = false

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true, features = ["std"] }
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4", "serde"] }
tracing = { workspace = true }
tracing-subscriber = "0.3"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
tokio = { workspace = true, features = ["full", "tracing"] }
axum = { version = "0.8.4", features = ["macros"] }
tower = "0.5.2"
aws-config = "1.1.7"
aws-sdk-s3 = "1.17.0"
semver = "1.0"
tower-http = { version = "0.6.1", features = ["cors", "trace"] }
