[package]
name = "eur-update-service"
version = "0.1.0"
edition = "2024"
authors = ["Eurora <eurora@company.com>"]
description = "Eurora Update Service"
publish = false

[dependencies]
anyhow.workspace = true
futures = { workspace = true, features = ["std"] }
chrono = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v4", "serde"] }
tracing = { workspace = true }
zerocopy = { version = "0.8.26" }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
tokio = { workspace = true, features = ["full", "tracing"] }
