[package]
name = "eur-timeline"
version = "0.1.0"
edition = "2024"
authors = ["Eurora <eurora@company.com>"]
description = "Timeline storage for capturing system state over time"

[dependencies]
eur-proto = { path = "../../proto/eur-proto" }
image = "0.25.6"
eur-native-messaging = { path = "../eur-native-messaging" }
anyhow = "1.0.97"
chrono = { version = "0.4.40", features = ["serde"] }
tokio = { version = "1.44.2", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
parking_lot = "0.12.1"
eur-screen-capture = { path = "../eur-screen-capture" }
tokio-stream = { workspace = true }
tonic = { workspace = true }
