[package]
name = "eur-secret"
version = "0.0.0"
edition = "2024"
authors.workspace = true
description = "Secret management for Eurora"

[dependencies]
serde = { workspace = true, features = ["std"] }
keyring = { workspace = true }
anyhow = { workspace = true }
tracing.workspace = true
