
[package]
name = "eur-auth-service"
version = "0.0.1"
edition = "2024"
authors = ["Eurora <eurora@company.com>"]
publish = false

[dependencies]
eur-proto = { path = "../../proto/eur-proto" }
eur-remote-db = { path = "../eur-remote-db" }
eur-auth = { path = "../../common/eur-auth" }
anyhow = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
dotenv = "0.15"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
image = { workspace = true }
futures = "0.3"
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
bcrypt = "0.17"
jsonwebtoken = "9.3"
serde = { workspace = true, features = ["derive"] }
[build-dependencies]
tonic-build = { workspace = true }
