name: init-env-node
description: Prepare Node.js Environment
runs:
    using: 'composite'
    steps:
        - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
          name: Setup node
          with:
              node-version-file: '.nvmrc'
        - name: Enable corepack (installs pnpm from packageManager field)
          shell: bash
          run: corepack enable
        - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
          name: Setup pnpm cache
          with:
              cache: pnpm
              node-version-file: '.nvmrc'
        - name: Install dependencies
          shell: bash
          run: pnpm install
