//! Eurora's Microsoft Office desktop integration.
//!
//! This crate is the single home for everything Office-related on the
//! desktop side:
//!
//! - [`WordDocumentAsset`] — the on-the-wire shape exchanged with the
//!   Office add-in over the bridge WebSocket.
//! - [`WordAsset`] — the desktop-side wrapper with a stable UUID, used
//!   by `euro-activity` as a variant of `ActivityAsset`.
//! - [`OfficeApp`] — focus-tracker process-name catalog mirroring
//!   `euro_process::Browser`.
//! - [`fetch_word_asset`] / [`MICROSOFT_WORD_KIND`] — bridge helpers
//!   used by `euro-activity::strategies::word::WordStrategy`.
//!
//! Trait implementations that bind [`WordAsset`] into the activity
//! pipeline (`AssetFunctionality`, `SaveableAsset`) live in
//! `euro-activity` to avoid pulling that crate's dependencies — and the
//! agent-message machinery — into the Office bindings build.
//!
//! Unlike the browser's native-messaging path, the Office add-in is not
//! constrained by Chrome's stdio framing, so no `NativeMessage`
//! discriminator wrapper is needed: the asset struct *is* the payload.
//!
//! TypeScript bindings for the add-in are generated by the bundled
//! codegen binary:
//!
//! ```text
//! cargo run -p euro-office --features codegen -- --generate_specta
//! ```

mod assets;
mod client;
mod office_app;

pub use assets::{WordAsset, WordDocumentAsset};
pub use client::{ACTION_GET_ASSETS, MICROSOFT_WORD_KIND, fetch_word_asset};
pub use office_app::OfficeApp;

/// Build the [`specta::TypeCollection`] containing every type the
/// Office add-in needs on the wire — both the bridge-protocol envelope
/// types (`Frame`, `RegisterFrame`, …) and the office-specific asset
/// types defined in this crate. Emitted as a single TypeScript
/// `bindings.ts` consumed by `apps/office-addin`.
///
/// Desktop-only types (e.g. [`WordAsset`]) are intentionally not
/// registered: they never travel over the wire and would just bloat
/// the bindings file.
pub fn type_collection() -> specta::TypeCollection {
    let mut types = euro_bridge_protocol::type_collection();
    types.register_mut::<WordDocumentAsset>();
    types
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Both the bridge-protocol and office types must appear in the
    /// generated binding so the add-in can build frames and decode
    /// asset payloads from the same file.
    #[test]
    fn type_collection_includes_bridge_and_office_types() {
        let types = type_collection();
        let names: Vec<&str> = types
            .into_unsorted_iter()
            .map(|ndt| ndt.name().as_ref())
            .collect();
        assert!(
            names.contains(&"Frame"),
            "expected bridge-protocol Frame in collection, got {names:?}"
        );
        assert!(
            names.contains(&"RegisterFrame"),
            "expected bridge-protocol RegisterFrame in collection, got {names:?}"
        );
        assert!(
            names.contains(&"WordDocumentAsset"),
            "expected office WordDocumentAsset in collection, got {names:?}"
        );
    }

    /// Desktop-only types must stay out of the wire bindings so
    /// `apps/office-addin` doesn't get a TS interface it can't
    /// satisfy (no `id` is ever sent over the wire).
    #[test]
    fn type_collection_excludes_desktop_only_word_asset() {
        let types = type_collection();
        let names: Vec<&str> = types
            .into_unsorted_iter()
            .map(|ndt| ndt.name().as_ref())
            .collect();
        assert!(
            !names.contains(&"WordAsset"),
            "WordAsset is desktop-only and must not appear in the wire collection, got {names:?}"
        );
    }
}
