//! Asset types and codegen for the Eurora Office add-in.
//!
//! The Office add-in connects to the desktop bridge over WebSocket
//! (see `euro-bridge-protocol`) and exchanges `Frame`s. Office-specific
//! assets — currently only [`WordDocumentAsset`] — are carried as the
//! JSON payload of a `ResponseFrame`.
//!
//! Unlike the browser's native-messaging path, the Office add-in is not
//! constrained by Chrome's stdio framing, so no `NativeMessage`
//! discriminator wrapper is needed. The asset struct is the payload.
//!
//! TypeScript bindings for the add-in are generated by the bundled
//! codegen binary:
//!
//! ```text
//! cargo run -p euro-office --features codegen -- --generate_specta
//! ```

mod assets;

pub use assets::WordDocumentAsset;

/// Build the [`specta::TypeCollection`] containing every type the
/// Office add-in needs on the wire — both the bridge-protocol envelope
/// types (`Frame`, `RegisterFrame`, …) and the office-specific asset
/// types defined in this crate. Emitted as a single TypeScript
/// `bindings.ts` consumed by `apps/office-addin`.
pub fn type_collection() -> specta::TypeCollection {
    let mut types = euro_bridge_protocol::type_collection();
    types.register_mut::<WordDocumentAsset>();
    types
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Both the bridge-protocol and office types must appear in the
    /// generated binding so the add-in can build frames and decode
    /// asset payloads from the same file.
    #[test]
    fn type_collection_includes_bridge_and_office_types() {
        let types = type_collection();
        let names: Vec<&str> = types
            .into_unsorted_iter()
            .map(|ndt| ndt.name().as_ref())
            .collect();
        assert!(
            names.contains(&"Frame"),
            "expected bridge-protocol Frame in collection, got {names:?}"
        );
        assert!(
            names.contains(&"RegisterFrame"),
            "expected bridge-protocol RegisterFrame in collection, got {names:?}"
        );
        assert!(
            names.contains(&"WordDocumentAsset"),
            "expected office WordDocumentAsset in collection, got {names:?}"
        );
    }
}
