[package]
name = "eur-questions-service"
version = "0.1.0"
edition = "2024"
authors = ["Eurora <andre@eurora-labs.com>"]
publish = false

[[bin]]
name = "eur-questions-service"
path = "src/main.rs"

[dependencies]
eur-proto = { path = "../eur-proto" }
tonic = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-openai = "0.28.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
base64.workspace = true
dotenv = "0.15"
