// This file has been generated by Specta. DO NOT EDIT.

export type NativeArticleAsset = { content: string; text_content: string; selected_text: string | null; title: string; site_name: string; language: string; excerpt: string; length: number }

export type NativeYoutubeAsset = { url: string; title: string; transcript: string; current_time: number }

