name: 'Nightly build'
on:
    schedule:
        # every day at 2am
        - cron: '0 2 * * *'
    workflow_dispatch:

jobs:
    trigger-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Publish Workflow
              uses: benc-uk/workflow-dispatch@v1
              with:
                  workflow: Publish
                  token: ${{ secrets.GITHUB_TOKEN }}
                  inputs: '{"channel": "nightly", "bump": "patch"}'
