name: build e2e-runner container
on:
    push:
        branches:
            - main
        paths:
            - 'e2e/blackbox/Dockerfile'
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    docker_publish:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
              with:
                  persist-credentials: false
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push container image
              uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
              with:
                  context: 'apps/desktop/e2e'
                  push: true
                  tags: ghcr.io/eurora-labs/e2e-runner:latest
