name: E2E Tests Webdriver
on:
    pull_request:
        branches: [main]
    workflow_dispatch:
        inputs:
            sha:
                type: string
                required: false
                description: Target SHA

env:
    RUST_BACKTRACE: full
    RUSTUP_TOOLCHAIN: stable
    PUBLIC_STRIPE_KEY: ${{ secrets.PUBLIC_STRIPE_KEY }}

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        env:
            CARGO_TERM_COLOR: always
        steps:
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
              with:
                  persist-credentials: false
              if: ${{ github.event_name != 'workflow_dispatch' }}
            - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
              if: ${{ github.event_name == 'workflow_dispatch' }}
              with:
                  ref: ${{ github.event.inputs.sha }}
                  persist-credentials: false
            - name: Install Tauri OS dependencies
              run: |
                  sudo apt update;
                  sudo apt install -y \
                    build-essential \
                    curl \
                    wget \
                    file \
                    libssl-dev \
                    libgtk-3-dev \
                    libappindicator3-dev \
                    librsvg2-dev \
                    libwebkit2gtk-4.1-0 \
                    libwebkit2gtk-4.1-dev \
                    libgbm-dev \
                    libjavascriptcoregtk-4.1-0 \
                    libjavascriptcoregtk-4.1-dev \
                    gir1.2-javascriptcoregtk-4.1 \
                    gir1.2-webkit2-4.1 \
                    libpipewire-0.3-dev \

                    libsoup-3.0-0 \
                    libayatana-appindicator3-dev \
                    webkit2gtk-driver \
                    ffmpeg \
                    xvfb

            - name: Setup rust-toolchain stable
              id: rust-toolchain
              uses: dtolnay/rust-toolchain@5d458579430fc14a04a08a1e7d3694f545e91ce6 # stable
            - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: cargo-${{ steps.rust-toolchain.outputs.cachekey }}-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: cargo-
            - name: Setup node environment
              uses: ./.github/actions/init-env-node

            - name: Install Protoc
              uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3

            - name: Compile Protobuf
              run: pnpm proto:typescript

            - name: Build SvelteKit
              run: pnpm build -- --mode development

            - name: Build Tauri
              run: pnpm tauri build --debug

            - name: Install tauri-driver
              run: |
                  if [ ! -e "$HOME/.cargo/bin/tauri-driver" ]; then
                    cargo install tauri-driver
                  fi

            # Run it through `xvfb-run` to have a fake display server which allows our
            # application to run headless without any changes to the code
            - name: WebdriverIO
              run: xvfb-run pnpm test:e2e

            - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
              if: failure()
              with:
                  name: WebdriverIO Artifacts
                  overwrite: true
                  path: |
                      ./apps/desktop/e2e/videos
                      ~/.config/com.eurora.app*/logs
